### ISSUE TITLE
Postprocessor extract_prediction_answers not found

### ISSUE THREAD

**Issue by wdkwyf** [openvinotoolkit/open_model_zoo#1078]
Hi,
I noticed in postprocessor\README.md, there are `extract_prediction_answers`. However, it hasn't been implemented. I want to postprocess the output of bert network and when will it be ready?

**Comment by wdkwyf** [comment]
Maybe it's a mistake in README.md, I found ExtractSquadPrediction instead.

**Comment by eaidova** [comment]
it is not mistake, we have such postprocessing https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/accuracy_checker/postprocessor/extract_answers_tokens.py#L29

Please, make sure that you use correct accuracy checker version

**Comment by eaidova** [comment]
I am sorry,  postprocessor named `extract_prediction_tokens` not answers.

**Comment by IRDonch** [comment]
@eaidova I don't think you should've closed this; I just checked the latest `develop` and the docs still refer to a nonexistent `extract_prediction_answers` postprocessor. Could you fix the docs?

**Comment by eaidova** [comment]
@IRDonch  I believe, now it can be closed?
