### ISSUE TITLE
security_barrier_camera_demo got stuck in infinite loop without any UI show

### ISSUE THREAD

**Issue by zhangguobin** [openvinotoolkit/open_model_zoo#1081]
OS: Ubuntu 16.04.6 LTS
OpenVINO version: openvino_2020.1.023
Reproduce rate: 80%
Here is the command to reproduce the issue:

./security_barrier_camera_demo -i ~/sample-videos/output.mp4 ~/sample-videos/output.mp4  -m ~/models/intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml -m_va ~/models/intel/vehicle-attributes-recognition-barrier-0039/FP16/vehicle-attributes-recognition-barrier-0039.xml -m_lpr ~/models/intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml -d HDDL -d_va HDDL -d_lpr HDDL -n_iqs 10 -n_wt 4 -nireq 10 -loop_video

**Comment by Wovchena** [comment]
Is the issue reproducible for 2020.2.120?

Is the issue reproducible for CPU for each model (for 2020.2.120)?
Is the issue reproducible for -n_wt 1 (for 2020.2.120)?

**Comment by zhangguobin** [comment]
I don't have 2020.r2 yet, I built this demo from open_model_zoo directly. 
It can be reproduced with CPU or -n_wt 1
I will be on holiday next week, you may have to test it by yourself.

**Comment by AnthonyQuantum** [comment]
Right now, this is not reproducible with Ubuntu 18.04, OpenVINO 2020.2.120 and the following command:
./security_barrier_camera_demo -i ~/OMZ/datasets/1min_yolo_video.mp4 ~/OMZ/datasets/1min_yolo_video.mp4 -m ~/OMZ/models/intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml -m_va ~/OMZ/models/intel/vehicle-attributes-recognition-barrier-0039/FP16/vehicle-attributes-recognition-barrier-0039.xml -m_lpr ~/OMZ/models/intel/vehicle-license-plate-detection-barrier-0106/FP16/vehicle-license-plate-detection-barrier-0106.xml -d CPU -d_va CPU -d_lpr CPU -n_iqs 10 -nireq 10 -n_wt 1

@zhangguobin, does the demo get stuck on one video frame or all video frames are displayed correctly and there are just no UI?

**Comment by zhangguobin** [comment]
@AnthonyQuantum , just no UI, I did debug the task workflow before, it gave me the impression that no task is ready, so the pipeline engine was not started at all.
I will upgrade my OpenVINO and retest it later, thanks!

**Comment by vladimir-dudnik** [comment]
@zhangguobin I'm going to close this, as OpenVINO 2021.4 release published. Feel free to reopen if you have additional questions
