### ISSUE TITLE
yolov3_tiny_3l.cfg support! 

### ISSUE THREAD

**Issue by goodtogood** [openvinotoolkit/open_model_zoo#1110]
I found the [doc ](https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html)
but it's just for yolov3 and yolov3_tiny.
how to convert [yolov3_tiny_3l.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov3-tiny_3l.cfg) ?
thx!

**Comment by vladimir-dudnik** [comment]
@goodtogood have you found solution?

**Comment by vladimir-dudnik** [comment]
@goodtogood I'm going to close this, feel free to reopen if you still have questions
