### ISSUE TITLE
Unable to understand the logic behind the `object_detection_demo_yolov3_async.py` demo

### ISSUE THREAD

**Issue by pra-dan** [openvinotoolkit/open_model_zoo#1171]
I noticed that the [recent pull](https://github.com/eizamaliev/open_model_zoo/blob/yolo_demo_ref/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py) for the file `object_detection_demo_yolov3_async.py` did try to remove the otherwise confusing flattening of blob but I still can't figure out how most of the results are parsed from this blob. 

Is there some YOLO guide that you guys (@eizamaliev ) followed (except the official paper which is not so clear)?

**Some** example snippets that I don't understand include 
1. `if is_proportional:` in the [line131](https://github.com/eizamaliev/open_model_zoo/blob/095312bd1699faab2ad425fb4275640b7d16326d/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py#L131). What was the purpose behind introducing this additional parameter to pass around the functions?

2. In the [part](https://github.com/eizamaliev/open_model_zoo/blob/095312bd1699faab2ad425fb4275640b7d16326d/demos/python_demos/object_detection_demo_yolov3_async/object_detection_demo_yolov3_async.py#L167)
```
       # Process raw value
        x = (col + x) / params.side
        y = (row + y) / params.side
```
I can't understand how the `x`,`y` (values) are added with `row` and `col` is right. I mean what is the logic behind it? 

Please help me get a clear understanding of the YOLO decoding :/

**Comment by eizamaliev** [comment]
Hi, @pra-dan. Thanks for your questions, I'll try to answer them all.
1. Demo supports two resize type: with aspect ratio kept and without. Because initially was used simple resize, this behavior is saved as default. So `is_proportional` parameter tells to the function how it should rescale output boxes.

2. As you can know, YOLO generate local coordinates relative to the cell. To get coordinates relative to image, you should add cell coordinates. By dividing by cell count across corresponding direction, you normalize coordinates.

**Comment by pra-dan** [comment]
Thanks @eizamaliev . I do understand the second question and answer. But regarding the first of your answers, I can't find this anywhere else... I mean the how did you know if this is how the result was packed ? Is there any source ?

I will work on it and then try clarifying some other doubts if you do not mind :)

**Comment by eizamaliev** [comment]
@pra-dan some info you could find in official paper, site and repo. In fact in these three sources enough information about model, but it is quite scattered. :(

And one more thing - the original model requires sigmoid function to be applied to coordinates, object score and probalilities values, but converted to IR - doesn't.

If you have no more question, I'll close this issue.

**Comment by pra-dan** [comment]
I am working on it. Please leave it open for some time. I will close it on my own. I may have some other minor related-issues. Creating new issues for it will be too much.

**Comment by pra-dan** [comment]
Also, kindly share the libraries/packages required for this new program. Installing `monitors` gives error. 
```
$ pip install monitors
ERROR: Could not find a version that satisfies the requirement monitors (from versions: none)
ERROR: No matching distribution found for monitors
```

**Comment by eizamaliev** [comment]
`monitors` is a local cpp-library, it is built with cpp demos via `build_demos.sh` or `build_demos_msvc.bat` script in `demos` dir.

**Comment by GotG** [comment]
unfortunately build_demos.sh fails for me. my old intel processor might be at fault.
how can i install the `monitors` library?

**Comment by GotG** [comment]
> `monitors` is a local cpp-library, it is built with cpp demos via `build_demos.sh` or `build_demos_msvc.bat` script in `demos` dir.
> It could be ignored.

what do you mean by ignored? thanks

**Comment by GotG** [comment]
i ran the build_demos.sh and yet monitors still missing. how can i install monitors manually?

also you mention it could be ignored?

**Comment by vladimir-dudnik** [comment]
@pra-dan do you have an additional questions or we can close the issue?

**Comment by pra-dan** [comment]
Yeah, we are good to go 👍🏽
