### ISSUE TITLE
Unable to find the labels

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/open_model_zoo#1254]
for example, I cannot find the label corresponding to the **action-recognition-0001**

**Comment by eaidova** [comment]
@x1aoo , according documentation, model has the same labels order like in Kinetics-400 dataset. Please refer to the [kinetics](https://deepmind.com/research/open-source/kinetics) dataset specification to see list of action that are recognised by this model.

**Comment by x1aoo** [comment]
thanks！
