### ISSUE TITLE
How to infer head pose and landmarks?

### ISSUE THREAD

**Issue by vinicius121** [openvinotoolkit/open_model_zoo#1265]
Hi!

I've essentially two questions.
Nº1:
I'm doing inference using OpenVino's head-pose-estimation-adas-0001 model in C# using OpenCvSharp.
My code is the following:
```
var blob2 = CvDnn.BlobFromImage(face, 1.0, new OpenCvSharp.Size(60, 60), new OpenCvSharp.Scalar(0, 0, 0), false, false);
netHead.SetInput(blob2);
var outNames = netHead.GetUnconnectedOutLayersNames(); // three layer names (yaw, pitch, and roll)
using (var detectAngles = netHead.Forward(outNames[0]))
{
     Debug.WriteLine(detectAngles.At<float>(0,0));
}
```
However, the value that I obtain is always 0 or a huge number for pitch and roll. The yaw seems to be the only working.  So I think I'm accessing the angles in the right way. I've tried to look for examples on OpenCV in C++ with IE since OpenCvSharp is just a directly wrapper around OpenCV but I can only and barely find samples in python. Anyone might know how to properly get the output from the network?

Nº2:

For the facial landmark detection I'm using the facial-landmarks-35-adas-0002 model. I can successfully retrieve and draw the landmarks but they are not properly drawn (see image). Each point I multiply by the width and height of the original image.
![image](https://user-images.githubusercontent.com/28484866/85649447-1bc06080-b69b-11ea-9b70-9e4c75d35e2e.png)
 Here is my code: 
```
var outputFL = netFL.Forward()

List<OpenCvSharp.Point> points = new List<OpenCvSharp.Point>();
float[] dataArr = new float[70];

for (int i = 0; i < outputFL.Cols; i++)
{
	dataArr[i] = outputFL.At<float>(0, i);              
}
for(int j=0; j < dataArr.Length; j += 2) { points.Add((OpenCvSharp.Point)new Point2f(dataArr[j]* frameWidth, dataArr[j + 1]* frameHeight)); } //frameWidth=640 and frameHeight=480

foreach (var point in points) 
{
	Cv2.Circle(image, (int)point.X, (int)point.Y, 2, new Scalar(255, 255, 255), -1);
}
``` 
Any help?
Thanks

**Comment by Wovchena** [comment]
I think I have an answer for the second question.
* facial-landmarks-35-adas-0002 expects a crop of an image containing a face, but not the whole image. I cant't say what you did, so this is just a clarification.
* Given that facial-landmarks-35-adas-0002 sees only a crop of an image you need to multiply output values by a size of the crop but not the original image. (And take into account the position of the crop before putting landmarks on the original image.)

**Comment by vinicius121** [comment]
Yes, I do crop the original image after the face is detected.  If I adjust the width and height to the crop I get the following:
![image](https://user-images.githubusercontent.com/28484866/85868708-92a44900-b7c2-11ea-8f76-bf766bd47244.png) The points  are shifted. How do I draw the circles taking into account the position of the crop? Is there any OpenCV function for doing that?

**Comment by Wovchena** [comment]
The area covered by landmarks looks similar to the detected area now.
To perform shifting just add X coord of top left corner of the crop to X coords of each circle. The same with Y. Alternatively, yes, you can draw them in the crop without shifting. But take into account that you want to draw on a cropped region of the original image but not the copied version of that region. So if you didn't request a copy of the cropped region earlier it should work.

**Comment by vinicius121** [comment]
Ok so I did that but the points seems not to be drawn correctly:
![image](https://user-images.githubusercontent.com/28484866/85880643-42ce7d80-b7d4-11ea-8653-2b4601b1511a.png)
Here is the code:
```
// face detection
int x1 = (int)(detectionMat.At<float>(i, 3) * frameWidth); //xmin
int y1 = (int)(detectionMat.At<float>(i, 4) * frameHeight); //ymin
int x2 = (int)(detectionMat.At<float>(i, 5) * frameWidth); //xmax
int y2 = (int)(detectionMat.At<float>(i, 6) * frameHeight); //ymax    

OpenCvSharp.Rect roi = new OpenCvSharp.Rect(x1, y1, (x2 - x1), (y2 - y1));
Mat face = new Mat(image, roi);

var blob2 = CvDnn.BlobFromImage(face, 1.0, new OpenCvSharp.Size(60, 60), new OpenCvSharp.Scalar(0, 0, 0), false, false);
//Landmark detection
netFL.SetInput(blob2);
var outputFL = netFL.Forward()
var points = RetrieveFacialLandmarks(outputFL, x2 - x1, y2 - y1, x1, y1);

foreach (var point in points) 
{
	Cv2.Circle(image, (int)point.X, (int)point.Y, 2, new Scalar(255, 255, 0), -1);
}

private List<OpenCvSharp.Point> RetrieveFacialLandmarks(Mat mat, int frameWidth, int frameHeight, int topX, int topY)
{
	List<OpenCvSharp.Point> points = new List<OpenCvSharp.Point>();
	float[] dataArr = new float[70];

	for (int i = 0; i < mat.Cols; i++)
	{
		dataArr[i] = mat.At<float>(0, i);              
	}
	for(int j=0; j < dataArr.Length; j += 2) { points.Add((OpenCvSharp.Point)new Point2f(dataArr[j]* frameWidth + topX, dataArr[j + 1]* frameHeight + topY)); }

	return points;
}
```

**Comment by vinicius121** [comment]
Yes that is it. Any help regarding my first question? Only the yaw works.
Thanks

**Comment by vinicius121** [comment]
Hi any updates about the head orientation model? 
Only the yaw is working...

**Comment by Wovchena** [comment]
I can only suggest to check that the model works with `gaze_estimation_demo` and to align your application with the demo.

**Comment by vinicius121** [comment]
Ok! I got it working. thanks!
