### ISSUE TITLE
Demo on macOS

### ISSUE THREAD

**Issue by thibault390** [openvinotoolkit/open_model_zoo#1293]
Hi,

Can someone explain me what's the purpose of the  "-fg " parameter "Path to the face images directory" please ? I'm not sure and how to use the facetime camera for macOS because "-i cam " doesn't work here? 

Thanks

**Comment by thibault390** [comment]
It's ok I solved my problem

**Comment by Wovchena** [comment]
Hi,

`-fg` sets a gallery so the demo could assign names to faces it finds on input (assuming the question is about `face_recognition_demo`).

**Comment by thibault390** [comment]
Ok thanks for the reply :)

**Comment by vladimir-dudnik** [comment]
closing this as it seems the original question was answered
