### ISSUE TITLE
how to build text_detection_demo

### ISSUE THREAD

**Issue by rawat123** [openvinotoolkit/open_model_zoo#1296]
hi i have setup openvino on my window10 machine, and can run sample app object_detection_ssd with python api, how can i build text_detection_demo, and if there is some python api sample to use text_detection_recognition demo.

**Comment by Wovchena** [comment]
Hi, there is an instruction https://github.com/opencv/open_model_zoo/tree/master/demos#build-the-demo-applications which builds every demo. There is also a similar python demo but designed to use different models comparing to `text_detection_demo`: [`text_spotting_demo`](https://github.com/opencv/open_model_zoo/tree/master/demos/python_demos/text_spotting_demo).

**Comment by rawat123** [comment]
thanks for your reply, i will look into it

**Comment by rawat123** [comment]
i am setting up openvino in windows machine
there is setupvars.bat file which setups openvino environment variables, and after executing it in cmd in the same cmd i can run python scripts with import openvino , can i setup all these variables in python script so i don't need to run setupvars.bat file separately.

and with c++ samples can i manage it as library for my c# winform application, i don't want to access it as command line because it will load IR model every time.

**Comment by Wovchena** [comment]
You could set env vars which are set by `setupvars.bat` in Windows settings so your `PATH` and `PYTHONPATH` vars always has values for OpenVINO.

I think technically it is possible to link you your app with some demos libraries, but you shouldn't do that.
1. It will be easier to  write your own library. I'm not  aware of Inference Engine C# wrappers, but you could use OpenCV's wrappers and run inference from it.
2. Demos aren't designed to be used as libraries.

**Comment by vladimir-dudnik** [comment]
closing this as it seems the original question was answered
