### ISSUE TITLE
Yolov3 Python Demo erroneous detections

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/open_model_zoo#1325]
Using `object_detection_demo_yolov3_async.py` produces the following output on yolov3 tiny coco model:

![errors](https://user-images.githubusercontent.com/61444721/87575908-48cfc400-c6d9-11ea-96e4-01387ec05e37.png)

**Comment by eizamaliev** [comment]
@GotG you can tune IoU threshold to eliminate such behavior (`-iout` option)

**Comment by GotG** [comment]
the issue can be mitigated with extreme iout of 0.1. with this extreme iout i may get only the smaller box to display, which is clearly wrong.
this points to the more important fact that one of the layers outputs boxes that are wrong. 
prior implementations of yolov3 async demo.py from previous openvino releases display the same error.
