### ISSUE TITLE
yolov3 async demo .py code question

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/open_model_zoo#1331]
Hello

In object_detection_demo_yolov3_async.py why is the reshape needed? the output.buffer already has the required shape before the reshape. also why is buffer used (i see this as a recent change). thank you

`out_blob = out_blob.buffer.reshape(net.layers[net.layers[layer_name].parents[0]].out_data[0].shape)`

**Comment by GotG** [comment]
thanks! given the name of the demo did not think of that.
also the buffer in the network out_blob holds the tensor. this seems to be a newer addition to openvino?
i used to get the results from the output like this:
`results = output[layer_name]`
now if i do the same i get a blob object so i have to access its buffer to get to the numbers.
is my understanding correct? do you know why this change? thanks!

**Comment by eaidova** [comment]
@GotG, it is changes in Inference Engine python API, old deprected property infer_request.outputs return numpy arrays as outputs (blob unpackaging made inside python API before) in the dictionary, new API with name output_blobs return blob objects as values in the dict and you need to get buffer. It was made for alignment with C++ interface. Blob class in python needs for providing such opportunities like usage IE Preprocessing capabilities and manipulation with tensor description, which are usual things for C++ API.

**Comment by GotG** [comment]
thanks. can you show me what is the best way to keep up with OpenVINO python API changes? thanks again
