### ISSUE TITLE
Can I download weightts for intel  head-pose-estimation-adas-0001?

### ISSUE THREAD

**Issue by innjoshka** [openvinotoolkit/open_model_zoo#1347]
I see ptototxt file inside the folder but no weights inside, Can you please provide the link to download these weights?

**Comment by eaidova** [comment]
@innjoshka, I am sorry, but this model distributed in openvino IR format only, prototxt provided for posibilities of model architecture analisys. We do not have plan for sharing weights (caffemodel), it means you can download and use only xml+bin (where bin-file represents model weights for running via openvino)
