### ISSUE TITLE
faster_rcnn_resnet50_coco with bs 32 get wrong image_info

### ISSUE THREAD

**Issue by qiyuangong** [openvinotoolkit/open_model_zoo#1363]
OpenVINO version 2020.3
open_model_zoo master

I'm trying to covert faster_rcnn_resnet50_coco with batch 32. By change https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/faster_rcnn_resnet50_coco/model.yml#L30 into `[32,600,1024,3]`, I get a converted model with bs 32 input. 

But, `image_info` is still `1,3` rather than `32,3`. This difference may leads to input shape mismatch when using these code https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo_faster_rcnn/main.cpp#L224

I believe this issue impact all faster_rcnn models from TensorFlow.

**Comment by eizamaliev** [comment]
@qiyuangong please try TF fasters with [object_detection_demo_ssd_async](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo_ssd_async).

**Comment by qiyuangong** [comment]
Hi @eizamaliev . Thank you for response!

I have tried SSD examples. It works well. But for faster_rcnn from TensorFlow, it doesn't. Pls check faster_rcnn example and related code.

**Comment by eizamaliev** [comment]
@qiyuangong please describe what did go wrong with faster-rcnn from TF on object_detection_demo_ssd_async.

**Comment by IRDonch** [comment]
I believe this is no longer relevant. The unified object detection demo will always force the batch size to 1, so it will work regardless of what the input model's batch size is.
