### ISSUE TITLE
The distillation method of bert-small-uncased-whole-word-masking-squad-0001

### ISSUE THREAD

**Issue by cocokale** [openvinotoolkit/open_model_zoo#1374]
For the bert-small-uncased-whole-word-masking-squad-0001 model, the description document says that it is distilled on SQuAD v1.1 training set. Could anyone please kindly share the exact distillation method of it, because obviously there exist many distillation methods...
Thanks!

**Comment by eaidova** [comment]
@krodyush, could you please answer, if it is possible?
Thanks!
