### ISSUE TITLE
FPS issue in Human pose estimation 3D model

### ISSUE THREAD

**Issue by aswin-datakalp** [openvinotoolkit/open_model_zoo#1378]
Hi Team , 

I a using **human-pose-estimation-3d-0001** model and converting the model using the below thread:

https://github.com/openvinotoolkit/open_model_zoo/issues/1346#issuecomment-662944002

I have converted the model into 4 different precision formats namely : FP32, FP16 , float and half.

The problem we are facing is with FPS. We noted the following FPS on an average of few sets:

FP32 - 14 FPS
FP16 - 7 FPS
float - 8 FPS
half - 6 FPS

As per my understanding, when we lower the precision points while converting the model to open vino IR format , 
it should result with an increase in FPS. But what we observed seems to be opposite to the hypothesis.

Can you please clarify on the same ?

Thanks 

Aswin Prabhakaran

**Comment by eizamaliev** [comment]
@aswin-datakalp could you provide some additional info:
- Which device did you use for inference?
- How did you obtain each model?
Provide as much info as you can: it makes easier further investigation.

**Comment by vladimir-dudnik** [comment]
@aswin-datakalp still the issue is actual for you? Note, OpenVINO 2021.1 was just released, you might be interested to evaluate the latest release. We'll close the issue if this is not actual or no comments from you.

**Comment by aswin-datakalp** [comment]
Hi @vladimir-dudnik , 

yes will check the latest release of OpenVINO 2021.1 and revert back. This issue can be closed for now.
