### ISSUE TITLE
how to prepare VOC2012_Segmentation datasets

### ISSUE THREAD

**Issue by x1aoo** [openvinotoolkit/open_model_zoo#1414]
Hi,

I am trying to test the accuracy of the deeplabv3 model, but it requires the **VOC2012_Segmentation** in [deeplabv3.yml](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/accuracy_checker/configs/deeplabv3.yml) rather than the dataset you can see in [Dataset Preparation Guide](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/datasets.md).

Is there any guideline for preparing  VOC2012_Segmentation?

Thanks!

**Comment by Anna-Mironova** [comment]
[Pull request](https://github.com/openvinotoolkit/open_model_zoo/pull/1425) with VOC2012 dataset preparation has been created

**Comment by x1aoo** [comment]
thanks！
