### ISSUE TITLE
[Legal question] Is it legal to use pre-trained models from the model zoo for commercial purposes?

### ISSUE THREAD

**Issue by ternaus** [openvinotoolkit/open_model_zoo#1433]
I see discussions at

* [Reddit](https://www.reddit.com/r/MachineLearning/comments/4eu2vd/can_pretrained_networks_be_used_in_commercial/)
* [Kaggle](https://www.kaggle.com/c/deepfake-detection-challenge/discussion/131121)
* [PyTorch forum](https://discuss.pytorch.org/t/can-i-use-the-pretrained-models-for-commercial-use/54279)
* [Authors Guild, Inc. v. Google, Inc.](https://en.wikipedia.org/wiki/Authors_Guild,_Inc._v._Google,_Inc.)

But there is no definitive answer.

**Comment by ternaus** [comment]
Similar question to:
* Google: https://github.com/tensorflow/models/issues/9131
* Facebook: https://github.com/pytorch/vision/issues/2597

**Comment by vladimir-dudnik** [comment]
@ternaus please contact your company legal department for conditions of use under certain license questions.

**Comment by ternaus** [comment]
> @ternaus please contact your company legal department for conditions of use under certain license questions.

It is a separate question.

Let's focus on the original. OpenVino provides models. What does the legal department at Intel thinks about pre-trained models provided by OpenVino:

I am fine with either of the answers:

* They could be used only for non-commercial purposes.
* They could be used for commercial purposes.
* We do not know. Use them at your own risk.

And it will be great to write it **clearly** on the page with pre-trained models. 

Or something like:

Models A, B, C - non-commercial.
D, E, F - research only.
G, F, I - we have no clue.

The community needs a bit of transparency on the topic.

**Comment by ternaus** [comment]
As I understand:

> What is the outbound license for the github repositories of OpenVINO™ toolkit?
> All content of OpenVINO™ toolkit are distributed under Apache License, Version 2.0

in https://01.org/openvinooolkit/faq

is very close to what will be nice to have.

If there will be a line in FAQ or statement at the page with the list of pre-trained models:

> Q: What is the license for pre-trained models?
> A: The license for all pre-trained models is Apache-2.

It would solve all the issues.

**Comment by BoPengGit** [comment]
Hi Vlad,

Good to see you here. Thanks for hosting Lyft competitions on Kaggle! 

Do you guys have more comments on this? I feel if I train a model on images that do not allow commercial usage, I should be able to use the weights in a commercial setting if I do not use any of the images. 

For example, the end product will have no images of the dataset at all, but only a model with some numbers. Isn't that what BERT is all about, it trains on all these texts that could have private information, but the end model contains no private text, only numbers from a pretrained weight. And BERT is allowed for commercial use.

Thank you guys!
