### ISSUE TITLE
How to get label map for product-detection-0001

### ISSUE THREAD

**Issue by just4give** [openvinotoolkit/open_model_zoo#1441]
Hi,
I am fairly new to this field and wondering where I can find the label map for this model. Should it be generated ? If so, how? Any help is appreciated. Thanks.

**Comment by eaidova** [comment]
Hi @just4give  according to [model description](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/product-detection-0001/description/product-detection-0001.md):
```
 The network can detect 12 classes of objects (sprite, kool-aid, extra, ocelo, finish, mtn_dew, best_foods, gatorade, heinz, ruffles, pringles, del_monte). Labels 0 and 1 are related to background_label and undefined correspondingly.
```
so the label map looks like:
0. background
1. undefined
2. sprite
3. kool-aid
4. extra
5. ocelo
6.  finish
7. mtn_dew
8. best_foods 
9. gatorade
10. heinz
11.  ruffles
12. pringles
13. del_monte
