### ISSUE TITLE
Downloader script not working for resnet-50

### ISSUE THREAD

**Issue by anirudt** [openvinotoolkit/open_model_zoo#1475]
Hi,

The downloader script does not seem to work for resnet-50, is there anything I am missing here?

```
$ ./downloader.py --name "resnet-50" -o ./
################|| Downloading models ||################

========== Downloading public/resnet-50/resnet-50.prototxt
... 22%, 6 KB, 13589 KB/s, 0 seconds passed
########## Error: Downloaded file is shorter (7161 B) than expected (32500 B)

################|| Post-processing ||################

FAILED:
resnet-50
```

But "resnet-50" is a valid string (`--print_all` does show it)..

**Comment by vladimir-dudnik** [comment]
@anirudt we see the same on our side. It seems model is no more available on its original location, so we will have to exclude resnet-50, resnet-101 and resnet-152 Caffe models in the coming release. See [PR-1419](https://github.com/openvinotoolkit/open_model_zoo/pull/1419) and [PR-1494](https://github.com/openvinotoolkit/open_model_zoo/pull/1494)

**Comment by anirudt** [comment]
I see, thank you for your reply.
