### ISSUE TITLE
What is the use of MultipleOutputPostprocessor in object_detection_demo_ssd_async? No comments provided.

### ISSUE THREAD

**Issue by anujonthemove** [openvinotoolkit/open_model_zoo#1482]
Recently, the code for object_detection_demo_ssd_async got updated. I see that it now includes two classes: `SingleOutputPostprocessor` and `MultipleOutputPostprocessor` using which the output buffer gets defined. 

I know that SSD Mobilenet models outputs 3 tensors namely: boxes, scores, labels for which `MultipleOutputPostprocessor` would be used but I just converted the available ssd_mobilenet_v2_coco model(downloaded via model_downloader), loaded and printed out net.outputs which gives me only one tensor `{'DetectionOutput': <openvino.inference_engine.ie_api.DataPtr at 0x7fe836957dd0>}`. This will simply utilize `SingleOutputPostprocessor`. 

Since this demo is specifically for SSD object detection, I would like to know for which model implementation would we use `MultipleOutputPostprocessor`. Do we need this class here at all or am I missing something I should know? 

I am currently using toolkit version 2020.3, the demo is for toolkit version 2020.4 but I modified the code to make it work on the previous one by not using the '.buffer' when getting the tensor(s).

Here is what I did:
I returned `outputs[self.output_layer][0][0]` instead of `outputs[self.output_layer].buffer[0][0]` inside the `__call__()` method of `SingleOutputPostprocessor` class.

_Also, what is the use of utilization monitors in the code?_

I believe relevant explanations/comments would help here.

**Comment by eizamaliev** [comment]
Hi, @anujonthemove 
It is used for [SSD-ResNet34](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/models/public/ssd-resnet34-1200-onnx/ssd-resnet34-1200-onnx.md) model, since it has separate outputs for boxes, probabilities and classes.

**Comment by anujonthemove** [comment]
> Hi, @anujonthemove
> It is used for [SSD-ResNet34](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/models/public/ssd-resnet34-1200-onnx/ssd-resnet34-1200-onnx.md) model, since it has separate outputs for boxes, probabilities and classes.

Got it! Thank you so much for your response.
