### ISSUE TITLE
Can not download model person-reidentification-retail-0277/ 288/287 ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [openvinotoolkit/open_model_zoo#1486]
Hello,

I tried to download these model but i could not get it. Please check it   

![image](https://user-images.githubusercontent.com/57557628/91723001-667abf00-eb9b-11ea-84aa-517b6a588dbe.png)

**Comment by eaidova** [comment]
@hoangkhoiLE these models will be available only for the next release. you use openvino_2020.4.287, where the same model architectures represented as person-reidentification-retail-0265/267/270. Please try to use them.

**Comment by hoangkhoiLE** [comment]
Thank you for your excellent work!!
