### ISSUE TITLE
GT format for multi-target demo

### ISSUE THREAD

**Issue by zvif** [openvinotoolkit/open_model_zoo#1487]
What is the gt format when using the multi_camera_multi_target_tracking python code? 
I would like to use the run_history_visualize.

**Comment by vladimir-dudnik** [comment]
@sovrasov @DmitriySidnev @snosov1 could you please comment on this question?

**Comment by DmitriySidnev** [comment]
@zvif, hi!
Ground truth annotations can be obtained via annotation tool [CVAT](https://github.com/opencv/cvat). Minimal set and format of attributes:
```json
[
  {
    "name": "person",
    "id": 1,
    "color": "#c06060",
    "attributes": [
      {
        "id": 11,
        "name": "id",
        "input_type": "text",
        "mutable": false,
        "values": [
          " "
        ]
      },
    ]
  }
]
```
I am going to add possibility of reading annotations from *\*.txt* files like in MOT17, MOT20 challenges.

**Comment by zvif** [comment]
The *.txt would be great. 
I thought I could use the "datum convert" from the CVAT https://github.com/opencv/cvat/tree/develop/datumaro toolbox and I tried to convert (MOT challenge format) using the CVAT (-f cvat) format that wasn't recognized. Is there a different conversion?

**Comment by DmitriySidnev** [comment]
Actually, I have never used this converter. There is an option for MOT but the result may have some minor difference (in respect that you already tried).

**Comment by zvif** [comment]
Is there any recommended way of conversion? I have GT in a simple text file (csv). I would love to use the tool.

**Comment by DmitriySidnev** [comment]
Please take a look at this [code](https://github.com/DmitriySidnev/open_model_zoo/blob/ds/mot_eval/demos/python_demos/multi_camera_multi_person_tracking/evaluate_mot.py). There is a support for reading annotations from **.txt* files like in MO17(20).

**Comment by vladimir-dudnik** [comment]
@zvif do you have an additional questions on this or we can close the issue?

**Comment by zvif** [comment]
We can close this issue. Thank you very much.

**Comment by vladimir-dudnik** [comment]
ok, closing this
