### ISSUE TITLE
Running security_barrier_camera_demo with yolo-v2-tiny-vehicle-detection-0001

### ISSUE THREAD

**Issue by coneypo** [openvinotoolkit/open_model_zoo#1509]
Hi, 

`yolo-v2-tiny-vehicle-detection-0001` has been added into open_model_zoo (https://github.com/openvinotoolkit/open_model_zoo/pull/1156), but seems not working with `security_barrier_camera_demo`

> # Security Barrier Camera C++ Demo
> 
> This demo showcases Vehicle and License Plate Detection network followed by the Vehicle Attributes Recognition and License Plate Recognition networks applied on top
> of the detection results. You can use a set of the following pre-trained models with the demo:
> * `vehicle-license-plate-detection-barrier-0106` or `vehicle-license-plate-detection-barrier-0123`, which is primary detection network to find the vehicles and license plates

Worked with vehicle-license-plate-detection-barrier-0106 for detecting:
`
./security_barrier_camera_demo -i road_barrier_1080.mp4 -m vehicle-license-plate-detection-barrier-0106.xml -m_va bkc/models/vehicle-attributes-recognition-barrier-0042.xml`

Not working with yolo-v2-tiny-vehicle-detection-0001 for detecting:
`./security_barrier_camera_demo -i road_barrier_1080.mp4 -m yolo-v2-tiny-vehicle-detection-0001.xml -m_va vehicle-attributes-recognition-barrier-0042.xml`

Got following error:

> [ INFO ] InferenceEngine: 0x7f5fca33f030
> [ INFO ] Files were added: 1
> [ INFO ]     road_barrier_1080.mp4
> [ INFO ] Loading device CPU
>         CPU
>         MKLDNNPlugin version ......... 2.1
>         Build ........... 2020.4.0-359-21e092122f4-releases/2020/4
> 
> [ INFO ] Loading detection model to the CPU plugin
> [ ERROR ] unexpected ProposalCount

So will we support `security_barrier_camera_demo` with `yolo-v2-tiny-vehicle-detection-0001`or sth I can do like modifying  `security_barrier_camera_demo` source code in `/opt/intel/openvino_2020.4.287/deployment_tools/inference_engine/demos/security_barrier_camera_demo/net_wrappers.hpp` to enable `yolo-v2-tiny-vehicle-detection-0001`?

>  if (maxProposalCount != outputDims[2]) {
>             throw std::logic_error("unexpected ProposalCount");
>         }

Thanks

**Comment by eizamaliev** [comment]
Hi, @coneypo 
Appears, that this model isn't supported by `security_barrier_camera_demo` as we can see it absence in [models.lst](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/security_barrier_camera_demo/models.lst) file. I recommend you to use Python's [object detection demo](https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/python_demos/object_detection_demo_yolov3_async).

**Comment by coneypo** [comment]
Thanks, Eduard;

Successfully run `yolo-v2-tiny-vehicle-detection-0001` with `object_detection_demo_yolov3_async` but seems no recognization in this demo;

For us, currently we want to use `yolo-v2-tiny-vehicle-detection-0001`  for detection and `vehicle-attributes-recognition-barrier-0042` for recognization in our scene;

We got the sample code of  `yolo-v2-tiny-vehicle-detection-0001`  for detection in Python and `vehicle-attributes-recognition-barrier-0042` for recognization in C++ now, and try to combine it now :)

Thanks again;
