### ISSUE TITLE
how to try Bfloat16 in a simple test

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/open_model_zoo#1515]
Hi, 

I see that Bfloat16 is supported/optimized on Cooper Lake according to release notes, is there a simple test (.c or .cpp program) with one float32/Bfloat16 model that I can have a try? thanks.

**Comment by eaidova** [comment]
@guoyejun  conversion to bfloat16 will be performed automatically if platform support it, for testing I can suggest you to use benchmark_app. It has key for enable/disable bf16:
```
    -enforcebf16              Optional. Enforcing of floating point operations execution in bfloat16 precision on platforms with native bfloat16 support. By default, this key sets "true" on platforms with native bfloat16 support and "false" for other platforms. Use "-enforcebf16=false" to disable this feature.
```
see: [benchmark_app docs](https://docs.openvinotoolkit.org/latest/openvino_inference_engine_samples_benchmark_app_README.html)

**Comment by guoyejun** [comment]
thanks, got it, we don't need another bfloat16 model file, it is executed internally with bfloat16 precision on supported platforms on FP32 model file.

**Comment by eaidova** [comment]
yes, alright, you can switch -enforcebf16=false to return back to fp32 and compare performance between bf16 and fp32.
You can find more details about bf16 support in openvino on this [page](https://docs.openvinotoolkit.org/latest/openvino_docs_IE_DG_Bfloat16Inference.html)

**Comment by guoyejun** [comment]
thank you very much!
