### ISSUE TITLE
Modified tiny_yolo_v3.cfg to Tensorflow (to OpenVINO)

### ISSUE THREAD

**Issue by GotG** [openvinotoolkit/open_model_zoo#1547]
Hello

Does anyone have experience with converting modified yolov3 cfg to Tensorflow 1.x and then to OpenVINO?
I am using a modified tiny_yolo_v3.cfg where i decreased the number of filters.
The model trains and detects well in Darknet.
I modified the tiny-yolov3 model from mystic123 https://github.com/mystic123/tensorflow-yolo-v3 repo to match my cfg.
The conversion to TF works but the model detects less objects than in darknet (and the boxes are of wrong size). The converted model (.xml and .bin ) to OpenVINO yields no detections in the python demo for yolov3 and variants.
Thanks!

Files:
https://drive.google.com/file/d/1PnsxwNKIMugR2zvi24lx3uQX51wr1GN2/view?usp=sharing

**Comment by mowkee** [comment]
mystic123's code is buggy and it doesn't work and the project is abandoned.

**Comment by vladimir-dudnik** [comment]
OMZ contain [yolo-v3-tiny-tf model](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/yolo-v3-tiny-tf/yolo-v3-tiny-tf.md), can it serve as an example for you?

**Comment by vladimir-dudnik** [comment]
@GotG do you have additional questions?

**Comment by vladimir-dudnik** [comment]
I'll close this, feel free to reopen if you have additional questions
