### ISSUE TITLE
How can I convert the onnx language model (XLM_Roberta_Large) to openvino?

### ISSUE THREAD

**Issue by laifuchicago** [openvinotoolkit/open_model_zoo#1550]
To Author:
I first convert the pytorch model to onnx. Then I try to convert from onnx to OpenVINO. But this is the problem that I got.(In the figure) I think the problem happened in the input_shape. I know the xlm-roberta does not have "token_type_ids". So how can I set the input_shape? Or Openvino does not support xlm-roberta?
![openvino_prob1](https://user-images.githubusercontent.com/8537280/93190665-35db7d80-f776-11ea-918d-b4429be78448.PNG)

Thank you for your help.
Jonathan Sung

**Comment by eaidova** [comment]
Hi @laifuchicago,, your model has multiple inputs, so you need to specify input for all of them (input_ids, attention_masks) using comma and provide --input parameter with specifing names of input in the corresponding order. MO error says about it.
for example:
mo.py --input_model <model>.onnx --input_shape [1024,16],[1024,16] --input input_ids,attention_mask ....

**Comment by laifuchicago** [comment]
To Author:
Thank you, it can be converted now. But now when I want to demo , I found some error, because xlm-roberta does not have vocab.txt. They use sentence,bpe.model instead.  The following figures are what I set and the result that I got. Thank you.
![openvino_prob2](https://user-images.githubusercontent.com/8537280/93300488-734d1300-f829-11ea-9784-0986c50b8022.PNG)
![openvino_prob3](https://user-images.githubusercontent.com/8537280/93300489-73e5a980-f829-11ea-9fbb-04131aa256ac.PNG)

Jonathan Sung

**Comment by eaidova** [comment]
> To Author:
> Thank you, it can be converted now. But now when I want to demo , I found some error, because xlm-roberta does not have vocab.txt. They use sentence,bpe.model instead. The following figures are what I set and the result that I got. Thank you.
> ![openvino_prob2](https://user-images.githubusercontent.com/8537280/93300488-734d1300-f829-11ea-9784-0986c50b8022.PNG)
> ![openvino_prob3](https://user-images.githubusercontent.com/8537280/93300489-73e5a980-f829-11ea-9fbb-04131aa256ac.PNG)
> 
> Jonathan Sung

@laifuchicago  as expected, vocab.txt and sentencepiece model is not hte same thing, it is the reason why our bert demo is not suitable for your model. You can modify the code to work with sentencepiece instead of decoding by vocab. Also potential problem in preprocessing for input,  it has difference for xlm and bert if I right remember, you can see it in [huggingface question answering example](https://github.com/huggingface/transformers/blob/master/examples/question-answering/run_squad.py#L297-L316)
