### ISSUE TITLE
Which labels should be used with resnet-50?

### ISSUE THREAD

**Issue by dvrogozh** [openvinotoolkit/open_model_zoo#1560]
Considering https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/resnet-50 model: which labels should be used?

The https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/classification_demo demo gives 2 lists:
* https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/classification_demo/imagenet_2012_classes.txt
* https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/classification_demo/imagenet_2015_classes.txt

And a note that 2015 labels should be used with certain models (googlenet-v2, se-inception, se-resnet-101,se-resnet-152, se-resnet-50, se-resnext-101, se-resnext-50) all other models supported by the demo should use 2012 labels. The problem is that resnet-50 model referenced above is absent in the list of models supported by the demo: https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/classification_demo/models.lst.

**Comment by eizamaliev** [comment]
This model will be removed from OMZ in next release. But for the record it uses https://github.com/openvinotoolkit/open_model_zoo/blob/develop/demos/classification_demo/imagenet_2012_classes.txt .

**Comment by zeeintel** [comment]
Reset-50 model is not downloadable.
 other models (e.g. resnet-50-tf) can be downloaded. 

Here is the  downloader.py's log.

################|| Downloading models ||################

========== Downloading ~/models/public/resnet-50/resnet-50.prototxt
... 22%, 6 KB, 15067 KB/s, 0 seconds passed
########## Error: Downloaded file is shorter (7161 B) than expected (32500 B)

################|| Post-processing ||################

FAILED:
resnet-50

**Comment by vladimir-dudnik** [comment]
@zeeintel model resnet-50 from caffe is not available anymore from its original location, that is why downloader can't download it. Model will be removed from Open Model Zoo in the next OpenVINO release.

**Comment by vladimir-dudnik** [comment]
closing as resolved (resnet-50 Caffe removed from OMZ)
