### ISSUE TITLE
Which labels should be used with ssd_mobilenet_v2_coco?

### ISSUE THREAD

**Issue by dvrogozh** [openvinotoolkit/open_model_zoo#1561]
Considering https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/ssd_mobilenet_v2_coco, model: which labels should be used?

Looking into nice summary https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/, story looks to be:
1. Original paper considered 91 object categories
2. https://cocodataset.org/ had 2 releases in 2014 and 2017 both times exposing 80 object categories
3. Open ZOO model link mentions that "the model was trained on Microsoft* COCO dataset version with 90 categories of object"

Can you, please, provide ID->label map which should be used with the open zoo model? Does it correspond to original paper?

**Comment by eizamaliev** [comment]
As original paper says, you should use labels for 90 classes. Unfortunately, we haven't this label file yet, but you can view them [here](https://github.com/tensorflow/models/blob/master/research/object_detection/data/mscoco_label_map.pbtxt). In the future it will be added to OMZ.

**Comment by dvrogozh** [comment]
Thank you for clarification.

**Comment by vladimir-dudnik** [comment]
closing as resolved
