### ISSUE TITLE
Failed to reshape Network

### ISSUE THREAD

**Issue by ClementLeBihan** [openvinotoolkit/open_model_zoo#1575]
Hi guys,

I've compiled openvino by myself, downloaded open_model_zoo models using downloader script, and build demos using build_demos script.

Some demos are working perfectly on my Intel Neurel Compute Stick 2, but for some other demos, I have this error : 

```
/root/omz_demos_build/intel64/Release/pedestrian_tracker_demo \
    -m_det /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml \
    -m_reid /opt/intel/openvino/deployment_tools/open_model_zoo/tools/downloader/intel/person-reidentification-retail-0270/FP16/person-reidentification-retail-0270.xml \
    -d_det MYRIAD -d_reid MYRIAD \
    -i ~/video_test.mp4

InferenceEngine: 0x7f5b5c00e020
Loading device MYRIAD
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... custom_master_83e96891ca287bede3d0d481d6e5b3facabed346

[ ERROR ] Failed to reshape Network: You have called setBatchSize + reshape for CNNNetwork object. Please, either: 
- [SUGGESTED] Regenerate IR with current version of Model Optimizer
- [WORKAROUND] Call only reshape method where proper batch is already set
```

These error also appear for interactive face detection demo.

Is there a solution for this issue ? 

Thank you by advance,
Clément

**Comment by Wovchena** [comment]
Hi, @ClementLeBihan.
Can you check if it works on CPU for you?

**Comment by ClementLeBihan** [comment]
Hi @Wovchena,

Indeed, I forgot to say that it works good on CPU !

Clément

**Comment by Wovchena** [comment]
I've submitted a ticket to a myriad plugin team

**Comment by Wovchena** [comment]
A reply I got:
> https://github.com/openvinotoolkit/openvino/pull/1918

**Comment by vladimir-dudnik** [comment]
@ClementLeBihan have you a chance to verify OpenVINO fix?

**Comment by Wovchena** [comment]
The issue seems to be inactive and https://github.com/openvinotoolkit/openvino/pull/1918 successor is merged. Closing.
