### ISSUE TITLE
Specifying max_queue_length does not work correctly in FramesThreadBody

### ISSUE THREAD

**Issue by nixingyang** [openvinotoolkit/open_model_zoo#1578]
In [FramesThreadBody](https://github.com/openvinotoolkit/open_model_zoo/blob/2020.4/demos/python_demos/multi_camera_multi_target_tracking/multi_camera_multi_target_tracking.py#L80), the `max_queue_length` variable is used to limit the size of `self.frames_queue`. However, a "continue" statement is missing after [here](https://github.com/openvinotoolkit/open_model_zoo/blob/2020.4/demos/python_demos/multi_camera_multi_target_tracking/multi_camera_multi_target_tracking.py#L90). In the current implementation, the size of `self.frames_queue` can be larger than `max_queue_length`. It results in the out of memory issue, especially on resource-limited devices, i.e., `self.frames_queue` keeps adding new frames to it.

**Comment by vladimir-dudnik** [comment]
@DmitriySidnev could you please take a look on this report?

**Comment by DmitriySidnev** [comment]
@nixingyang, hi!
How did you face this problem: during execution the script or after interruption?

**Comment by nixingyang** [comment]
Hi @DmitriySidnev, this problem would occur during the execution of the program. To replicate it, you may print `self.frames_queue.qsize()` and add `time.sleep(60)` after [here](https://github.com/openvinotoolkit/open_model_zoo/blob/2020.4/demos/python_demos/multi_camera_multi_target_tracking/multi_camera_multi_target_tracking.py#L175). You will find that `self.frames_queue.qsize()` is continuously increasing.

**Comment by DmitriySidnev** [comment]
@nixingyang, yes you are right. Could you please make a fix with your suggestion?

**Comment by nixingyang** [comment]
@DmitriySidnev Great. I have created a pull request https://github.com/openvinotoolkit/open_model_zoo/pull/1621 to fix this issue.
