### ISSUE TITLE
how to speed up human-pose-estimation demo

### ISSUE THREAD

**Issue by AprilCat** [openvinotoolkit/open_model_zoo#1589]
I run this demo on MYRIAD. sync mode. it cost 410ms during inference. What can I do to speed up this demo.

**Comment by vladimir-dudnik** [comment]
@AprilCat might to try async mode?

**Comment by Daniil-Osokin** [comment]
Hi! You may also try to decrease network input size, e.g. twice: from 256x456 to 128x228. It will require network [reshape](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/human_pose_estimation_demo/src/human_pose_estimator.cpp#L113).

**Comment by vladimir-dudnik** [comment]
@AprilCat do you have an additional questions?
