### ISSUE TITLE
The problem with the downloading of the models ResNet.

### ISSUE THREAD

**Issue by Vladislav-Denisov** [openvinotoolkit/open_model_zoo#1591]
Hi. There is a problem with downloading prototxt files for the ResNet-50, ResNet-101, and Resnet-152 models.
Error: Downloaded file is shorter (<size>) than expected (<size>).

**Comment by eizamaliev** [comment]
These models are not available in original source and would be deleted in 2021.1. See [here](https://github.com/openvinotoolkit/open_model_zoo/issues/1475) for details.

**Comment by vladimir-dudnik** [comment]
@Vladislav-Denisov OpenVINO 2021.1 was just released, not available models were removed from it. I'm going to close the issue. Do you have an additional questions on it?

**Comment by Vladislav-Denisov** [comment]
> @Vladislav-Denisov OpenVINO 2021.1 was just released, not available models were removed from it. I'm going to close the issue. Do you have an additional questions on it?

Thanks for your reply. There are no more questions about these models. Issue can be closed.
