### ISSUE TITLE
Meet the following error when load weights in demo object_detection_sample_ssd

### ISSUE THREAD

**Issue by yangqbo** [openvinotoolkit/open_model_zoo#1602]
I tried to execute the command: ./object_detection_sample_ssd -i person.jpg -m person-detection-retail-0013.xml -d MYRIAD, then met the following error:
 
[ ERROR ] Check 'is_valid_permutation(permutation, arg_shape.rank())' failed at ngraph/core/src/op/transpose.cpp:73:
While validating node 'v1::Transpose Transpose_1902 (mbox_loc1/out/conv[0]:f16{1,48,20,34}, mbox_loc1/out/conv/perm/Cast_138728_const[0]:i64{4}) -> (dynamic?)' with friendly_name 'Transpose_1902':
Permutation AxisVector{512, 768, 256, 0} is not valid for input shape {1,48,20,34}

**Comment by yangqbo** [comment]
And the command "python object_detection_demo_yolov3_async.py -i car.png -m yolov3.xml -d MYRIAD" leads to the following error:
[ INFO ] Loading network
Traceback (most recent call last):
  File "object_detection_demo_yolov3_async.py", line 518, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_yolov3_async.py", line 320, in main
    net = ie.read_network(args.model, os.path.splitext(args.model)[0] + ".bin")
  File "ie_api.pyx", line 262, in openvino.inference_engine.ie_api.IECore.read_network
  File "ie_api.pyx", line 290, in openvino.inference_engine.ie_api.IECore.read_network
RuntimeError: Check 'PartialShape::merge_into(inputs_shape_scheme, this_input_shape)' failed at ngraph/core/src/op/concat.cpp:92:
While validating node 'v0::Concat Concat_1033 (up_sampling2d/resize/ResizeNearestNeighbor[0]:f32{1,256,6122752255950179772,0}, add_18/add[0]:f32{1,512,26,26}) -> (dynamic?)' with friendly_name 'Concat_1033':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 1).

**Comment by vladimir-dudnik** [comment]
Please make sure you use models and OpenVINO runtime from the same release.

**Comment by yangqbo** [comment]
> 
> 
> Please make sure you use models and OpenVINO runtime from the same release.

I use the OpenVINO 2020.4 and models downloaded from the open_model_zoo, and they shoud be the same release.

**Comment by eizamaliev** [comment]
@yangqbo did you use `downloader.py` and `converter.py` scripts to obtain the model?

**Comment by yangqbo** [comment]
Yes, I got the person-detection-retail-0013.xml and person-detection-retail-0013.bin files by downloader.py directly. and tried to load them into openvino, then I meet the error. 
And when tried to run the example: ./classification_sample_async -i car.jpg -m squeezenet1.1.xml  -d MYRIAD, the following error appeared:

[ INFO ] InferenceEngine: 
	API version ............ 2.1
	Build .................. custom_master_863a7bd6633763368f16679e37f4f73f54e3c650
	Description ....... API
[ INFO ] Parsing input parameters
[ INFO ] Parsing input parameters
[ INFO ] Files were added: 1
[ INFO ]     car.jpg
[ INFO ] Creating Inference Engine
	MYRIAD
	myriadPlugin version ......... 2.1
	Build ........... custom_master_863a7bd6633763368f16679e37f4f73f54e3c650

[ INFO ] Loading network files
[ ERROR ] segment size(2471004) exceeds given buffer limits(2469637). Please, validate weights file


> 
> 
> @yangqbo did you use `downloader.py` and `converter.py` scripts to obtain the model?

**Comment by eizamaliev** [comment]
Did you try it on CPU or GPU?

**Comment by yangqbo** [comment]
> 
> 
> Did you try it on CPU or GPU?
Yes, it is right on CPU or GPU, but I need run programs on VPN.

**Comment by vladimir-dudnik** [comment]
@yangqbo person-detection-retail-0013 validated to work on CPU, GPU and MyriadX stick with OpenVINO 2020.4 release. Please make sure you use OMZ downloader from your OpenVINO install package and not from github. If you use OMZ from github, make sure you checkout master branch and not develop branch. The master branch of OMZ on github always correspond to the latest public OpenVINO release, while develop branch may differ and so may download models prepared on pre-released versions of OpenVINO runtime and such models might be not compatible with previous versions of OpenVINO runtime.

**Comment by Wovchena** [comment]
I can't reproduce the problem. I did the following on Ubuntu18:
```sh
cd /mnt/h/i/openvino/inference_engine/samples/cpp/
. /mnt/h/i/openvino/bin/setupvars.sh
./build_samples.sh
cd ../../../deployment_tools/open_model_zoo/tools/downloader/
python3.6 downloader.py --name  person-detection-retail-0013 -o /mnt/h/d/downloader/ --cache_dir /mnt/h/d/downloader/
~/inference_engine_cpp_samples_build/intel64/Release/object_detection_sample_ssd -i /mnt/h/p/1.png -m /mnt/h/d/downloader/intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml -d MYRIAD
```
with `openvino` as a link: openvino -> /mnt/h/i/openvino_2020.4.287/

**Comment by yangqbo** [comment]
Thank you very much for your kind help! I transferred files by an FTP server, I think that maybe the arch-criminal led to the error.  And I transferred files with MobaXterm and downloaded *.xml and *.bin files later then the demos run rightly.
