### ISSUE TITLE
Labels vgg19, googlenet-v2.

### ISSUE THREAD

**Issue by Vladislav-Denisov** [openvinotoolkit/open_model_zoo#1607]
Hi! I want to validate the googlenet-v2 and vgg19 models. However, I can't find the correct labels. Please share a link to the files with them.

**Comment by vladimir-dudnik** [comment]
these public models are trained on [ImageNet](http://image-net.org) dataset. We do not redistribute ImageNet dataset or its parts, you need to get it on your own. There is a brief [description](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/datasets.md#dataset-preparation-guide), of how to get ImageNet dataset. Look for obtaining caffe_ilsvrc12.tar.gz archive which should contain class to name mapping for ImageNet.

**Comment by vladimir-dudnik** [comment]
@Vladislav-Denisov I'm going to close the issue. Do you have an additional questions on this?
