### ISSUE TITLE
Submitting a model without a dataset

### ISSUE THREAD

**Issue by snakers4** [openvinotoolkit/open_model_zoo#1622]
Hi!

We would like to contribute our [models](https://github.com/snakers4/silero-models).

> PR Rejection
> Your PR may be rejected in some cases, for example:
> If a dataset is inaccessible.

For a number of legal reasons we are not planning to share our datasets and / or re-upload publicly available datasets (i.e. LibriSpeech derivatives).

Does this make contributing a model to your model zoo improssible?

**Comment by vladimir-dudnik** [comment]
@snakers4 please review [CONTRIBUTING.md](https://github.com/openvinotoolkit/open_model_zoo/blob/master/CONTRIBUTING.md) for terms we require to accept contribution.
Contribution not required to re-upload publicly available dataset, we ask to specify which dataset your contribution depends on and what is the dataset license.

**Comment by snakers4** [comment]
@vladimir-dudnik 

>  we ask to specify which dataset your contribution depends on and what is the dataset license.

And if the dataset in question is private? 
Does it imply that the contribution will be automatically rejected?

**Comment by vladimir-dudnik** [comment]
@yssemaev could you please review question from legal point of view?

**Comment by yssemaev** [comment]
Hi, we accept contribution according to CONTRIBUTING.md "under permissive licenses, such as MIT, Apache 2.0, and BSD-3-Clause" only. As a rule, in github repo it's mentioned which dataset was used for training and validation (public or internal). Only contribution of a model is accepted, not a dataset. OMZ's Apache 2.0 license allows various use of models including commercial or academic.

**Comment by snakers4** [comment]
> under permissive licenses, such as MIT, Apache 2.0, and BSD-3-Clause
Is GPL considered to be a permissive license?

**Comment by yssemaev** [comment]
No, L/GPL implies additional restrictions like "same license", etc.

**Comment by snakers4** [comment]
I see.
Many thanks.
