### ISSUE TITLE
bash: ./gaze_estimation_demo: No such file or directory

### ISSUE THREAD

**Issue by TranThanh96** [openvinotoolkit/open_model_zoo#1630]
I am running the gaze_estimation_demo on ubuntu 18. And an issue occurred: 
`bash: ./gaze_estimation_demo: No such file or directory` . 
can you tell me how to fix this?

**Comment by eizamaliev** [comment]
Did you build it using `build_demos.sh` script? Does it exist in your directory?

**Comment by vladimir-dudnik** [comment]
@TranThanh96 you are launching application from current folder. Does it contain executable file? Hope you were able to review [Build the Demo Applications](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#build-the-demo-applications) and [Get Ready for Running the Demo Applications on Linux](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#get-ready-for-running-the-demo-applications-on-linux) sections of [README.md](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/README.md) in demo folder.

**Comment by TranThanh96** [comment]
It was my fault! I did not follow carefully the instruction. Close topic!
