### ISSUE TITLE
code + data training gaze_estimation

### ISSUE THREAD

**Issue by TranThanh96** [openvinotoolkit/open_model_zoo#1634]
as a title, can you public that?

**Comment by eizamaliev** [comment]
@snosov1 could you help?

**Comment by snosov1** [comment]
Sorry, that's one of the older Caffe models that we don't intend to publish in the original format.

**Comment by TranThanh96** [comment]
> Sorry, that's one of the older Caffe models that we don't intend to publish in the original format.

how about data?

**Comment by snosov1** [comment]
(With very rare expections) we never publish training data. There's about 167 good and bad reasons for that.

**Comment by TranThanh96** [comment]
anyway, thank you for your efforts
