### ISSUE TITLE
Config file .YML miss "global_definitions: ../dataset_definitions.yml" on OpenVINO2021.1 

### ISSUE THREAD

**Issue by biyuehuang** [openvinotoolkit/open_model_zoo#1666]
Hi, I found tool POST's configs .yml miss "global_definitions: ../dataset_definitions.yml" on OpenVINO2021.1 
for example,  /opt/intel/openvino_2021.1.110/deployment_tools/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml
or https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/deeplabv3/accuracy-check.yml 
miss "global_definitions: ../dataset_definitions.yml". 

Without "global_definitions: ../dataset_definitions.yml", I excute 
$ pot -c /opt/intel/openvino_2021/deployment_tools/tools/post_training_optimization_toolkit/configs/examples/deeplabv3.json -e
 error will exist:
  File "/opt/intel/openvino_2021.1.110/deployment_tools/tools/post_training_optimization_toolkit/libs/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py", line 111, in configure
    'data reader and read data'.format(self.__provider__))
libs.open_model_zoo.tools.accuracy_checker.accuracy_checker.config.config_validator.ConfigError: data_source parameter is required to create "opencv_imread" data reader and read data

However, I add "global_definitions: ../dataset_definitions.yml" to /opt/intel/openvino_2021.1.110/deployment_tools/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml, then solve problem. Thanks.

**Comment by eizamaliev** [comment]
@biyuehuang you can use `-d <path/to/dataset_definitions.yml>` option in Accuracy Checker command line.

**Comment by eaidova** [comment]
Hi @biyuehuang,  please note that suggested by @eizamaliev solution works only for Accuracy Checker by itself.
 if you want use definitions file in quantization via Post Training Optimization Toolkit (POT), you should use environment variable DEFINITIONS_FILE for specifying path to definitions.

you can find more details about predefined configs usage in this [post](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/tools/accuracy_checker/configs/README.md)

**Comment by biyuehuang** [comment]
Thanks @eaidova and @eizamaliev
