### ISSUE TITLE
Request Face Person model on Openvino 2021.1

### ISSUE THREAD

**Issue by campos537** [openvinotoolkit/open_model_zoo#1676]
Greetings!
I would like to ask about the Face + Person model, you guys had added this model on really older versions of Openvino, but since the new version 2021.1 removes the support for older models, is there any possibility you guys add the Face + Person model converted with the new Openvino? Or at least add the original model so we can convert?

Link for reference: https://docs.openvinotoolkit.org/2018_R5/_docs_Retail_object_detection_face_pedestrian_rmnet_ssssd_2heads_0002_caffe_desc_face_person_detection_retail_0002.html

**Comment by eizamaliev** [comment]
@snosov1 could you help?

**Comment by shirish100** [comment]
Using old models with a newer version throws up some support error. And I have found no detection being detected using the new models. Is it the same with you @campos537 ?

**Comment by snosov1** [comment]
1. I don't have the measurements at hand, but I suggest to try running 2 networks (for faces and people separately). I believe, performance-wise, it should be comparable (and provides more flexibility)
2. Actually, I don't know why the model disappeared. @vladimir-dudnik have you, guys, removed it for some reason?

**Comment by vladimir-dudnik** [comment]
@shirish100 @campos537 have you noticed [Backward Incompatible Changes Compared with 2020.4](https://software.intel.com/content/www/us/en/develop/articles/openvino-relnotes.html) section in OpenVINO 2021 release notes? In 2021.1 release decision was made to introduce backward incompatible changed in IR format, which allow support new models features. So, old models have to be rebuild with OpenVINO 2021.1 MO. Unfortunately it is not possible for deprecated Intel pre-trained models (those which were available in IR form only).

**Comment by vladimir-dudnik** [comment]
@snosov1 model face-person-detection-retail-0002 was deprecated in OpenVINO 2019R2 time frame.

**Comment by campos537** [comment]
> Using old models with a newer version throws up some support error. And I have found no detection being detected using the new models. Is it the same with you @campos537 ?

In my case i only had issues with previous versions of intel models. Which they didn't work, because of what the guys explained.


>     1. I don't have the measurements at hand, but I suggest to try running 2 networks (for faces and people separately). I believe, performance-wise, it should be comparable (and provides more flexibility)
> 
>     2. Actually, I don't know why the model disappeared. @vladimir-dudnik have you, guys, removed it for some reason?

I shouldn't got problems by using the separated models, would be just easier and no need to change the current code by using the old ones.

**Comment by snosov1** [comment]
> I shouldn't got problems by using the separated models, would be just easier and no need to change the current code by using the old ones.

I see you, but the thing is - the face-person model was a bit "architecturally unusual", in a sense, that it had 2 detection outputs (instead of having a 2 labels in a single detection output). So, if we are to revive it - we'll need to change/adjust the demo code on our side. To quote Louie from the Ghost Dog movie "Better you than me" =)
