### ISSUE TITLE
Input preprocessing 

### ISSUE THREAD

**Issue by edward9112** [openvinotoolkit/open_model_zoo#1706]
Hello,

Do I need to perform any input preprocessing for those models? 
In particular, person-vehicle-bike-detection-2000 and person-detection-0200

Do images have to be exactly 256x256 for best result?

Thank you

**Comment by eaidova** [comment]
@edward9112  simple resize with bilinear interpolation to 256x256 using opencv will be enough. Models return boxes coordinates in normalized format, in [0, 1] range, so for getting result in original image scale, you need to rescale them (multiply x and y coordinates on image width and height correspondingly).

More details about expected input and output format you can find in models description:
* [person-vehicle-bike-detection-2000](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-vehicle-bike-detection-2000/description/person-vehicle-bike-detection-2000.md)
* [person-detection-0200](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-detection-0200/description/person-detection-0200.md)

**Comment by edward9112** [comment]
Alright, thank you!
