### ISSUE TITLE
is there a model for tracking

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/open_model_zoo#1732]
I just tried to look for a tracking model in the open model zoo but did not find one.  Is there a model such as SIAM for single object track? thanks.

**Comment by vladimir-dudnik** [comment]
@guoyejun we do not have SIAM object tracking model in Open Model Zoo yet. If you are interested you may try to contribute one (see [CONTRIBUTING.md](https://github.com/openvinotoolkit/open_model_zoo/blob/develop/CONTRIBUTING.md) for the requirements). Although, there is a OpenCV DNN [sample](https://github.com/opencv/opencv/pull/17647) which demonstrate how such models work.

**Comment by vladimir-dudnik** [comment]
@guoyejun do you have additional questions?

**Comment by guoyejun** [comment]
thanks
