### ISSUE TITLE
How can I download the pre-trained models manually?

### ISSUE THREAD

**Issue by cezane** [openvinotoolkit/open_model_zoo#1741]
I copied the downloader.py code and installed the prerequisites (pyyaml and requests), but when I tried to run, I got the following error:

```
./downloader.py 
Traceback (most recent call last):
  File "./downloader.py", line 357, in <module>
    main()
  File "./downloader.py", line 322, in main
    reporter = make_reporter(common.DirectOutputContext())
AttributeError: module 'common' has no attribute 'DirectOutputContext'
```
How to manually download the models to follow the instructions in the tutorial?

**Comment by cezane** [comment]
I noticed that the `common` needed for the code is the `common.py` file. Then I created it and got success running the `downloader.py`. But when I followed the instructions to download the `squeezenet1.1` model, I got the following message:

```
./downloader.py --name squeezenet1.1 --output_dir ~/public_models
No matching models: "squeezenet1.1"
```

**Comment by eaidova** [comment]
hi @cezane 
I believe for usage model downloader copy only single script is not enough. This script works with specific file structure which describe where model should be found and how idownloaded files should be postprocessed if need (e,g, unzip archive) and how it should be converted to OpenVINO representation.
Please clone repo and use downloader from it.

**Comment by cezane** [comment]
So, if I have to clone all the repository, it seems the script does not really download the models. It just gets the model from the `models/public` folder, which contains all the models, and, for this reason, I dont want to clone everything. This way, I would like to know how to manually download the models, as mentioned in the tutorial: "You can find and download this model manually or use the OpenVINO™ Model Downloader".

**Comment by eaidova** [comment]
@cezane no, this repo does not contains models at all :) You can see it if you open [squeezenet1.1](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/squeezenet1.1) directory, here no files related with model architecture and weights, only configs in yaml format. So this script really download models from different sources.

**Comment by eaidova** [comment]
Manaul downloading a model literally means that you need to find the model and download its files by hands (from various repositories, websites, shared drives and so on, depends from model).

**Comment by cezane** [comment]
Thank you @eaidova . I cloned all the repository and got success in downloading the desired model.
