### ISSUE TITLE
Willing to contribute several new image classification models

### ISSUE THREAD

**Issue by spectrico** [openvinotoolkit/open_model_zoo#1747]
I want to contribute several Tensorflow models to Open Model Zoo. All the models are released under MIT license.
I read the contributing guidelines and the Pull Request Requirements but it is difficult for me to understand them.
I would appreciate it if someone with OpenVINO knowledge could prepare the necessary files and make pull requests.
The models are:

- Age and Gender Recognition: [https://github.com/spectrico/age-gender-recognition-64x64-python](https://github.com/spectrico/age-gender-recognition-64x64-python)

- Race Recognition: [https://github.com/spectrico/race-recognition-python](https://github.com/spectrico/race-recognition-python)

- Car Color Recognition: [https://github.com/spectrico/car-color-classifier-yolo4-python](https://github.com/spectrico/car-color-classifier-yolo4-python)

- Car Make and Model classification: [https://github.com/spectrico/car-make-model-classifier-yolo3-python](https://github.com/spectrico/car-make-model-classifier-yolo3-python)

- Vehicle Brand Recognition: [https://github.com/spectrico/vehicle-brand-recognition-yolov4-python](https://github.com/spectrico/vehicle-brand-recognition-yolov4-python)

**Comment by eizamaliev** [comment]
Hi @spectrico,
have you tried convert your models with Model Optimizer? Or may be to run it with OpenVINO?

**Comment by spectrico** [comment]
Hi @eizamaliev,

I am able to convert the models with Models Optimizer successfully. And they run with OpenVINO inference engine.
I am attaching a sample model, which was converted using:
> python ./model_optimizer/mo.py --input_model model-weights-spectrico-car-recognition-mobilenet_v3-224x224-170620.pb --input_shape [1,224,224,3] --data_type FP16 --scale 127.50223128904757 --mean_values [127.5,127.5,127.5] --reverse_input_channels --model_name model-weights-spectrico-car-recognition-mobilenet_v3-224x224-170620

The prediction is called using the following command line parameters:
> python classification_sample.py -i car.jpg -m model-weights-spectrico-car-recognition-mobilenet_v3-224x224-170620.xml --labels labels.txt -nt 5 -d CPU

Model for car brand recognition:
[car-brand-recognition.zip](https://github.com/openvinotoolkit/open_model_zoo/files/5508941/car-brand-recognition.zip)

The problem is that I have no idea how to comply with the Pull Request Requirements in https://github.com/openvinotoolkit/open_model_zoo/blob/master/CONTRIBUTING.md
There is a requirement for configuration file model.yml, which I have no idea how to create.
Other requirements that are difficult for me are the following:

> Your PR must pass next tests:
> Model is downloadable by the tools/downloader/downloader.py script. See Configuration file for details.
> Model is convertible by the tools/downloader/converter.py script. See Model conversion for details.
> Model is usable by demo or sample and provides adequate results. See Demo for details.
> Model passes accuracy validation. See Accuracy validation for details.

I am not familiar with OpenVINO source code and don't know how to modify that scripts.

**Comment by vladimir-dudnik** [comment]
@spectrico do you have additional questions?
