### ISSUE TITLE
Smart Classroom Demo issue

### ISSUE THREAD

**Issue by allenwsh82** [openvinotoolkit/open_model_zoo#1821]
Hello Experts,

Anyone encounter this issue before when I tried to run the smartclass room demo ?

[ INFO ] InferenceEngine: 00007FFFFD6E4390
[ INFO ] Parsing input parameters
[ INFO ] Reading video 'classroom.mp4'
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.4.0-359-21e092122f4-releases/2020/4

[ ERROR ] Check 'shape_size(get_input_shape(0)) == shape_size(output_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-icc2018\b\repos\openvino\ngraph\src\ngraph\op\reshape.cpp:290:
While validating node 'v1::Reshape Reshape_187891(Softmax_187890[0]:f32{3249,8}, Constant_187705[0]:i64{3}) -> (f32{1,3249,2})':
Requested output shape Shape{1, 3249, 2} is incompatible with input shape Shape{3249, 8}

**Comment by vladimir-dudnik** [comment]
@allenwsh82 it seems model IR not corresponds to OpenVINO runtime. If you use OpenVINO 2020.4 runtime then you should not use model from 2021.1 release.

**Comment by allenwsh82** [comment]
Hi Vladimir-Dudnik,

I am using IR file for OpenVINO 2020 release and some how I didn't see the error messages already but nothing happen, i guess it is not playing the .mp4 file, no pop out of the video windows, seems weird.... 

C:\Users\allensen\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release>smart_classroom_demo.exe -i classroom.mp4 -m_act person-detection-action-recognition-0006.xml -m_fd face-detection-retail-0004.xml -m_lm landmarks-regression-retail-0009.xml -m_reid face-reidentification-retail-0095.xml -fg faces_gallery.json
[ INFO ] InferenceEngine: 00007FFFFE094390
[ INFO ] Parsing input parameters
[ INFO ] Reading video 'classroom.mp4'
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 2020.4.0-359-21e092122f4-releases/2020/4


C:\Users\allensen\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release>

**Comment by vladimir-dudnik** [comment]
strange how it happens that ngraph related issue comes out without any changes.
If you can't playback video file on windows it might be related to absence of required media codecs. You may need to download ffmpeg DLLs for opencv, see this [thread](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/inference-engine-samples-do-not-take-image-or-video-files-as/m-p/1134761#M9384) on OpenVINO forum

**Comment by allenwsh82** [comment]
Hello Vladimir-Dudnik,

Thanks for the recommendation and I had downloaded ffmpeg DLL for OpenCV previously.
One thing I notice, when I use the same classroom.mp4 video with another Interactive_Face_Detetion example, it is working perfectly.

So I am wondering if this is related to smart_classroom_demo.exe only? 

![Uploading Interactive_Face_Detection_Video.PNG…]()

**Comment by allenwsh82** [comment]
Hello Vladimir-Dudnik,

Same results even I tried on diff machine in OpenVINO 2021, any thoughts, no issue running other demos.

Thanks

**Comment by vladimir-dudnik** [comment]
@allenwsh82 
I do not have issue to run smart class room demo with OpenVINO 2021.2, which was just released, using parameters below:
smart_classroom_demo.exe -i classroom.mp4 -m_act person-detection-action-recognition-0005.xml -m_fd face-detection-retail-0004.xml -m_lm landmarks-regression-retail-0009.xml -m_reid face-recognition-mobilefacenet-arcface.xml

![smart_classroom_screenshot](https://user-images.githubusercontent.com/9465398/102491385-2889a400-4081-11eb-85bb-5704c68aa876.jpg)

But, when I change action recognition model to person-detection-action-recognition-0006.xml demo reports error:
[ ERROR ] The number of specified actions and the number of actions predicted by the Person/Action Detection Retail model must match

This model recognize 6 actions vs 4 recognized by person-detection-action-recognition-0005, so you need to specify additional option to demo: -student_ac "sitting,writing,raising hand,standing,turned around,lie on the desk" to make it work.

**Comment by vladimir-dudnik** [comment]
@allenwsh82 do you have additional questions?

**Comment by allenwsh82** [comment]
Hello Vladimir, 

No more questions from my side.

Thanks for the help and advise

**Comment by vladimir-dudnik** [comment]
thanks, so I'll close this
