### ISSUE TITLE
How to generate an executable sample

### ISSUE THREAD

**Issue by dxxhjk** [openvinotoolkit/open_model_zoo#1840]
hi!
While i was generating executable file in `open_model_zoo/demos/object_detection_demo_yolov3_async/` with cmake under the build folder, an error occurred. It said 
```
  CMake Error at CMakeLists.txt:5 (ie_add_sample):
  Unknown CMake command "ie_add_sample".
```
How to generate an executable sample, can you help me?
Thanks.

**Comment by vladimir-dudnik** [comment]
please follow instructions in [Build the Demo Applications](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#build-the-demo-applications) section of Open Model Zoo Demos [READNE.md](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/README.md) file

**Comment by dxxhjk** [comment]
What should I do after i compiled opencv and openvino? I cloned codes from `https://github.com/openvinotoolkit/open_model_zoo` but i couldn't find `deployment_tools/bin/setupvars.sh` anywhere. What dose `<INSTALL_DIR>` mean? opencv, openvino or open_model_zoo? 
Looking forward to your reply, thanks.

**Comment by vladimir-dudnik** [comment]
@dxxhjk Open Model Zoo demo instructions provided for Open Model Zoo distributed with OpenVINO binary package. It is expected that one who decide to build everything from sources on his own - know what he is doing.

There is no any magic in these setupvars scripts (.SG for linux and .BAT for windows). They basically set up necessary environment variables, which help to build and run OpenVINO based applications. 

In OpenVINO repository you may find [setupvars](https://github.com/openvinotoolkit/openvino/tree/master/scripts/setupvars) scripts, which comes to binary distribution package, so you may learn from them what environment variables should be set in usual OpenVINO distribution.

If you are not sure to cope with all of these things I would recommend to start from binary distribution of OpenVINO.

**Comment by vladimir-dudnik** [comment]
@dxxhjk do you have additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
