### ISSUE TITLE
RuntimeError: get_element_type() must be called on a node with exactly one output. when running asl_recognition_demo.py

### ISSUE THREAD

**Issue by engineer0204** [openvinotoolkit/open_model_zoo#1845]
Hi, 
I got this problem when I run the asl_recognition_demo.py
I thought the problem is in "-d MYRIAD", because when I remove this everything is fine
How can I use NCS2 with "-d MYRIAD" this commend and don't get anything wrong??
thinks
```
D3H:/opt/intel/openvino_2021.1.110/deployment_tools/open_model_zoo/demos/python_demos/asl_recognition_demo$ python3 asl_recognition_demo.py -m_a ~/models/asl-recognition-0004.xml -m_d ~/models/person-detection-asl-0001.xml -i 0 -c ./classes.json -d MYRIAD
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "asl_recognition_demo.py", line 235, in <module>
    sys.exit(main() or 0)
  File "asl_recognition_demo.py", line 115, in main
    person_detector = PersonDetector(args.detection_model, args.device, ie_core,
  File "/opt/intel/openvino_2021.1.110/deployment_tools/open_model_zoo/demos/python_demos/asl_recognition_demo/asl_recognition_demo/person_detector.py", line 29, in __init__
    super().__init__(model_path, device, ie_core, num_requests, output_shape)
  File "/opt/intel/openvino_2021.1.110/deployment_tools/open_model_zoo/demos/python_demos/asl_recognition_demo/asl_recognition_demo/common.py", line 40, in __init__
    self.exec_net = ie_core.load_network(network=self.net,
  File "ie_api.pyx", line 311, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 320, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: get_element_type() must be called on a node with exactly one output.
```

**Comment by vladimir-dudnik** [comment]
@engineer0204 this model may not work on MyriadX

**Comment by engineer0204** [comment]
Hi,
where can I fine a list for working on MyriadX
I find this [Demos that Support Pre-Trained Models](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/README.md), but I can't see any information about asl_recognition_demo
btw. the "single-human-pose-estimation-0001" is actually doing well on MyriadX, but it says it's not Supported in the list.

**Comment by vladimir-dudnik** [comment]
@engineer0204 thanks for notice on single-human-pose-estimation-0001, we need to update info

@moslex FYI

**Comment by vladimir-dudnik** [comment]
@engineer0204 for the upcoming OpenVINO 2021.4 release we plan to add a table for models support per inference devices, see PR #2367 update OMZ 2021.4 documentation

**Comment by vladimir-dudnik** [comment]
Tables for [Intel](https://docs.openvinotoolkit.org/latest/omz_models_intel_device_support.html) and [public](https://docs.openvinotoolkit.org/latest/omz_models_public_device_support.html) models to list supported devices added in OpenVINO 2021.4 release
