### ISSUE TITLE
object_detection_demo_ssd_async.py  models list

### ISSUE THREAD

**Issue by Seph85** [openvinotoolkit/open_model_zoo#1855]
In the models list attached to this demo there is a voice 
person-detection-????
However if I try to use the **person-detection-action-recognition-0006** an error occurs.
It says `unsupported model outputs`

**Comment by vladimir-dudnik** [comment]
@Seph85 that is correct. Regular expresion person-detection-???? expanded to person-detection-0106/0200/0201/0202 models

**Comment by Seph85** [comment]
Thanks for the clarification
