### ISSUE TITLE
confusing about RGB and BGR input

### ISSUE THREAD

**Issue by thancaocuong** [openvinotoolkit/open_model_zoo#1872]
Hi, I'm so confusing about the RGB and BGR mean and scale value. Suppose I have model trained with RGB order, and the input is zero centered by dividing by 255, then subtract mean [0.485, 0.456, 0.406] and scale by std [0.229, 0.224, 0.225]. So when run optimizer, I use the following command
```bash
../deployment_tools/model_optimizer/mo.py --input_shape [1,3,320,320] --input_model mymodel.onnx --mean_values input[123.675,116.28,103.53] --scale_values input[58.395,57.12,57.375] --input "input" --output "out1","out2" --reverse_input_channels
```
So is it correct, I mean I use mean value 255 * mean and std is 255 * std. It's from normalized_image = (image/255 - mean) / std. When inference, I use BGR image to feed to the input buffer. Could you tell me what wrong with me?

**Comment by eaidova** [comment]
@thancaocuong why do you think that your actions is not correct?
Usage BGR channels order and mean scale during model conversion is just a recommendation (our demos assume that model has bgr as input color format and no mean/scale performed on data). If you do not plan to use demos, then you can keep original preprocessing and model also will work with RGB and normalization performed on data.

regarding conversion command MO can not normalize image in several steps (divide by 255, then by std), it is the reason why multiplication used normalized_image = (image/255 - mean) / std = (image - mean * 255) / std * 255, it is an equivalent operations. Switching channels happens after normalization, so you should keep original mean, scale order (I mean  input[123.675,116.28,103.53], not input[103.53,116.28, 123.675]). After that ready IR accept BGR image in [0, 255] pixel range.

**Comment by thancaocuong** [comment]
@eaidova  thank you. That's exactly that I want to know.
