### ISSUE TITLE
About the classes of the person-vehicle-bike-detection-crossroad-0078

### ISSUE THREAD

**Issue by pingchesu** [openvinotoolkit/open_model_zoo#1880]
Based on the description of the person-vehicle-bike-detection-crossroad-0078, this model will predict Vehicle, Pedestrain and Bike. It's seems that the number of classes are 3. However when I check this file [person-vehicle-bike-detection-crossroad-0078.prototxt](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-vehicle-bike-detection-crossroad-0078/person-vehicle-bike-detection-crossroad-0078.prototxt#L7751), the num_classes was 4. Did I misunderstood the meaning of this file? Can you provide the classes_id_mapping of this model? Really thanks!!!

**Comment by eaidova** [comment]
@pingchesu the number of valid classes is 3  (1- person, 2 - vehicle, 3 - bike). 0 class is background, it is not visible for user in the final prediction, it is the reason why we do not take it into account.

**Comment by eaidova** [comment]
@pingchesu we update model description, thank you for your note!

**Comment by pingchesu** [comment]
@eaidova Really appreciate for answering my question!!!
