### ISSUE TITLE
PR 1793 breaks input from camera support in action_recognition demo

### ISSUE THREAD

**Issue by vladimir-dudnik** [openvinotoolkit/open_model_zoo#1888]
After https://github.com/openvinotoolkit/open_model_zoo/pull/1793 can't specify input from camera

@Wovchena FYI

**Comment by anzhella-pankratova** [comment]
In https://github.com/openvinotoolkit/open_model_zoo/pull/1793 the camera input does not convert to int type, so the capture fails to open it. 
This issue is fixed in https://github.com/openvinotoolkit/open_model_zoo/pull/1848, there the input reading is rewritten.

**Comment by anzhella-pankratova** [comment]
@vladimir-dudnik After merging https://github.com/openvinotoolkit/open_model_zoo/pull/1848 it works fine, I checked the demo.
