### ISSUE TITLE
Can python_demos/object_detection_demo_ssd_async run ssd_mobilenet_v2_coco and ssdlite_mobilenet_v2?

### ISSUE THREAD

**Issue by ytfksw** [openvinotoolkit/open_model_zoo#1912]
`ssd-resnet34-1200-onnx` is included in [python_demos/object_detection_demo_ssd_async/models.lst](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_ssd_async/models.lst), but the other ssd models are not.
Are these supported?

It does not include ssd_mobilenet_v2_coco and ssdlite_mobilenet_v2, which are important models for mobile devices.

Models of ssd in models/public that are not included in the list:
- ssd300
- ssd512
- ssd_mobilenet_v1_coco
- ssd_mobilenet_v1_fpn_coco
- ssd_mobilenet_v2_coco
- ssd_resnet50_v1_fpn_coco
- ssdlite_mobilenet_v2

**Comment by vladimir-dudnik** [comment]
object_detection_demo_ssd_async should be able to work with all models which have SSD type output. Thanks for notice, we will validate demo with these models and update models.lst file.

Note, in OpenVINO 2021.2 release, which is coming soon, we have modified object detection demo, by joining support for different object detection models into one application (one for C++ and another one for Python). This implemented by introducing detection model class hierarchy, where we define a base class and implement the difference in processing model's output in child classes. It will have name object_detection_demo and demo will require to specify type of model (which define what child class should be used to process output) as command line parameter of application. You may see that approach in 'develop' branch while release is preparing.
Going further we plan to provide similar class hierarchy for segmentation models and possible for other common cases.

**Comment by ytfksw** [comment]
@vladimir-dudnik 
Thank you so much for your prompt response!

It's fascinating to me that in the OpenVINO 2021.2 release, the object detection demo will become a unified interface!
