### ISSUE TITLE
Where is a demo of human pose estimation with EfficientHRNet model?

### ISSUE THREAD

**Issue by UnaNancyOwen** [openvinotoolkit/open_model_zoo#1929]
Where is a demo of human pose estimation with new EfficientHRNet model?
[human_pose_estimation_demo](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/human_pose_estimation_demo) does not seem to support those models.

* [models/intel/human-pose-estimation-0002](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/human-pose-estimation-0002)
* [models/intel/human-pose-estimation-0003](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/human-pose-estimation-0003)
* [models/intel/human-pose-estimation-0004](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/human-pose-estimation-0004)

**Comment by eaidova** [comment]
@UnaNancyOwen please use python demo version

**Comment by UnaNancyOwen** [comment]
thanks!
