### ISSUE TITLE
can not use model 2018 in openvino version 2021 and no was to convert

### ISSUE THREAD

**Issue by vijayky88** [openvinotoolkit/open_model_zoo#1937]
Hi,
earlier i was using **face-reidentification-retail-0095** for openvino version 2019.  now i wanted to switch openvino 2021 version but i can t use the above model generated for openvino-2018. Can you suggest me any workaround so that i can use that model in open vino version 2021.

Thanks
Vijay

**Comment by vladimir-dudnik** [comment]
there is no way to use old IR models with latest 2021 OpenVINO runtime. We are working on getting model back to release.

**Comment by vladimir-dudnik** [comment]
@vijayky88 do you have additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
