### ISSUE TITLE
How can I use webcam(IntelRealsense) as input instead of mp4 file

### ISSUE THREAD

**Issue by laifuchicago** [openvinotoolkit/open_model_zoo#1950]
To Author:
I am currently using recorded mp4 file as input to do the vehicle detection on Windows 10. However, if I want to use your IntelRealsense camera D430i as the input. Do you have any idea? In Linux we use dev/video0 as input. How about Windows?
I use -i cam but the error occured
![ERROR1](https://user-images.githubusercontent.com/8537280/102957321-1ee6bd00-4515-11eb-9546-c43778750b9b.PNG)

Jonathan Sung

**Comment by vladimir-dudnik** [comment]
That question not related to OpenVINO or Open Model Zoo, I would recommend to ask that question on OpenCV repo/forum.
@alalek FYI

**Comment by avitial** [comment]
@laifuchicago depending on which OpenVINO demo/sample you are trying you may have to modify the source code to use appropriate device. For example in _object_detection_demo_ssd_async_ C++ demo, in _main.cpp_ edit line 88 `cap.open(0)` from 0 to 1/2/3/etc. depending on which one is the RGB device of the RealSense camera, then rebuild demo.
```
// line 88
(!((FLAGS_i == "cam") ? cap.open(0) : cap.open(FLAGS_i.c_str()))) { or 
```

**Comment by vladimir-dudnik** [comment]
@laifuchicago do you have additional questions?
