### ISSUE TITLE
Openvino inference speech model

### ISSUE THREAD

**Issue by CVUsers** [openvinotoolkit/open_model_zoo#1975]
Hello, I see that you mentioned in other issues that the deep speech model has been deployed to omz. I used: deployment_ tools/demo/demo_ speech_ recognition.sh , downloaded the model of deep speech: XML bin, CFG, FST and other models. I see that you are using CFG and FST (the model is too large). Is there any parsing method for XML and bin, just like Yolo's reasoning parsing method for XML bin? In addition, I checked the neural network in XML. The input is 1x143 and the output is 1024x3312. What does this mean? How can I parse? Can you provide:

Inference speech recognition XML bin mode and code

Reasoning Chinese speech model

cver Intel openvino partner

**Comment by vladimir-dudnik** [comment]
@CVUsers not sure I completely understand your question. Please note, OpenVINO has two speech recognition models, Kaldi models, which have a separate demo in OpenVINO (you may find it under <OpenVINO install root>/data_procesing/audio/speech_recognition and with Open Model Zoo we also provide some public speech recognition models and associated [demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/speech_recognition_demo/README.md) application, namely, [mozilla-deepspeech-0.6.1](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/mozilla-deepspeech-0.6.1/mozilla-deepspeech-0.6.1.md) and [mozilla-deepspeech-0.8.2](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/mozilla-deepspeech-0.8.2/mozilla-deepspeech-0.8.2.md).
Hope this helps.

**Comment by vladimir-dudnik** [comment]
@CVUsers do you have additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
