### ISSUE TITLE
The inference time of Super Resolution C++ Demo?

### ISSUE THREAD

**Issue by odefiao** [openvinotoolkit/open_model_zoo#2007]
Hi,  I am trying the Super Resolution C++ Demo, single-image-super-resolution-1033
the openvino version is 2021R01, CORE i78th
but, i got the inference time is : **100 ms**.
It's too slow, can you tell me the inference time during your test?
Thank you and look forward to your reply.
``` 
slog::info << "Start inference" << slog::endl;
float time_eval_s, time_eval_e;
for (int i = 0; i < 20; i++)
{
	time_eval_s = std::clock();
	inferRequest.Infer();
	time_eval_e = std::clock();
	slog::info << i << " time consuming is :" << static_cast<double>(time_eval_e - time_eval_s) / CLOCKS_PER_SEC << slog::endl;
}
```

**Comment by vladimir-dudnik** [comment]
OpenVINO 2021.2.185 internal performance tests show data like 7..8 FPS on Core i7-8700 CPU for single-image-super-resolution-1033 for FP32 IR, 9.6 FPS for FP16 on iGPU and 13..16 FPS for INT8 on the same CPU

**Comment by vladimir-dudnik** [comment]
@odefiao do you have additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
