### ISSUE TITLE
Horizontal Text Detection on Myriad

### ISSUE THREAD

**Issue by InzamamAnwar** [openvinotoolkit/open_model_zoo#2029]
Hi,

I am trying to compile `horizontal-text-detection-0001` for myriad using the below command.
```
%cd "/content/"
model_name = "./intel/horizontal-text-detection-0001/FP16/horizontal-text-detection-0001"
!source /opt/intel/openvino_2021.1.110/bin/setupvars.sh && \
    /opt/intel/openvino_2021.1.110/deployment_tools/inference_engine/lib/intel64/myriad_compile -m ./{model_name}.xml -o ./{model_name}_custom.blob -ip U8 -VPU_NUMBER_OF_SHAVES 4 -VPU_NUMBER_OF_CMX_SLICES 4
```

But I am having the following **warning** and the model is not being converted to blob file. Have anyone encountered this 
problem or know solution for this?

```
[setupvars.sh] OpenVINO environment initialized
Inference Engine: 
	API version ............ 2.1
	Build .................. 2021.1.0-1237-bece22ac675-releases/2021/1
	Description ....... API
[Warning][VPU][Config] Deprecated option was used : VPU_MYRIAD_PLATFORM
get_element_type() must be called on a node with exactly one output.
```

**Comment by vladimir-dudnik** [comment]
@InzamamAnwar this model did not work on MyriadX during validation of OpenVINO 2021.1 and 2021.2, So it might be not supported on MyriadX.

**Comment by InzamamAnwar** [comment]
@vladimir-dudnik thank you for clarification. Do you have some reasoning behind it for not working with myriad specially? Also is there any pre-trained model available for getting only bounding boxes for text in images. As in case of `text-detection-*` we get linkages and not bounding boxes.

**Comment by vladimir-dudnik** [comment]
@InzamamAnwar most probably model does not work on MyriadX because some of layers not implemented. It is better to ask details on OpenVINO github.

OMZ also contain public [ctpn](https://github.com/vladimir-dudnik/open_model_zoo/tree/master/models/public/ctpn) text detection model, we do not have OMZ demo for it yet, but this should work on MyriadX.

**Comment by InzamamAnwar** [comment]
Thank you for quick responses.
