### ISSUE TITLE
Make: Error on or near line 85; exiting with status 1 seen with Raspberry Pi 4 OpenVINO Docker container

### ISSUE THREAD

**Issue by jomoengineer** [openvinotoolkit/open_model_zoo#2040]
While running through the install of the Model Zoo examples on a Raspberry Pi OpenVINO Docker instance, both make and build_demos.sh script fail:
OpenVINO Toolkit version: 2021.2
CMake version: 3.13.4
GCC Version: 8.3.0
GNU Make version: 4.2.1

Model Zoo was downloaded via git:
  **git clone https://github.com/opencv/open_model_zoo.git**

Error from build_demos.sh:

```
/usr/include/c++/8/bits/vector.tcc: In member function ‘DetectionLog PedestrianTracker::GetDetectionLog(bool) const’:
/usr/include/c++/8/bits/vector.tcc:109:4: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<DetectionLogEntry*, std::vector<DetectionLogEntry> >’ changed in GCC 7.1
    _M_realloc_insert(end(), std::forward<_Args>(__args)...);
    ^~~~~~~~~~~~~~~~~
[ 68%] Linking CXX executable ../armv7l/Release/pedestrian_tracker_demo
[ 68%] Built target pedestrian_tracker_demo
make: *** [Makefile:130: all] Error 2
Error on or near line 85; exiting with status 1

``` 

Make error:
```
  std::__inplace_stable_sort(__first, __last, __comp);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/8/bits/stl_algo.h:5006:29: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<std::pair<std::__cxx11::basic_string<char>, InferenceEngine::InferenceEngineProfileInfo>*, std::vector<std::pair<std::__cxx11::basic_string<char>, InferenceEngine::InferenceEngineProfileInfo> > >’ changed in GCC 7.1
  std::__stable_sort_adaptive(__first, __last, __buf.begin(),
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         _DistanceType(__buf.size()), __comp);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 85%] Linking CXX executable ../armv7l/Release/security_barrier_camera_demo
/usr/bin/ld: CMakeFiles/security_barrier_camera_demo.dir/main.cpp.o: in function `ResAggregator::process()':
main.cpp:(.text+0x3580): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: CMakeFiles/security_barrier_camera_demo.dir/main.cpp.o: in function `Drawer::process()':
main.cpp:(.text+0x5f8c): undefined reference to `__atomic_load_8'
/usr/bin/ld: CMakeFiles/security_barrier_camera_demo.dir/main.cpp.o: in function `main':
main.cpp:(.text.startup+0x4034): undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [security_barrier_camera_demo/CMakeFiles/security_barrier_camera_demo.dir/build.make:98: armv7l/Release/security_barrier_camera_demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:1148: security_barrier_camera_demo/CMakeFiles/security_barrier_camera_demo.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by jomoengineer** [comment]
After doing some searchin', I found this to resolve the make errors.
I added the following to the bottom of the CMakeLists.txt for the security_barrier_camera_demo and the text_detection_demo.
```
set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")
```
After deleting and recreating the build folder, I ran the cmake command as described in the link and successfully ran make on the demos:

**Comment by vladimir-dudnik** [comment]
@jomoengineer thanks for updating on this. We'll look if we need to update OMZ build scripts.

**Comment by vladimir-dudnik** [comment]
@terfendail @alalek could you please suggest what conditional we may use in Open Model Zoo demo cmake scripts to detect build on/for RasperryPi and add line below. Is that compiler version or OS version?

> set(CMAKE_CXX_LINK_FLAGS "${CMAKE_CXX_LINK_FLAGS} -latomic")

@IRDonch @Wovchena we may need to consider to add some conditional to OMZ cmake to support OpenVINO RasperryPi package.

**Comment by IRDonch** [comment]
`libatomic` is used by GCC when it can't generate lock-free code for atomic fetches/updates. IMO, we should just avoid such situations instead of linking in the library.

In the case of `security_barrier_camera_demo` this is most likely caused by the `std::atomic<uint64_t> frameCounter` variable. I think we can safely downgrade this variable to 32-bit, since it'll still take over two continuous years of 60 FPS video to overflow a 32-bit frame counter. :-)

I don't know why this would affect `text_detection_demo`, though; it doesn't use atomics at all.

@jomoengineer Could you check if changing the type of `frameCounter` to `std::atomic<uint32_t>` in `demos/security_barrier_camera_demo/cpp/main.cpp` fixes the issue? Also, why did you need to update `text_detection_demo`, what were the errors with its compilation?

**Comment by jomoengineer** [comment]
@IRDonch The 'text_detection_demo' issue I had seen might have been a result of the other errors I was seeing. I've rebuild it without the change to the CMakeList.txt and it compiles fine. 

Changing frameCounter to std::atomic<uint32_t>  in 'demos/security_barrier_camera_demo/main.cpp' seems to correct the issue. 
Note: The path on my system to main.cpp is different than what you show. Also, there is other entries in main.cpp that use 'uint64_t' as well so I am not sure if that would pose an issue on a 32-bit platform.

**Comment by vladimir-dudnik** [comment]
@jomoengineer as I get form what @IRDonch saying is that using std::atomic<uint64_t> will cause this issue. Ordinary uint64_t variable will not bring that because not declared as atomic.

**Comment by vladimir-dudnik** [comment]
@jomoengineer seems issue was fixed (fix will be available in the next release). Do you have additional questions?
