### ISSUE TITLE
common-sign-language model

### ISSUE THREAD

**Issue by tunght** [openvinotoolkit/open_model_zoo#2058]
Hi,

I'm trying to run the gesture detection demo with common-sign-language model.
However when I use the model optimizer to convert the model to IR format I get this error

Model Optimizer version:        2021.2.0-1877-176bdf51370-releases/2021/2
[ ERROR ]  Cannot infer shapes or values for node "Conv_0".
[ ERROR ]  Data after padding has dimension less than window size. Possible reason of error is incorrectly specified model input shape(s).
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Convolution.infer at 0x7ff89a655af0>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Conv_0" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

this is the command that I used
python3 mo.py --input_model s3d-rgb-mobilenet-v3-large-stream-jester.onnx

Can you please help?

Thank you
Tung

**Comment by vladimir-dudnik** [comment]
@tunght most probably you miss some parameters or use some wrong parameters for MO. That is why we recommend to use OMZ downloader.py and converter.py scripts to download and convert the model. These scripts use model.yml file to read all necessary parameters and then call MO with correct parameters. These parameters are validated to work for corresponding OpenVINO release. Please read OMZ tools [documentation](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/README.md) to see how to use them. Basically it is quite simple, after setting up correct python environment you just call `converter.py --name common-sign-language-0001` and it will convert model to IR

**Comment by tunght** [comment]
@vladimir-dudnik Thank you very much.
I'm able to convert the model

**Comment by rahullrajesh** [comment]
where did you get the class_map?

**Comment by 836999113** [comment]
Hello, I can not download **s3d-rgb-mobilenet-v3-large-stream-jester.onnx** anymore. Could you share this doc pls?
