### ISSUE TITLE
what's the data type of face-detection-adas-0001

### ISSUE THREAD

**Issue by guoyejun** [openvinotoolkit/open_model_zoo#2068]
https://docs.openvinotoolkit.org/2018_R5/_docs_Transportation_object_detection_face_pruned_mobilenet_reduced_ssd_shared_weights_caffe_desc_face_detection_adas_0001.html

```
name: "input" , shape: [1x3x384x672] - An input image in the format [BxCxHxW]
```
is the input data type uint8_t with range [0, 255]? or float with range [0.0, 1.0], or float with range [0.0, 255.0]?

```
The net outputs blob with shape: [1, 1, N, 7], 
```
is the output data type float?

**Comment by eaidova** [comment]
@guoyejun all provided in OMZ models requires BGR image in [0, 255] (FP32 used in openvino as main input data type by default) if any other details is not provided..
Regarding output format, yes it is float. Output contains normalized detected bounding box coordinates in [0, 1] range.

**Comment by guoyejun** [comment]
That's great. I can make the model input/output fixed in FFmpeg DNN module. thanks.
