### ISSUE TITLE
3D Convolution supported or not?

### ISSUE THREAD

**Issue by dedoogong** [openvinotoolkit/open_model_zoo#2095]
Hi, I saw there is no CONV-3D layers in the supported layers by openvino webpage, but I found someone converted 3d Convolution layer of keras(tensorlfow backend) successfully( https://github.com/avbelova/POT_tutorial/tree/master/advanced_materials/3d_unet_demo )

Can anybody tell me what is true?

Thank you!

**Comment by eaidova** [comment]
@dedoogong in OMZ you can find several models with 3d convolutions (e.g. [brain-tumor-segmentation-0001](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/brain-tumor-segmentation-0001/brain-tumor-segmentation-0001.md)/[0002](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/brain-tumor-segmentation-0002/brain-tumor-segmentation-0002.md), [I3D-rgb](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/i3d-rgb-tf/i3d-rgb-tf.md), [common-sign-langualge-recognition-0001](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/common-sign-language-0001/common-sign-language-0001.md))
these models converted from different frameworks (MXNet, TF, Pytorch), so the answer on your question should be yes,  openvino supports 3d conv nets.

If you have trouble with conversion or inference some specific model, not from OMZ, please let us know in the main [openvino](https://github.com/openvinotoolkit/openvino) repo.

**Comment by eaidova** [comment]
Also you can look on [Convolution description](https://docs.openvinotoolkit.org/latest/openvino_docs_ops_convolution_Convolution_1.html) in openvino opset specification.
It mentions 3d convolution case:
> Inputs:
> 
> 1. Input tensor of rank 3 or greater. Required.
> 2. Convolution kernel tensor. Weights layout is OIYX (OIZYX for 3D convolution), which means that X is changing the fastest, then Y, then Input, then Output. The size of the kernel is derived from the shape of this input and not specified by any attribute. Required.
