### ISSUE TITLE
Python demos do not run on Raspberry Pi 4 with Raspbian 10

### ISSUE THREAD

**Issue by jomoengineer** [openvinotoolkit/open_model_zoo#2135]
I'm attempting to run the python_demos from Open Model Zoo on a Raspberry Pi 4 with Raspbian 10, however I am not able to run these.  I have set the environment with 'setupvars.sh' but the Python demos do not seem to find certain dependencies.

Example: object_detection_demo
```
pi@raspberrypi:~/open_model_zoo/demos $ python3 ./python_demos/object_detection_demo/object_detection_demo.py -h
Traceback (most recent call last):
  File "./python_demos/object_detection_demo/object_detection_demo.py", line 32, in <module>
    from models import *
  File "/home/pi/open_model_zoo/demos/python_demos/common/models/__init__.py", line 19, in <module>
    from .yolo import YOLO
  File "/home/pi/open_model_zoo/demos/python_demos/common/models/yolo.py", line 18, in <module>
    import ngraph
ModuleNotFoundError: No module named 'ngraph'
```
Looking at the environment variables, it does seem like there a reference to ngraph.
```
pi@raspberrypi:~/open_model_zoo/demos $ env |grep ngraph
LD_LIBRARY_PATH=/opt/intel/openvino/opencv/lib:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/hddl/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino/deployment_tools/inference_engine/lib/armv7l
ngraph_DIR=/opt/intel/openvino/deployment_tools/ngraph/cmake

```
It appears there are files listed in the ngraph lib folder:
```
pi@raspberrypi:~/open_model_zoo/demos $ ls /opt/intel/openvino/deployment_tools/ngraph/lib
libngraph.so  libonnx_importer.so
```

I am not sure what I am missing here.

**Comment by vladimir-dudnik** [comment]
@jomoengineer thanks for noticing this, you are right, OpenVINO install package for RaspberryPi does not include ngrpah python api, we will review possibility to add this in future OpenVINO releases. Meantime, ngraph python module is only needed for OMZ demo to work with yolo models, it is safe to comment out this import if you not going to work with yolo models

**Comment by cosmos1982** [comment]
@jomoengineer , could you tell me what version of openvino raspbian package do you use?

**Comment by jomoengineer** [comment]
@cosmos1982 I would suspect it was with 2021.2 considering that is what I was testing with at that time.

**Comment by cosmos1982** [comment]
@jomoengineer Thanks, and did you solve your problem if comment out "import ngraph" as suggested?

**Comment by jomoengineer** [comment]
@cosmos1982 Yeah, I believe I was able to get some of the Python examples to work after commenting out the import of ngraph.

I suppose this can be closed since I am not working on this at this time.

Thanks.

**Comment by vladimir-dudnik** [comment]
closing as suggested
