### ISSUE TITLE
How to run single_human_pose_estimation_demo.py?

### ISSUE THREAD

**Issue by kevkid** [openvinotoolkit/open_model_zoo#2151]
I am trying to run this demo, I found this https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/single_human_pose_estimation_demo

and I am trying to follow the example:
`C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\open_model_zoo\demos\python_demos\single_human_pose_estimation_demo>python single_human_pose_estimation_demo.py --model_od C:\Users\kevin\Downloads\Intel\mobilenet-ssd\mobilenet-ssd.xml --model_hpe C:\Users\kevin\Downloads\Intel\human-pose-estimation-0001\FP16-INT8\human-pose-estimation-0001.xml -i video.mp4`

```
but I get this garbage: 
Traceback (most recent call last):
  File "single_human_pose_estimation_demo.py", line 121, in <module>
    run_demo(args)
  File "single_human_pose_estimation_demo.py", line 81, in run_demo
    device=args.device)
  File "C:\Program Files (x86)\Intel\openvino_2021\deployment_tools\open_model_zoo\demos\python_demos\single_human_pose_estimation_demo\estimator.py", line 91, in __init__
    assert len(self.model.outputs) == 1, "Expected 1 output blob"
AssertionError: Expected 1 output blob
```

What am I doing wrong here? I downloaded the mobilenet-ssd via the downloader then converted it. I downloaded the HPE via the downloader too, but did not convert it as it already is in IR format.

**Comment by vladimir-dudnik** [comment]
@kevkid single_single_human_pose_estimation_demo designed to work with single-human-pose-estimation-0001 model. For human-pose-estimation-0001 you may use C++ human-pose-estimation demo.

**Comment by vladimir-dudnik** [comment]
@kevkid do you have any additional questions?

**Comment by vladimir-dudnik** [comment]
question answered
