### ISSUE TITLE
 What kind of neural network structure is this model "semantic-segmentation-adas-0001" based on ？For instance Unet?Pspnet?  Looking forward to your answer！！

### ISSUE THREAD

**Issue by muyufujianxiaobawang** [openvinotoolkit/open_model_zoo#2154]
I don't know how to get the detail of the model"**semantic-segmentation-adas-0001**" which is used in my study./I'll be very grateful if you can answer it . Thank you! @openvino-pushbot

**Comment by vladimir-dudnik** [comment]
@muyufujianxiaobawang please take a look at corresponding model folder in Open Model Zoo. All information we have is there. You may notice that model was implemented in Caffe framework and see [.prototxt](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/semantic-segmentation-adas-0001/semantic-segmentation-adas-0001.prototxt) file.

Why do you wonder model structure? If your goal is to fine-tune model on your specific data, you might be interested to take a look at [OpenVINO Training Extension](https://github.com/openvinotoolkit/training_extensions/blob/develop/README.md), which is set of tools and training pipeline configurations which allow fine-tuning for set of models.

cc @snosov1

**Comment by muyufujianxiaobawang** [comment]
I'm sorry to take so long to reply to your answer. I want to know if this model is original by Intel, or just an implementation of an existing model?

**Comment by muyufujianxiaobawang** [comment]
I'm sorry to take so long to reply to your answer. I want to know if this model is original by Intel, or just an implementation of an existing model? @vladimir-dudnik

**Comment by vladimir-dudnik** [comment]
@snosov1 could you please comment on semantec-segmentation-adas-0001 model details?

**Comment by Daniil-Osokin** [comment]
Hi! The network structure looks like ICNet described in the "[ICNet for Real-Time Semantic Segmentationon High-Resolution Images](https://arxiv.org/pdf/1704.08545.pdf)".

**Comment by vladimir-dudnik** [comment]
closing as answered
