### ISSUE TITLE
xml and bin files

### ISSUE THREAD

**Issue by dhruvsheth-ai** [openvinotoolkit/open_model_zoo#2161]
Hi, I'm trying to locate the xml and bin files corresponding to the model.yml in intel pre-trained models. Is there a specific link to access these files, or do we have to pertain to downloader.py to download models. It would be great if there is "resource" page to find the files

Edit: Figured it out

**Comment by memona008** [comment]
@dhruvsheth-ai Please mention where did you find those files.
