### ISSUE TITLE
is the output name of DENSENET-121 correct?

### ISSUE THREAD

**Issue by tyoungroy** [openvinotoolkit/open_model_zoo#2179]
When i check the prototxt file i can't the name of `prob` which is mentioned as output name of the model [link](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/densenet-121/densenet-121.md)
Event though i ran the model and look into layers name, i can't find the `prob`. there is only `fc6`.

**Comment by vladimir-dudnik** [comment]
@eizamaliev please take a look on this question

**Comment by eizamaliev** [comment]
@tyoungroy thank you for attention. We are fixing it.
