### ISSUE TITLE
Request a template python demo for model person-detection-0203

### ISSUE THREAD

**Issue by hoangkhoiLE** [openvinotoolkit/open_model_zoo#2182]
Hi, thank for your excellent work.
Now I study the model multi_camera_multi_target_tracking by this link 
https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/multi_camera_multi_target_tracking with your model that names "person-detection-0203".

the commands that i use is:

python3.7 multi_camera_multi_target_tracking.py -i test.mp4 --m_detector person-detection-0203.xml --m_reid person-reidentification-retail-0277.xml --config configs/person.py  

And i got this error :
![image](https://user-images.githubusercontent.com/57557628/110462040-7b975400-80d0-11eb-9395-892f3cc779f8.png)

Do we have template specific for this model "person-detection-0203" ? Please help me in this case.

Best regard !

**Comment by vladimir-dudnik** [comment]
@hoangkhoiLE  Models may have different format of output layers and so require different postprocessing to extract detection results. That is why we specify particular models which demo was designed to work with in file [models.lst](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/python_demos/multi_camera_multi_target_tracking/models.lst). Note, you may use this file as a parameter to model downloader, to load only models which supported by this particular demo and so avoid this issues when you try to apply model which demo can't process.
So, all in all, the person-detection-0203 model can't be used with this demo.

**Comment by eizamaliev** [comment]
@hoangkhoiLE please specify version of OpenVINO.

**Comment by hoangkhoiLE** [comment]
@vladimir-dudnik Thank you for your kind response, I will try with  python object_detection_demo.
@eizamaliev I have already test with the 2021.2, 2021.1, 2020.3 , 2020.4, none of them works

**Comment by hoangkhoiLE** [comment]
I have verified the version so that my version 2021.2 work, but the result of model "person-detection-0203" is wrong in comparison with   "person-detection-0202"
 "person-detection-0202"
![image](https://user-images.githubusercontent.com/57557628/110486812-4baa7980-80ed-11eb-941b-130ef2db779d.png)
"person-detection-0203" 
![image](https://user-images.githubusercontent.com/57557628/110486887-5ebd4980-80ed-11eb-9ea4-4fdae52f5111.png)

So may be there's something wrong in post processing...

**Comment by vladimir-dudnik** [comment]
you are right, seems there is an issue with postprocessing of this model output in demo, we'll take a look. Thanks for noticing this.

**Comment by eizamaliev** [comment]
Hi, @hoangkhoiLE! Please look at linked PR for solution

**Comment by hoangkhoiLE** [comment]
@eizamaliev  Hello, thank for your solution and excellent work . It works in my part.
