### ISSUE TITLE
Face Detection network should have only one input？

### ISSUE THREAD

**Issue by Curry30h** [openvinotoolkit/open_model_zoo#2186]

**Comment by vladimir-dudnik** [comment]
@Curry30h Are you asking about some particular model or this is question in general? Basically, number of model inputs or outputs not defined by model task, it depends on network implementation.

**Comment by Curry30h** [comment]
> @Curry30h Are you asking about some particular model or this is question in general? Basically, number of model inputs or outputs not defined by model task, it depends on network implementation.

When I use fast r-cnn perception V2 for inferencing, I will report this error，and the error of face detection network output layer should have 7 as a last dimension will be reported when using other models.

**Comment by eaidova** [comment]
@Curry30h  if I right understand you speak about demo for face detection and try to use it with some trained faster-rcnn perseption v2 model, is it correct?

We provide demo application code only based on Open Model Zoo repo content, so our demo applications has specific model list for supported models (e.g.  https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/interactive_face_detection_demo/models.lst, all of these models can be downloaded by model downloader and converted with model converter from OMZ) and it is expected that it may not work with custom models. Please feel free to adopt demo for work with your model if you need.

Regarding single input and 7 last dimension, looks like it is description SSD-based approach (majority of OMZ face detector uses this architecture as basic).

P.S. If we still not fully understand your ask, please provide more details

**Comment by Curry30h** [comment]
> @Curry30h if I right understand you speak about demo for face detection and try to use it with some trained faster-rcnn perseption v2 model, is it correct?
> 
> We provide demo application code only based on Open Model Zoo repo content, so our demo applications have specific model list for supported models (e.g. https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/interactive_face_detection_demo/models.lst, all of these models can be downloaded by model downloader and converted with model converter from OMZ) and it is expected that it may not work with custom models. Please feel free to adopt demo for work with your model if you need.
> 
> Regarding single input and 7 last dimension, looks like it is description SSD-based approach (majority of OMZ face detector uses this architecture as basic).
> 
> P.S. If we still not fully understand your ask, please provide more details

I use / opt / Intel / openvino / deployment_ tools/tools/model_ Script download model under downloader path and from https://docs.openvinotoolkit.org/cn/2020.3/_ docs_ MO_ DG_ prepare_ model_ convert_ model_ Convert_ Model_ From_ TensorFlow.html downloaded the model  convert to IR and then deployed to the accelerator  pillar. The above error appears when inferencing.What you mean by omz is omz_ demos_ Build this file?

**Comment by eaidova** [comment]
> What you mean by omz is omz_ demos_ Build this file?

under OMZ we understand open_model_zoo related entries (/opt/intel/openvino/deployment_tools/open_model_zoo) and this repo including demos and their build script. 
/ opt / Intel / openvino / deployment_ tools/tools/model_downloader is also part of open_model_zoo (as you can see there is soft link which lead to open_model_zoo/tools/downloader directory)

> The above error appears when inferencing.

Unfortunatly, I do not know what you use for inference (which scripts, applications and so on), but looks like these message from them and they do not support faster rcnn like face detection model or you use wrong application which is not designed to work with faster rcnn

> I use / opt / Intel / openvino / deployment_ tools/tools/model_ Script download model under downloader path and from https://docs.openvinotoolkit.org/cn/2020.3/_ docs_ MO_ DG_ prepare_ model_ convert_ model_ Convert_ Model_ From_ TensorFlow.html

As far as I know there is no face detection faster-rcnn pretrained  model in downloader script, so more likely you use wrong code for inference

**Comment by Curry30h** [comment]
> > What you mean by omz is omz_ demos_ Build this file?
> 
> under OMZ we understand open_model_zoo related entries (/opt/intel/openvino/deployment_tools/open_model_zoo) and this repo including demos and their build script.
> / opt / Intel / openvino / deployment_ tools/tools/model_downloader is also part of open_model_zoo (as you can see there is soft link which lead to open_model_zoo/tools/downloader directory)
> 
> > The above error appears when inferencing.
> 
> Unfortunatly, I do not know what you use for inference (which scripts, applications and so on), but looks like these message from them and they do not support faster rcnn like face detection model or you use wrong application which is not designed to work with faster rcnn
> 
> > I use / opt / Intel / openvino / deployment_ tools/tools/model_ Script download model under downloader path and from https://docs.openvinotoolkit.org/cn/2020.3/_ docs_ MO_ DG_ prepare_ model_ convert_ model_ Convert_ Model_ From_ TensorFlow.html
> 
> As far as I know there is no face detection faster-rcnn pretrained model in downloader script, so more likely you use wrong code for inference

I ran interactive_ face_ detection_ The demo uses fast r-cnn perception V2, squeezenet1.1 and Google net v2.

**Comment by eaidova** [comment]
@Curry30h  then, as I already said this demo is not designed to work with all of these models.
inside the demo you can find model.lst file which describes the models supported by interective_face_detection_demo.

regading faster-rcnn inception v2 it should be infered used object_detection_demo, squeezenet1.1 and googlenet v2 - using classification demo

**Comment by Curry30h** [comment]
> @Curry30h then, as I already said this demo is not designed to work with all of these models.
> inside the demo you can find model.lst file which describes the models supported by interective_face_detection_demo.
> 
> regading faster-rcnn inception v2 it should be infered used object_detection_demo, squeezenet1.1 and googlenet v2 - using classification demo

Thanks！！

**Comment by eaidova** [comment]
@Curry30h  do you have any additional questions or we can close this discussion?

**Comment by Curry30h** [comment]
> @Curry30h then, as I already said this demo is not designed to work with all of these models.
> inside the demo you can find model.lst file which describes the models supported by interective_face_detection_demo.
> 
> regading faster-rcnn inception v2 it should be infered used object_detection_demo, squeezenet1.1 and googlenet v2 - using classification demo

Thanks！！

> @Curry30h do you have any additional questions or we can close this discussion?

temporary not，close it，thanks.
