### ISSUE TITLE
Interactive Face Detection Python Demo missing.

### ISSUE THREAD

**Issue by anujonthemove** [openvinotoolkit/open_model_zoo#2202]
In earlier versions of OpenVINO toolkit, there used to be demos showing how to work on multiple/chained models. One such was the Interactive Face Detection Python Demo which is now missing. Will there be any demos showing how to implement chained models with the new OpenVINO 2021 or future releases?

**Comment by vladimir-dudnik** [comment]
@anujonthemove you probably mean Python [multi_camera_multi_target_tracking](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/python_demos/multi_camera_multi_target_tracking) demo, which still be there? As far as I know, there were no Python interactive_face_detection demo in OMZ.

**Comment by anujonthemove** [comment]
@vladimir-dudnik To be precise, there was a python demo named: face_recognition_demo which included the following models: **Face Detection model**, **Facial Landmarks Regression model**, **Face Reidentification model**, and Face matching algorithms: **Hungarian**, and **Min distance**. There is also a You Tube video on that demo here: https://www.youtube.com/watch?v=zgOoSjwMTLE

**Comment by vladimir-dudnik** [comment]
@anujonthemove that's right, there was a face recognition demo, but it was not interactive face detection python demo which was missed.
There are demos which show chained models (if you mean pipeline consisting from several models), [crossroad_camera_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/crossroad_camera_demo/README.md), [gaze_estimation_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/gaze_estimation_demo/README.md), [interactive_face_detection_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/interactive_face_detection_demo/README.md), [pedestrian_tracker_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/pedestrian_tracker_demo/README.md), [security_barrier_camera_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/security_barrier_camera_demo/README.md), [smart_classroom_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/smart_classroom_demo/README.md), [text_detection_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/text_detection_demo/README.md)

**Comment by anujonthemove** [comment]
@vladimir-dudnik I was curious to know if there are plans to bring back face recognition demo for the newer releases of OpenVINO?

Yes, I have already checked all the demos you have mentioned. They all are in C++. I am specifically looking for a python implementation for at least one of them where

**Comment by vladimir-dudnik** [comment]
@anujonthemove yes, we are considering to return back face recognition demo, pending additional license approval. Unfortunately, this will not happen yet in 2021.3 release which is coming soon.

**Comment by anujonthemove** [comment]
Okay, that answers my question. Thank you! 
I am closing the issue now and hope to see more python demos in future releases.
