### ISSUE TITLE
Model person-reidentification-retail-0277 : Threshold for cosine distance ?

### ISSUE THREAD

**Issue by hoangkhoiLE** [openvinotoolkit/open_model_zoo#2243]
Hello,
I'm very interesting in the model 

https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/person-reidentification-retail-0277/description/person-reidentification-retail-0277.md. 

I would like to know which is the threshold for  cosine distance that you use for compare the person to get Market-1501 rank@1 accuracy 96.2%. If possible, can you provide the threshold of other models person-reidentification  too so that we can use it as a default parameters ? Thank in advance !

Best regards

**Comment by vladimir-dudnik** [comment]
@snosov1 could you please comment on this?

**Comment by snosov1** [comment]
@sovrasov Vlad?

**Comment by sovrasov** [comment]
Hi. During evaluation on Market-1501 model ranks gallery images by cosine distance to query. Then evaluation protocol uses only this ranking to compute top-N accuracy and mAP without deriving any thresholds.

You can estimate a threshold on your data: to do that just prepare a dataset consisting of positive and negative pairs, estimate normalized histograms of positive and negative pairwise distances and then compute `t*: H_neg(t*) = H_pos(t*)`. t* is the optimal threshold in this setup. Positive/negative pairs could be also sampled from Market-1501 in case of lack of a real-world data. But in this case threshold would be biased to the distribution produced on Market-1501 and may not work correctly for your data.

**Comment by hoangkhoiLE** [comment]
@sovrasov Thank you for your kind answer ! I know that the threshold would be biased towards the distribution produced on Market-1501. However, in case that we can't collect more data, it would be one of the best value that we could use as default ! So I hope that you could please share the threshold as a good point to reference ! I very appreciate your help !

**Comment by sovrasov** [comment]
I haven't carry out any experiments of that kind on Market, so at the moment can't say anything about threshold there. If we're talking about scaled cosine similarity=0.5*(cos(a^b) + 1), in a tracking pipeline I was using threshold = 0.8 once to collect positive samples, but it wasn't always work correctly.

**Comment by hoangkhoiLE** [comment]
Thank you for your info !
