### ISSUE TITLE
Machine Translation Source Code Issue

### ISSUE THREAD

**Issue by mhamdan91** [openvinotoolkit/open_model_zoo#2286]
Hi, I am a developer with the devCloud team and I am currently developing a sample that uses the machine_translation_demo.py
I ran into several issues:

`    
parser.add_argument('--output-name', type=str, default='pred/Squeeze',
                        help='Optional. Name of the models output node.')
`

the default argument is invalid as the output node name is not that. For English <--> Deutsch models, the output name is "preds" and for English <--> Russian models the output name is "pred". So, to fix this,  I'd suggest recreating the model and renaming the output node with a common name across all models.  Then setting the default argument with that common output name.

The other issue is that, the code processes the input sentence word for word, meaning it feeds one word at a time to the model which results in a very bad translation. Here is the code segment that I am referring to in the machine_translation_demo.py

    if args.input:
        def sentences():
            for sentence in args.input:
                print("> {}".format(sentence))
                yield sentence
    else:
        def sentences():
            while True:
                yield input("> ")

    for sentence in sentences():
        if not sentence.strip():
            break

        try:
            start = time.perf_counter()
            translation = model(sentence)
            stop = time.perf_counter()
            print(translation)
            logger.info(f"time: {stop - start} s.")
        except Exception:
            log.error("an error occurred", exc_info=True)

What I recommend is feeding the entire sentence to the model for better context based translation. Possible fix should look like this (not necessarily, the fix): 

Remove this segment of code:

       if args.input:
           def sentences():
               for sentence in args.input:
                   print("> {}".format(sentence))
                   yield sentence
       else:
           def sentences():
               while True:
                   yield input("> ")
  

       for sentence in sentences():
           if not sentence.strip():
               break

Add this modified segment: 

    try:
        sentence = " ".join(args.input)
        start = time.perf_counter()
        translation = model(sentence)
        stop = time.perf_counter()
        print("> {}".format(sentence))
        print(translation)
        logger.info(f"time: {stop - start} s.")
    except Exception:
        log.error("an error occurred", exc_info=True)

**Comment by vladimir-dudnik** [comment]
@bes-dev could you please review this comment?

**Comment by bes-dev** [comment]
@mhamdan91 Hey, thanks for your feedback. I agree with you. We will fix it.

**Comment by bes-dev** [comment]
updates related to this issue: https://github.com/openvinotoolkit/open_model_zoo/issues/2286

**Comment by vladimir-dudnik** [comment]
2021.4 release published, so I'll close this. Feel free to reopen if you have additional questions
