### ISSUE TITLE
UNet Segmentation Model

### ISSUE THREAD

**Issue by ikeaney** [openvinotoolkit/open_model_zoo#2300]
Is there any examples of the unet_camvid_onnx_0001 model working? When I run inference on the model the results are not representative of what's in the image. See examples below

![camvid_openvino_1](https://user-images.githubusercontent.com/25864143/114615448-9fd0ec80-9c9d-11eb-9926-63bc14098f44.png)

![camvid_openvino_0](https://user-images.githubusercontent.com/25864143/114615533-b9723400-9c9d-11eb-8436-be1b704acc31.png)

**Comment by vladimir-dudnik** [comment]
Hello, below is screenshot of running Open Model Zoo Python segmentation demo from OpenVINO 2021.3 release, launched on Windows by following command:
python <demo_dir>\segmentation_demo.py -d CPU -i image.jpg -m <path_to_models>\unet-camvid-onnx-0001\FP16\unet-camvid-onnx-0001.xml -at segmentation -c <omz_dir>\data\palettes\camvid_12cl_colors.txt
![image](https://user-images.githubusercontent.com/9465398/114626422-5cd24180-9cbc-11eb-9544-fdf2aa4961ae.png)

**Comment by vladimir-dudnik** [comment]
@ikeaney do you have additional questions on this?

**Comment by vladimir-dudnik** [comment]
@ikeaney I close this, feel free to reopen if you have additional questions
