### ISSUE TITLE
'object detection demo' error with parameter '-o'

### ISSUE THREAD

**Issue by cosmos1982** [openvinotoolkit/open_model_zoo#2331]
Enviroment:  OpenVINO2021.3.394, win10, cmake version 3.14.7
Description:  
run following cmd in administrator privileges
```
object_detection_demo.exe -m C:\Work\tmp\public\ssd_resnet50_v1_fpn_coco\FP32\ssd_resnet50_v1_fpn_coco.xml -at ssd -i C:\Work\car_1.bmp -o C:\Work\tmp\car_result.bmp -labels C:\
Work\tmp\coco_labels.txt
```
will get this error:
```
MFX: Invalid frame size passed to encoder
[ERROR:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2021.3\build\windows\opencv\modules\videoio\src\cap.cpp (589) cv::VideoWriter::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.2-openvino) C:\jenkins\workspace\OpenCV\OpenVINO\2021.3\build\windows\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): C:\Work\tmp\car_result.bmp in function 'cv::icvExtractPattern'


[ ERROR ] Can't open video writer
```
No '-o' specification is OK.
How can I save my detection result?

**Comment by anzhella-pankratova** [comment]
Hello @cosmos1982,
The OpenCV documentation says "**Use uncompressed image format (eg. img_%02d.BMP) to save raw frames.**"
So you can modify the command-line parameter like this: `-o C:\Work\tmp\car_result_%d.bmp`
The same way you can save the results for folder of images.

**Comment by cosmos1982** [comment]
@anzhella-pankratova , pefect, that resolve my problem! I strongly suggest adding this description in help messages so that we can find the '-o' usage easily.

**Comment by anzhella-pankratova** [comment]
Thank you for your feedback, @cosmos1982! The description of `--output` is actually not clear enough and does not cover usage cases, so we are going to expand it.

**Comment by vladimir-dudnik** [comment]
`-o` parameter description was updated in PR #2455, hope this helps

**Comment by vladimir-dudnik** [comment]
2021.4 release published, so closing this
