### ISSUE TITLE
How to change the window size

### ISSUE THREAD

**Issue by dengyoyo** [openvinotoolkit/open_model_zoo#2359]
<img width="546" alt="超出" src="https://user-images.githubusercontent.com/83382997/116494608-bc8f3600-a8d3-11eb-85dc-f5c9dcd1becb.png">

How to modify the window size?
please help me

**Comment by vladimir-dudnik** [comment]
@dengyoyo we introduce `--output_resolution` option for demos in this [PR-2315](https://github.com/openvinotoolkit/open_model_zoo/pull/2315), which is merged to `develop` branch. This option was not implemented in 2021.3 release

**Comment by vladimir-dudnik** [comment]
@dengyoyo is this answers your question?

**Comment by dengyoyo** [comment]
> @dengyoyo這是回答你的問題嗎？

Yes thanks

**Comment by vladimir-dudnik** [comment]
@dengyoyo thanks for update, I'll close this once 2021.4 release happens

**Comment by vladimir-dudnik** [comment]
2021.4 release published, so closing this
