### ISSUE TITLE
Issue with releasing Neural Compute Stick 2 (MYRIAD) resources programmatically while using async_pipeline.h

### ISSUE THREAD

**Issue by saifvazir** [openvinotoolkit/open_model_zoo#2364]
Environment: OpenVINO 2021.2.185
Device: Neural Compute Stick 2
I'm trying to create an application in C++ using the async pipeline-based code followed in object_detection_demo.exe. I'm facing an issue where the NCS2 resource is not being released correctly which results in `Can not init Myriad device: NC_ERROR` when I try to use NCS2 in the same process but for a different model configuration. I'm following the same steps as used in the object_detection_demo.exe. I've also tried setting the `MYRIAD_ENABLE_FORCE_RESET` to "YES", but that doesn't work either.
Ways to reproduce the error:
1. Run object_detection_demo.exe with NCS2 in quick succession.
2. Run segmentation_demo_async.exe with NCS2 in quick succession.

Both of these examples use the async_pipeline based code. Here is a reference to the [Intel Community forum post](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/OpenVINO-Issue-with-releasing-NCS2-resources-programmatically/m-p/1277473/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufEtPMjFPTTM4TTdTQlE2fDEyNzc0NzN8U1VCU0NSSVBUSU9OU3xoSw#M23675) which contains a detailed explanation for this error and a potential bug in the pipeline/requests pool codebase.
Attaching logs of object_detection_demo.exe when run in quick succession.
[logs.txt](https://github.com/openvinotoolkit/open_model_zoo/files/6398972/logs.txt)
Ref for the issue: @vladimir-dudnik.

**Comment by vladimir-dudnik** [comment]
@saifvazir thanks for submitting, we are working on this

**Comment by vladimir-dudnik** [comment]
@saifvazir We've created PR https://github.com/openvinotoolkit/open_model_zoo/pull/2375 to work on solution

**Comment by saifvazir** [comment]
Hey @vladimir-dudnik, I tried using the solution posted in PR #2375 , but now the demos won't work at all. I'm trying this with openvino 2021.2.185. Can you confirm the same?

**Comment by saifvazir** [comment]
Hey @vladimir-dudnik, I tried using the solution posted in PR #2375, but that doesn't seem to solve the problem, instead now the demos won't work at all. ^tested with openvino 2021.2.185, can you confirm this?

**Comment by vladimir-dudnik** [comment]
@saifvazir what are the symptoms?

**Comment by saifvazir** [comment]
@vladimir-dudnik  Sorry for not including the logs before: ```C:\Users\saif\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release>object_detection_demo.exe -i "C:\Users\saif\Downloads\test.mp4" -m "C:\Users\saif\Downloads\person-detection-0200.xml" -at ssd -d MYRIAD
[ INFO ] InferenceEngine:       API version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Loading Inference Engine
[ INFO ] Device info:
[ INFO ]        MYRIAD
        myriadPlugin version ......... 2.1
        Build ........... 2021.2.0-1877-176bdf51370-releases/2021/2
Loading network files
[ INFO ] Batch size is forced to 1.
[ INFO ] Checking that the inputs are as the demo expects
[ INFO ] Checking that the outputs are as the demo expects
[ INFO ] Loading model to the device```

This is all that happens, the program exits after this.

**Comment by vladimir-dudnik** [comment]
@saifvazir I'm worrying how do you get this build of demo with our latest fix? The develop branch from OMZ should not be able to build with OpenVINO 2021.2 environment, due to incompatible changes in API, introduced in develop branch and targeted for 2021.4 release. Have you back-ported these changes to 2021.2 version of demo?

**Comment by vladimir-dudnik** [comment]
@saifvazir have you got any progress on this?

**Comment by saifvazir** [comment]
Hey @vladimir-dudnik, sorry for not being responsive earlier, I tried cherry-picking the commit onto 2021.2 and 2021.3 releases and then build the object detection demo. The build goes through successfully but the demo fails. I will try building openvino from the master branch and check if the demo works then or not.
