### ISSUE TITLE
several model download links are invalid (HTTP 404)

### ISSUE THREAD

**Issue by AvenSun** [openvinotoolkit/open_model_zoo#2448]
```
face-recognition-resnet34-arcface
ssh-mxnet
face-recognition-mobilefacenet-arcface
face-recognition-resnet50-arcface
retinaface-resnet50
face-recognition-resnet100-arcface
resnest-50-pytorch
retinaface-anti-cov
```

links are reported not found (404) as follows 
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/yp7y6jic464l09z/model-r34-arcface-ms1m-refine-v1.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/ou8v3c307vyzawc/model-r50-arcface-ms1m-refine-v1.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/akxeqp99jvsd6z7/model-MobileFaceNet-arcface-ms1m-refine-v1.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/06zmchmq4iwj6rt/ssh-model-final.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/53ftnlarhyrpkg2/retinaface-R50.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/tj96fsm6t6rq8ye/model-r100-arcface-ms1m-refine-v2.zip
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.dropbox.com/s/dl/6rhhxsbh2qik65k/cov2.zip
```
another one is 403 after changing some networks 

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://s3.us-west-1.wasabisys.com/resnest/resnest50-528c19ca.pth`

**Comment by vladimir-dudnik** [comment]
@AvenSun that's right, models were removed by its authors from dropbox, which allow anonymous download and still available on baidu drive only, which require authorization, so now they can't be automatically downloaded by Open Model Zoo tools. That is why we are going to remove those models from OMZ for the next release, see related PR #2386.

There are several issues reported on original repository, will see if downloads restore before we freeze code for 2021.4 release
https://github.com/deepinsight/insightface/issues/1516
https://github.com/deepinsight/insightface/issues/1504
https://github.com/deepinsight/insightface/issues/1480
https://github.com/deepinsight/insightface/issues/1543
https://github.com/deepinsight/insightface/issues/1535
https://github.com/deepinsight/insightface/issues/1533

**Comment by AvenSun** [comment]
@vladimir-dudnik 
I got it ! thank you.
