### ISSUE TITLE
the wrong result of formula recognition

### ISSUE THREAD

**Issue by shixinlishixinli** [openvinotoolkit/open_model_zoo#2480]
i try to use '/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/formula_recognition_demo/python', but  the result of this demo is wrong.

python3 formula_recognition_demo.py -m_encoder ~/open_model_zoo/tools/downloader/intel/formula-recognition-polynomials-handwritten-0001/formula-recognition-polynomials-handwritten-0001-encoder/FP32/formula-recognition-polynomials-handwritten-0001-encoder.xml -m_decoder ~/open_model_zoo/tools/downloader/intel/formula-recognition-polynomials-handwritten-0001/formula-recognition-polynomials-handwritten-0001-decoder/FP32/formula-recognition-polynomials-handwritten-0001-decoder.xml --vocab_path /opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/./models/intel/formula-recognition-polynomials-handwritten-0001/vocab.json -i ./sample.png -o ~/test/aa

the result is ./sample.png    1 1 1 w ^ { 1 } + 7 . 1 9 o ^ { 1 } - 6 - 0 . 9 6 r ^ { 1 } y
but the right result is             474w ^ { 1 } + 7 . 1 9 o ^ { 1 } - 6 - 0 . 9 6 L ^ { 1 } y

by the way , i only can get the result of sample.png ,  i try to infer other picture, there is a bug of openCV
Traceback (most recent call last):
  File "formula_recognition_demo.py", line 309, in <module>
    sys.exit(main() or 0)
  File "formula_recognition_demo.py", line 277, in main
    model_input = prerocess_crop(bin_crop, (height, width), preprocess_type=args.preprocessing_type)
  File "/opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/formula_recognition_demo/python/utils.py", line 115, in prerocess_crop
    crop = cv.cvtColor(crop, cv.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.5.2-openvino) ../opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

best
lisa Shi

**Comment by shixinlishixinli** [comment]
i have found out why my result is wrong, because i use wrong weight , but when i try to use my own picture there is the same error

**Comment by vladimir-dudnik** [comment]
@shixinlishixinli could you please attach your picture, which gives the wrong result?

**Comment by vladimir-dudnik** [comment]
@shixinlishixinli have you solved your issue?

**Comment by vladimir-dudnik** [comment]
closing as not active. feel free to reopen in case still not solved
