### ISSUE TITLE
Unable to run interactive_face_detection_demo_gapi

### ISSUE THREAD

**Issue by architlfc** [openvinotoolkit/open_model_zoo#2484]
Hi,

I have run build.sh , but on trying :
./interactive_face_detection_demo_gapi -h
Im getting an error : bash: ./interactive_face_detection_demo_gapi: No such file or directory
How do i run this demo ?

**Comment by vladimir-dudnik** [comment]
@architlfc have you build demo before trying to run it? Please take a look on instructions of how to build OMZ demo either here, on [github](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/README.md#build-the-demo-applications) or within OpenVINO online [documentation](https://docs.openvinotoolkit.org/latest/omz_demos.html).

**Comment by architlfc** [comment]
Hi @vladimir-dudnik ,
Yes i have followed the documentation.
While running build.sh i see 
[ 42%] Built target interactive_face_detection_demo_gapi  aswell.

Im trying this on my local system aswell as a docker container on a remote server. Facing the same issue in both places.

**Comment by vladimir-dudnik** [comment]
@architlfc If you are looking for help, could you please provide more detailed info, on what you try to do, how you did that, what is version of OpenVINO, what is OS, and so on. It is difficult to guess what might be wrong in your case. OMZ demos were successfully validated on supported OS/platforms. Could you please attach a log from build on your system?

**Comment by architlfc** [comment]
The issue is resolved . I was running it from the demos directory  instead of <path_to_build_directory>/intel64/Release/ . 
Thanks for helping out @vladimir-dudnik . Il be closing the issue.
