### ISSUE TITLE
Image Segmentation Python Demo - Documentation Issue

### ISSUE THREAD

**Issue by dtischler** [openvinotoolkit/open_model_zoo#2566]
It appears that the `-at` flag is not present / available in the `segmentation_demo.py` command for the Image Segmentation Python Demo.

Trying to run the command with it results in an error as such:

```
root@3c53548:/usr/src/app# python3 /opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/segmentation_demo/python/segmentation_demo.py -i /dev/video0 -m /opt/intel/openvino_2021.3.394/deployment_tools/open_model_zoo/demos/models/intel/semantic-segmentation-adas-0001/FP32/semantic-segmentation-adas-0001.xml -d CPU -at segmentation
/opt/intel/openvino_2021.3.394/python/python3.8/ngraph/utils/types.py:37: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (NgraphType.boolean, np.bool),
usage: segmentation_demo.py [-h] -m MODEL -i INPUT [-d DEVICE] [-c COLORS] [-nireq NUM_INFER_REQUESTS]
                            [-nstreams NUM_STREAMS] [-nthreads NUM_THREADS] [--loop] [-o OUTPUT]
                            [-limit OUTPUT_LIMIT] [--no_show] [-u UTILIZATION_MONITORS]
segmentation_demo.py: error: unrecognized arguments: -at segmentation
``` 

The usage here make reference to it, though:  https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/segmentation_demo/python#running

So, just need to update to docs to remove that reference, I suppose.

**Comment by eaidova** [comment]
Hi @dtischler 
Probably, you use old demo version, this key was introduced in 2021.4 openvino release. If you look inside the code, you can see that flag presents in argument parser now
https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/segmentation_demo/python/segmentation_demo.py#L110
So documentation in the repo is correspond to demo version provided in repo

**Comment by eaidova** [comment]
As I can see from the logs, you use openvino 2021.3 package.
[Here](https://docs.openvinotoolkit.org/2021.3/omz_demos_segmentation_demo_python.html) you can find segmentation demo documentation which correspond to your package version, it does not contain this key.

**Comment by dtischler** [comment]
AHA!  Thanks for the great find @eaidova!  Yes, I pull in 2021.3.394 in my Dockerfile, it was the most current version when I wrote it.  I now see that 2021.4.582 is sitting in the `apt` repo.  I will update my Dockerfile and pull in the newer version, and that should solve my issue.  Thanks!

**Comment by dtischler** [comment]
Worked perfect, thanks!
