### ISSUE TITLE
Error when converting YoloV4 model using the converter

### ISSUE THREAD

**Issue by likholat** [openvinotoolkit/open_model_zoo#2571]
Trying to convert YoloV4 model to IR using `converter.py`:
```
python3 /home/open_model_zoo/tools/downloader/converter.py --name yolo-v4-tf --mo /opt/intel/openvino/deployment_tools/model_optimizer/mo.py
```
But get the error:
```
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/open_model_zoo/public/yolo-v4-tf/yolo-v4.savedmodel is not a directory
Traceback (most recent call last):
  File "/home/open_model_zoo/models/public/yolo-v4-tf/pre-convert.py", line 40, in <module>
    main()
  File "/home/open_model_zoo/models/public/yolo-v4-tf/pre-convert.py", line 36, in main
    ], check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '--', '/home/open_model_zoo/public/yolo-v4-tf/keras-YOLOv3-model-set/tools/model_converter/convert.py', '/home/open_model_zoo/public/yolo-v4-tf/keras-YOLOv3-model-set/cfg/yolov4.cfg', '/home/open_model_zoo/public/yolo-v4-tf/yolov4.weights', '/home/open_model_zoo/public/yolo-v4-tf/yolo-v4.savedmodel', '--yolo4_reorder']' returned non-zero exit status 1.

FAILED:
yolo-v4-tf
```

**Comment by eaidova** [comment]
@likholat could you please specify which python and tensorflow version do you use?

**Comment by eaidova** [comment]
@likholat
I can not reproduce this locally, so probably it is an issue in your environment.
Usually this error means that you try to use tf < 2 for model in saved_model format for tf2 and higher.
Please pay attention on model downloader requirements https://github.com/openvinotoolkit/open_model_zoo/blob/develop/tools/downloader/requirements-tensorflow.in
and try to convert with correct tf version

**Comment by likholat** [comment]
@eaidova 
Now my TF version is 2.4.1(was 2.2.0), but it still doesn't work

**Comment by vladimir-dudnik** [comment]
@likholat You've closed the issue, so seems yo solved the problem? If someone will look for yolo-v4 related issues it might be not clear if you close the issue because simple decode to stop work with yolo-v4 model or you have find and solved problem.

**Comment by eaidova** [comment]
@vladimir-dudnik we internally discussed issue. The issue connected with running downloader and converter from different release versions.
in 2021.4 we migrate on usage saved model instead keras h5 format to simplify model conversion. It made downloader postprocessing from 2021.3 is not compatible with pre-convert script in 2021.4.
