### ISSUE TITLE
person-vehicle-bike-detection-2004 model can not be load with latest opencv dldt 2021.4

### ISSUE THREAD

**Issue by fuatka** [openvinotoolkit/open_model_zoo#2580]
I'm using OpenVINO models with opencv dldt support. person-vehicle-bike-detection-2004 model input resolution is widescreen format what I was looking for. Still fast and mAP result looks great.

But I can not load this model with opencv-4.5.3-dldt-2021.4 using readNet function!
This model based on MobileNetV2 backbone with ATSS, different than other person-vehicle-bike-detection models backbone.

There is no issue with person-vehicle-bike-detection-2000, person-vehicle-bike-detection-2001, person-vehicle-bike-detection-2002

**Comment by vladimir-dudnik** [comment]
@fuatka that is possible issue with OpenCV DNN, but you should be still able to use model directly with OpenVINO, is not it? You may try Open Model Zoo Python [object_detection_demo](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/object_detection_demo/python/README.md) to see how model work with OpenVINO directly.

@alvoron please look at this issue from OpenCV point of view

**Comment by alvoron** [comment]
@fuatka thank you for raising the issue. OpenCV team will try to reproduce it and come back with some updates.

**Comment by AvenSun** [comment]
@alvoron 

#opencv/opencv/issues/20380 some related problem
can not get correct result via OpenCv DNN with some OpenVINO models

**Comment by alalek** [comment]
There are 2 issues of OpenCV DNN module:
- 1D layouts. OpenCV uses Mat internally which supports 2D+ layouts only (1D is forced as 2D).
- OpenCV DNN module supports FP32 output only. See 'labels' layout. It is with `I32` precision. OpenCV DNN tries to reconfigure output precision [here](https://github.com/opencv/opencv/blob/4.5.3/modules/dnn/src/ie_ngraph.cpp#L603), but looks like this doesn't work anymore. Exception message is:
  `[ PARAMETER_MISMATCH ] Failed to set output blob with precision: FP32, if CNNNetwork output blob precision is: I32`

**Comment by alalek** [comment]
> with opencv-4.5.3-dldt-2021.4

Could you try OpenCV build of that package from [here](
http://pullrequest.opencv.org/buildbot/export/opencv_releases/precommit_custom_windows/20210716-120313--2492/)?
(it is built for PR https://github.com/opencv/opencv/pull/20423 which includes PR with fix: https://github.com/opencv/opencv/pull/20410 )

**Comment by fuatka** [comment]
I tried this build with opencv dnn object_detection.cpp [sample code](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp)

This time model loaded successfully, these are output layers names,
TopK_1123.0
TopK_1339.0
TopK_1555.0
TopK_1829.0
TopK_691.0
TopK_907.0
boxes
labels

But object_detection.cpp doesn't have output layer support except from DetectionOutput and Region. So I get "Unknown output layer type: TopK" error at [line](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L403)

Before that I also get some warnings at [line](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L292)
net.forward(outs, outNames);

[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1123.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1339.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1555.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1829.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_691.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_907.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (969) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong precision: FP32 => I32  ndims=1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong dims: 2 => 1

**Comment by fuatka** [comment]
I tried this precommit build with opencv dnn object_detection.cpp sample code.

This time previous exception `[ PARAMETER_MISMATCH ] Failed to set output Blob. Dimensions mismatch`  doesn't occured, but get some warnings at the same [line](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L292)

```
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1123.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1339.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1555.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1829.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_691.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_907.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (969) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong precision: FP32 => I32 ndims=1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong dims: 2 => 1
```

Another issue is object_detection.cpp doesn't have output layer support except from DetectionOutput and Region. So I get "Unknown output layer type: TopK" error at [line](https://github.com/opencv/opencv/blob/master/samples/dnn/object_detection.cpp#L403)

**Comment by AvenSun** [comment]
@alalek 
I tried the package downloaded from the link above via python.
for example [person-vehicle-bike-detection-2004](https://docs.openvinotoolkit.org/latest/omz_models_model_person_vehicle_bike_detection_2003.html)

`dnn = cv2.dnn.Net_readFromModelOptimizer(xml, bin)`

we will get output names via 

`outputNames = dnn.getUnconnectedOutLayersNames()`

====outputNames====
['TopK_1123.0', 'TopK_1339.0', 'TopK_1555.0', 'TopK_1829.0', 'TopK_691.0', 'TopK_907.0', 'boxes', 'labels']
====outputNames====

then if we pass the outputNames to forward 

```
blob = cv2.dnn.blobFromImage(frame, 1.0, size, swapRB=False, crop=False)
net.setInput(blob)
outs = net.forward(outputNames)
```
generally it works now , but with same warnings 

```
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1123.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1339.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1555.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_1829.0' blob
 due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_691.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'TopK_907.0' blob
due to wrong dims: 2 => 1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (969) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong precision: FP32 => I32  ndims=1
[ WARN:0] global C:\build\precommit_custom_windows\opencv\modules\dnn\src\ie_ngr
aph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due
to wrong dims: 2 => 1

```

as I mentioned in issue opencv/opencv/issues/20380

though we got 8 outputNames,  the [document page ](https://docs.openvinotoolkit.org/latest/omz_models_model_person_vehicle_bike_detection_2003.html)just lists **boxes and lables**
actually we just need these two to get the result
