### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by diego-varela-seijas** [openvinotoolkit/open_model_zoo#2589]
Hi,

I need to do inference on a Raspberry Pi 4B with NCS 2 using YOLO. I get the default model in IR (the xml and the bin file) before converting custom models to try, and used two demos of open_model_zoo but I always get a Segmentation fault error. Here are the outputs:

Command
`./multi_channel_object_detection_demo_yolov3 -m ../../../build/frozen_darknet_yolov3_model.xml -d MYRIAD -i ../../../build/cars.mp4`

Output:
`
[ INFO ] InferenceEngine:     IE version ......... 2021.4
    Build ........... 0
[ INFO ] Parsing input parameters
[ INFO ]     Detection model:           ../../../build/frozen_darknet_yolov3_model.xml
[ INFO ]     Detection threshold:       0.5
[ INFO ]     Utilizing device:          MYRIAD
[ INFO ]     Batch size:                1
[ INFO ]     Number of infer requests:  5
[ INFO ] Model   path: ../../../build/frozen_darknet_yolov3_model.xml
Segmentation fault
`

Command
`./object_detection_demo -m ../../../build/frozen_darknet_yolov3_model.xml -d MYRIAD -i ../../../build/cars.mp4 -at yolo`

Output:
`[ INFO ] InferenceEngine:     IE version ......... 2021.4
    Build ........... 0
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (1044) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global ../opencv/modules/videoio/src/cap_gstreamer.cpp (1081) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
[ INFO ] Loading Inference Engine
[ INFO ] Device info: 
[ INFO ]     MYRIAD
    myriadPlugin version ......... 2021.4
    Build ........... 0
Loading network files
[ INFO ] Batch size is forced to 1.
[ INFO ] Checking that the inputs are as the demo expects
[ INFO ] Checking that the outputs are as the demo expects
[ INFO ] Loading model to the device
Segmentation fault
`

I don't know what could be the error or how to fix it. If anyone knows another way to do inference with YOLO on a Raspberry with the NCS it would be also good.

Thanks in advance

**Comment by vladimir-dudnik** [comment]
@alvoron @terfendail could you please look at the issue?

**Comment by alvoron** [comment]
@diego-varela-seijas thank you for raising the issue. We will try to reproduce it at the nearest time.
The cause of segmentation fault is often related to model size. Did you consider to try tiny version of YOLO?

**Comment by diego-varela-seijas** [comment]
The version was already YOLOv3 tiny

**Comment by alvoron** [comment]
@diego-varela-seijas did you build OMZ demo `multi_channel_object_detection_demo_yolov3` on Raspberry Pi?

**Comment by diego-varela-seijas** [comment]
Yes, the only step I didn't do on RPi was converting the model to .xml and .bin.

**Comment by alvoron** [comment]
@diego-varela-seijas could you try to add `-DCMAKE_CXX_FLAGS="-march=armv7-a"` to `cmake` command when you build OMZ demo?

**Comment by diego-varela-seijas** [comment]
Adding that made it work. Thank you!!
