### ISSUE TITLE
Python-demo Error : ModuleNotFoundError: No module named 'models' .etc

### ISSUE THREAD

**Issue by Hnnuliulei123456** [openvinotoolkit/open_model_zoo#2662]
Demo : open_model_zoo/demos/human_pose_estimation_demo/python/human_pose_estimation_demo.py
Openvino version : l_openvino_toolkit_runtime_raspbian_p_2021.2.185
Device : RaspberryPi+Intel NCS2

In the demo, it need import many modules like:
import models
import monitors
from images_capture import open_images_capture
from pipelines import get_user_config, AsyncPipeline
from performance_metrics import PerformanceMetrics
from helpers import resolution

Because there is no human_pose_estimation_demo of python in this openvino install package, I download it in open_model_zoo.
But when I run it in my RaspberryPi, there many errors like: No module named 'models', 'monitors', 'images_capture'.etc. And I can not find these module's file in openvino install package.

I don't know why and which version of openvino install package can be used. Thanks.

**Comment by vladimir-dudnik** [comment]
@Hnnuliulei123456 I would recommend to install the latest OpenVINO 2021.4 package if you need Python human pose estimation demo

**Comment by Hnnuliulei123456** [comment]
> @Hnnuliulei123456 I would recommend to install the latest OpenVINO 2021.4 package if you need Python human pose estimation demo

@vladimir-dudnik Thank you for you reply. But in the version latest OpenVINO 2021.4 package, there is no Python human pose estimation_2D demo. I don't want the 3D demo, I just want the 2D demo.

**Comment by vladimir-dudnik** [comment]
@Hnnuliulei123456 Really? Python human_pose_estimation_demo is part of OpenVINO 2021.4 Open Model Zoo, see [description](https://docs.openvinotoolkit.org/latest/omz_demos_human_pose_estimation_demo_python.html). I also see this in my Windows OpenVINO installation.

**Comment by Hnnuliulei123456** [comment]
> @Hnnuliulei123456 Really? Python human_pose_estimation_demo is part of OpenVINO 2021.4 Open Model Zoo, see [description](https://docs.openvinotoolkit.org/latest/omz_demos_human_pose_estimation_demo_python.html). I also see this in my Windows OpenVINO installation.

@vladimir-dudnik Thanks. Yes, I find it in the latest Windows OpenVINO installation. But I can't get the latest RaspberryPi OpenVINO install package (may be also the 2021.4 version), because I can't open the [official link](https://storage.openvinotoolkit.org/repositories/openvino/packages/ ). Is there other way I can get it？

**Comment by vladimir-dudnik** [comment]
@Hnnuliulei123456 you should be able to register and download OpenVINO package from [software.intel.com](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html) site.

**Comment by Hnnuliulei123456** [comment]
> @Hnnuliulei123456 you should be able to register and download OpenVINO package from [software.intel.com](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html) site.

@vladimir-dudnik Thanks. In the [software.intel.com](https://software.intel.com/content/www/us/en/develop/tools/openvino-toolkit/download.html) site, there is only five kinds of package version (Windows, Windows(FPGA), macOS, Linux and Linxu(FPGA)), which one can I use for RaspberryPi.

**Comment by Hnnuliulei123456** [comment]
> @Hnnuliulei123456 seems you are right, OpenVINO RaspberryPi install package is not available through software.intel.com. Do you know why you can't open [official link](https://storage.openvinotoolkit.org/repositories/openvino/packages/)? I just check and was able to open this link.

> @vladimir-dudnik Thank you for your reply. I don's konw why I can't open [official link](https://storage.openvinotoolkit.org/repositories/openvino/packages/) , and I have tried on several computers. I may have to wait to download it on software.intel.com.

**Comment by vladimir-dudnik** [comment]
@Hnnuliulei123456 there is another opportunity, OpenVINO RaspberryPi package can be built through OpenVINO github version, there is no closed source component in it, everything is open sourced. Please look at [How to build](https://github.com/openvinotoolkit/openvino/wiki/BuildingForRaspbianStretchOS) instructions on github.

**Comment by vladimir-dudnik** [comment]
@Hnnuliulei123456 please follow official OpenVINO [documentation](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_raspbian.html#doxid-openvino-docs-install-guides-installing-openvino-raspbian) for RaspberryPi

**Comment by Hnnuliulei123456** [comment]
Thank you sir. I will continue to follow openvino's updates to Raspberry Pi. If you have something new to do, please also recommend it to me.


| |
13605545615
|
|
***@***.***
|
On 4/1/2022 21:16，Vladimir ***@***.***> wrote：

@Hnnuliulei123456 please follow official OpenVINO documentation for RaspberryPi
