### ISSUE TITLE
Questions regarding accuracy_checker

### ISSUE THREAD

**Issue by Rakshith2597** [openvinotoolkit/open_model_zoo#2708]
> If a model uses a dataset which is not supported by the Accuracy Checker, you also must provide the license and the link to it and mention it in the PR description.

1. Should we just provide the link to the dataset and its license? Or should we create a custom Accuracy Checker and provide the same as well?
2. If we are to create a custom accuracy checker. Are there any guidelines for the same? In the documentation, only guidelines to use existing checkers is specified.

In the documentation, it is mentioned that 
> Convert annotation of your dataset. Use one of the converters from annotation-converters, or **write your own** if there is no converter for your dataset. You can find detailed instructions on how to use converters in the Annotation Conversion Guide.

3. Are there any guidelines for writing our own converter for the dataset?
4. The annotation provided in our dataset can be converted to [DatasetFolder ](https://pytorch.org/vision/stable/datasets.html#datasetfolder) format. If I do so, I assume I can use the ` cls_dataset_folder - converts generic classification dataset with DatasetFolder format to ClassificationAnnotation.` Where should I provide the pre-processing script to convert the annotation to DatasetFolder format?

More details regarding the dataset and model I intent to contribute can be found at PR #2345

**Comment by vladimir-dudnik** [comment]
@eaidova FYI

**Comment by Rakshith2597** [comment]
@vladimir-dudnik @eaidova It's been a few months, Any updates on this?

**Comment by vladimir-dudnik** [comment]
@Rakshith2597 we've aligned OMZ branching strategy with OpenVINO and so, deleted `develop` branch (this cause to close your PR). Please reopen and retarget your PR to `master` branch
