### ISSUE TITLE
Transfer MRI reconstruction demo to AsyncPipeline API

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/open_model_zoo#2718]
demo: https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/mri_reconstruction_demo

example: https://github.com/openvinotoolkit/open_model_zoo/pull/2178

- [ ] AsyncPipeline
- [x] Add description for inputs and outputs in the README https://github.com/openvinotoolkit/open_model_zoo/pull/2770

**Comment by dwipddalal** [comment]
Is this issue still open? I would like to work on this.

**Comment by dkurt** [comment]
@dwipddalal, yes, it's still open.

**Comment by vladimir-dudnik** [comment]
@dwipddalal welcome to OMZ contributors, can I assign this PR to you?

**Comment by dwipddalal** [comment]
Yes Please assign it to me. I would love to work on it.

**Comment by dwipddalal** [comment]
Can you also please share some resources that can help me to get started with it?

**Comment by vladimir-dudnik** [comment]
@dwipddalal sure, what resources do you mean? Are you asking about OpenVINO API and Open ModelZoo Model API details?

**Comment by dwipddalal** [comment]
Yes I am asking about OpenVINO API and Open ModelZoo Model API details.

**Comment by dkurt** [comment]
I think AsyncPipeline os something expected in Python demo. I also have an example by using it in a different deom: https://github.com/openvinotoolkit/open_model_zoo/pull/2178 (please note that something could be changed)
