### ISSUE TITLE
How to use INT8 for IR

### ISSUE THREAD

**Issue by llxingkongxia** [openvinotoolkit/open_model_zoo#2726]
Hi
I want to use INT8 to inference.
In demo_squeeznet_download_convert_run.sh, I change target_precision="FP32" to "FP32-INT8" , but can,t convert.  "========== Skipping squeezenet1.1 (all conversions skipped)"
Please help to tell me how to convert. 
Thanks.

**Comment by Aakash-kaushik** [comment]
Hi, take a look at the below link you might be able to figure something out.
https://docs.openvinotoolkit.org/latest/pot_compression_algorithms_quantization_default_README.html

there are two methods that i know first is with a config and then the DL workbench i think both require that you have an FP32 version available and a dataset which can be used for the conversion then you can use

```bash
pot -c <config_file>
```

to start the conversion.

**Comment by vladimir-dudnik** [comment]
for public Open Model Zoo models we do provide an auxiliary scripts which simplify downloading, convertion to IR and quantization some of public models. Note, you will need to download validation datasets for models, see OMZ scripts [description](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/README.md) for more details.

**Comment by vladimir-dudnik** [comment]
closing this as resolved
