### ISSUE TITLE
Conversion for PSPNet-pytroch not working

### ISSUE THREAD

**Issue by Aakash-kaushik** [openvinotoolkit/open_model_zoo#2746]
### Commands I ran

```bash
python3 /opt/intel/openvino_2021.4.582/deployment_tools/open_model_zoo/tools/downloader/downloader.py --name pspnet-pytorch

python3 /opt/intel/openvino_2021.4.582/deployment_tools/open_model_zoo/tools/downloader/converter.py --name pspnet-pytorch
```
### Error
The download part was successful but the conversion gave the following error: 

```bash
========== Converting pspnet-pytorch to ONNX
Conversion to ONNX command: /usr/bin/python3 -- /opt/intel/openvino_2021.4.582/deployment_tools/open_model_zoo/tools/downloader/src/open_model_zoo/model_tools/internal_scripts/pytorch_to_onnx.py --model-path=/opt/intel/openvino_2021.4.582/deployment_tools/open_model_zoo/models/public/pspnet-pytorch --model-path=/home/aakash/public/pspnet-pytorch/models --model-path=/home/aakash/public/pspnet-pytorch/models/addict --model-path=/home/aakash/public/pspnet-pytorch/models/mmcv-1.2.0 --model-name=PSPNet --import-module=model '--model-param=weights_path=r"/home/aakash/public/pspnet-pytorch/pspnet_r50-d8_512x512_20k_voc12aug_20200617_101958-ed5dfbd9.pth"' '--model-param=config_path=r"/home/aakash/public/pspnet-pytorch/models/configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py"' --input-shapes=1,3,512,512 --input-names=input.1 --output-names=segmentation_map --output-file=/home/aakash/public/pspnet-pytorch/pspnet_r50-d8.onnx

ERROR: Module model contains no class or function with name PSPNet!
'super' object has no attribute '_specify_ddp_gpu_num'

FAILED:
pspnet-pytorch
```

### System info:

ubuntu: `21.04`
Openvino version: `2021.4.582`

**Comment by vladimir-dudnik** [comment]
@Aakash-kaushik how did you initialize your python environment?

**Comment by Aakash-kaushik** [comment]
Hi @vladimir-dudnik,
It wasn't in an environment it's my base python installation.

**Comment by vladimir-dudnik** [comment]
even if you do not create virtual environment you have to install python dependencies, required by OpenVINO model optimizer, in order to be able to convert model.

**Comment by Aakash-kaushik** [comment]
@vladimir-dudnik i forgot to mention this but i have used the exact same method to convert other models from which some were from tensorflow and some were from PyTorch and they worked perfectly fine.
So that leaves me with this model which I can't go forward with and i can assure that i do have the required libs to make conversions but not sure if this model requires something different.

**Comment by vladimir-dudnik** [comment]
@Aakash-kaushik starting from OpenVINO 2021.4 there is more convenient way to initialize required Python environment. Please see [documentation](https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_pip.html) for openvino-dev package distribution through PyPi. Basically, you will need to run command like:
pip install openvino-dev[pytorch,onnx]
to install required python dependencies. After that downloading and conversion of OMZ models will be as simple as:
omz_downloader --name pspnet-pytorch
omz_converter --name pspnet-pytorch

Note on supported Python versions from the package [page](https://pypi.org/project/openvino-dev/)

**Comment by vladimir-dudnik** [comment]
@Aakash-kaushik just tested on Windows with OpenVINO 2021.4 openvino-dev PyPi package

(py3.7-openvino-2021.4) c:\Temp>omz_downloader --name pspnet-pytorch -o c:\temp\models-exp
################|| Downloading pspnet-pytorch ||################

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\pspnet_r50-d8_512x512_20k_voc12aug_20200617_101958-ed5dfbd9.pth
... 100%, 191613 KB, 966 KB/s, 198 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\configs\pspnet\pspnet_r50-d8_512x512_20k_voc12aug.py
... 100%, 0 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\configs\_base_\models\pspnet_r50-d8.py
... 100%, 1 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\configs\_base_\datasets\pascal_voc12_aug.py
... 100%, 0 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\configs\_base_\datasets\pascal_voc12.py
... 100%, 1 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\configs\_base_\default_runtime.py
... 100%, 0 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\mmsegmentation-0.11.0-py3-none-any.whl
... 100%, 143 KB, 209 KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\addict-2.4.0-py3-none-any.whl
... 100%, 3 KB, ? KB/s, 0 seconds passed

========== Downloading c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0.tar.gz
... 100%, 236 KB, 503 KB/s, 0 seconds passed

========== Unpacking c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0.tar.gz
========== Unpacking c:\temp\models-exp\public\pspnet-pytorch\models\addict-2.4.0-py3-none-any.whl
========== Unpacking c:\temp\models-exp\public\pspnet-pytorch\models\mmsegmentation-0.11.0-py3-none-any.whl
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\configs\pspnet\pspnet_r50-d8_512x512_20k_voc12aug.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmseg\models\backbones\__init__.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmseg\models\backbones\__init__.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmseg\models\decode_heads\__init__.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmseg\models\decode_heads\__init__.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0\mmcv\utils\config.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0\mmcv\__init__.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0\mmcv\utils\env.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0\mmcv\cnn\bricks\plugin.py
========== Replacing text in c:\temp\models-exp\public\pspnet-pytorch\models\mmcv-1.2.0\mmcv\utils\config.py


(py3.7-openvino-2021.4) c:\Temp>omz_converter --name pspnet-pytorch -o c:\temp\models-exp -d c:\temp\models-exp
========== Converting pspnet-pytorch to ONNX
Conversion to ONNX command: c:\miniconda3\envs\py3.7-openvino-2021.4\python.exe -- c:\miniconda3\envs\py3.7-openvino-2021.4\lib\site-packages\open_model_zoo\model_tools\internal_scripts\pytorch_to_onnx.py --model-path=C:\Miniconda3\envs\py3.7-openvino-2021.4\Lib\site-packages\open_model_zoo\model_tools\models\public\pspnet-pytorch --model-path=c:\temp\models-exp\public\pspnet-pytorch/models --model-path=c:\temp\models-exp\public\pspnet-pytorch/models/addict --model-path=c:\temp\models-exp\public\pspnet-pytorch/models/mmcv-1.2.0 --model-name=PSPNet --import-module=model "--model-param=weights_path=r\"c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8_512x512_20k_voc12aug_20200617_101958-ed5dfbd9.pth\"" "--model-param=config_path=r\"c:\temp\models-exp\public\pspnet-pytorch/models/configs/pspnet/pspnet_r50-d8_512x512_20k_voc12aug.py\"" --input-shapes=1,3,512,512 --input-names=input.1 --output-names=segmentation_map --output-file=c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8.onnx

c:\temp\models-exp\public\pspnet-pytorch/models\mmseg\ops\wrappers.py:28: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  size = tuple(int(x) for x in size)
ONNX check passed successfully.

========== Converting pspnet-pytorch to IR (FP16)
Conversion command: c:\miniconda3\envs\py3.7-openvino-2021.4\python.exe -m mo --framework=onnx --data_type=FP16 --output_dir=c:\temp\models-exp\public\pspnet-pytorch\FP16 --model_name=pspnet-pytorch --input_shape=[1,3,512,512] --input=input.1 --mean_values=input.1[123.675,116.28,103.53] --scale_values=input.1[58.395,57.12,57.375] --input_model=c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8.onnx --reverse_input_channels

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8.onnx
        - Path for generated IR:        c:\temp\models-exp\public\pspnet-pytorch\FP16
        - IR output name:       pspnet-pytorch
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         input.1
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,512,512]
        - Mean values:  input.1[123.675,116.28,103.53]
        - Scale values:         input.1[58.395,57.12,57.375]
        - Scale factor:         Not specified
        - Precision of IR:      FP16
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       True
ONNX specific parameters:
        - Inference Engine found in:    c:\miniconda3\envs\py3.7-openvino-2021.4\lib\site-packages\openvino
Inference Engine version:       2021.4.0-3839-cd81789d294-releases/2021/4
Model Optimizer version:        2021.4.0-3839-cd81789d294-releases/2021/4
[ WARNING ]  Const node 'Resize_134/Add_input_port_1/value251914664' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_146/Add_input_port_1/value255114666' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_158/Add_input_port_1/value258314668' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_170/Add_input_port_1/value261514670' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_183/Add_input_port_1/value264714672' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Const node 'Resize_192/Add_input_port_1/value267914674' returns shape values of 'float64' type but it must be integer or float32. During Elementwise type inference will attempt to cast to float32
[ WARNING ]  Changing Const node 'Resize_134/Add_input_port_1/value251914812' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_170/Add_input_port_1/value261515052' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_158/Add_input_port_1/value258315262' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_146/Add_input_port_1/value255115106' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_183/Add_input_port_1/value264715091' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ WARNING ]  Changing Const node 'Resize_192/Add_input_port_1/value267915028' data type from float16 to <class 'numpy.float32'> for Elementwise operation
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: c:\temp\models-exp\public\pspnet-pytorch\FP16\pspnet-pytorch.xml
[ SUCCESS ] BIN file: c:\temp\models-exp\public\pspnet-pytorch\FP16\pspnet-pytorch.bin
[ SUCCESS ] Total execution time: 19.61 seconds.

========== Converting pspnet-pytorch to IR (FP32)
Conversion command: c:\miniconda3\envs\py3.7-openvino-2021.4\python.exe -m mo --framework=onnx --data_type=FP32 --output_dir=c:\temp\models-exp\public\pspnet-pytorch\FP32 --model_name=pspnet-pytorch --input_shape=[1,3,512,512] --input=input.1 --mean_values=input.1[123.675,116.28,103.53] --scale_values=input.1[58.395,57.12,57.375] --input_model=c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8.onnx --reverse_input_channels

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      c:\temp\models-exp\public\pspnet-pytorch/pspnet_r50-d8.onnx
        - Path for generated IR:        c:\temp\models-exp\public\pspnet-pytorch\FP32
        - IR output name:       pspnet-pytorch
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         input.1
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,512,512]
        - Mean values:  input.1[123.675,116.28,103.53]
        - Scale values:         input.1[58.395,57.12,57.375]
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       True
ONNX specific parameters:
        - Inference Engine found in:    c:\miniconda3\envs\py3.7-openvino-2021.4\lib\site-packages\openvino
Inference Engine version:       2021.4.0-3839-cd81789d294-releases/2021/4
Model Optimizer version:        2021.4.0-3839-cd81789d294-releases/2021/4
[ SUCCESS ] Generated IR version 10 model.
[ SUCCESS ] XML file: c:\temp\models-exp\public\pspnet-pytorch\FP32\pspnet-pytorch.xml
[ SUCCESS ] BIN file: c:\temp\models-exp\public\pspnet-pytorch\FP32\pspnet-pytorch.bin
[ SUCCESS ] Total execution time: 23.53 seconds.

**Comment by Aakash-kaushik** [comment]
Hi @vladimir-dudnik ,
Creating a new env and installing openvino-dev through pip made it work.
Thank You !
