### ISSUE TITLE
downloading some models from google drive failed

### ISSUE THREAD

**Issue by vladimir-dudnik** [openvinotoolkit/open_model_zoo#2764]
starting from Sep 14 2021 downloading of some models using OMZ downloader script failed. The root cause is that google drive start require login for these links and OMZ script, which load models in anonymous mode, is not able to download them. The list of affected models [below](http://213.221.44.203/job/omz/job/master/job/downloader_ubuntu18/375/console):
00:45:50  FAILED:
00:45:50  densenet-161
00:45:50  densenet-161-tf
00:45:50  mobilenet-ssd
00:45:50  se-inception
00:45:50  se-resnext-101
00:45:50  se-resnext-50
00:45:50  densenet-169
00:45:50  se-resnet-101
00:45:50  ssd512
00:45:50  densenet-201
00:45:50  ssd300
00:45:50  densenet-121
00:45:50  Sphereface
00:45:50  se-resnet-50
00:45:50  se-resnet-152

The whole picture for all OMZ models located at google drive looks like:

|model|anonymous downloading from google drive|
|------|-------------------------------------------------|
|anti-spoof-mn3|SUCCESS|
|brain-tumor-segmentation-0001|SUCCESS|
|brain-tumor-segmentation-0002|SUCCESS|
|cocosnet|SUCCESS|
|common-sign-language-0001|SUCCESS|
|ctdet_coco_dlav0_384|SUCCESS|
|ctdet_coco_dlav0_512|SUCCESS|
|deblurgan-v2|SUCCESS|
|densenet-121|FAIL|
|densenet-161|FAIL|
|densenet-161-tf|FAIL|
|densenet-169|FAIL|
|densenet-201|FAIL|
|f3net|SUCCESS|
|faceboxes-pytorch|SUCCESS|
|facenet-20180408-102900|SUCCESS|
|higher-hrnet-w32-human-pose-estimation|SUCCESS|
|mobilenet-ssd|FAIL|
|pelee-coco|SUCCESS|
|repvgg-a0|SUCCESS|
|repvgg-b1|SUCCESS|
|repvgg-b3|SUCCESS|
|retinaface-resnet50-pytorch|SUCCESS|
|rexnet-v1-x1.0|SUCCESS|
|se-inception|FAIL|
|se-resnet-101|FAIL|
|se-resnet-152|FAIL|
|se-resnet-50|FAIL|
|se-resnext-101|FAIL|
|se-resnext-50|FAIL|
|Sphereface|FAIL|
|ssd300|FAIL|
|ssd512|FAIL|
|text-recognition-resnet-fc|SUCCESS|
|vehicle-reid-0001|SUCCESS|
|yolact-resnet50-fpn-pytorch|SUCCESS|

**Comment by ekaakurniawan** [comment]
This is effecting Intel Edge AI Certification since the first practice uses mobilenet-ssd model.

**Comment by vladimir-dudnik** [comment]
@ekaakurniawan As a workaround you may manually download this model under being logged in to your google drive account, see this OpenVINO user's forum [thread](https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/Unable-to-download-ssd300-model-with-downloader-py/td-p/1315317) for details.

**Comment by vladimir-dudnik** [comment]
this has been resolved with OpenVNO 2021.4.2 release, so I'm closing the issue
