### ISSUE TITLE
How to use more than 1 batch_size to inference inputs

### ISSUE THREAD

**Issue by regainOWO** [openvinotoolkit/open_model_zoo#2832]
i am using Intel Pre-Trained Models named person-detection-retail-0013, i see the inputs shape is [1x3x320x544], when i use img shape like this ,  it works good, but i want to use mutiple_thread to get more camera frame together, i think more batch may be faster than one by one, so i give 2 batch ndarray to function parameter inputs as a test, and I get an error. Could you tell me openvino if or not speed more than 1 batch_size, how can I test it. wish you can reply me! thank you!

**Comment by vladimir-dudnik** [comment]
closing this as resolved
