### ISSUE TITLE
not able to not able to download using downloader.py models 

### ISSUE THREAD

**Issue by vinayg-intel** [openvinotoolkit/open_model_zoo#2853]
“CA certificate of the server where open model zoo 2021.3 is host storage.openvinotoolkit.org are  changed and the new certs are not valid/secured on the browser as cert verification fails”
We are not able to not able to download using downloader.py models from “intel/text-to-speech-en-0001/text-to-speech-en-0001-regression/FP32/* /model/”

**Comment by vladimir-dudnik** [comment]
@vinayg-intel issue fixed, please check on your side

**Comment by vladimir-dudnik** [comment]
close as resolved
