### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by 28anmol** [openvinotoolkit/open_model_zoo#2864]
Greetings!!

I am trying to run the models in open_model_zoo by installing the dependencies but I encountered the following error while running the command given on https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/downloader/README.md#prerequisites

(venv) anmolsingh@anmolsingh-VirtualBox:~/Desktop/pythonProject/DepthAIOAKD/open_model_zoo/tools/downloader$ python3 -mpip install anmolsingh -r ./requirements.in
ERROR: Could not find a version that satisfies the requirement anmolsingh (from versions: none)
ERROR: No matching distribution found for anmolsingh

It would be appreciated if anyone could help me solve this problem.

Regards,
Anmol.

**Comment by vladimir-dudnik** [comment]
@28anmol where did you see "-mpip install anmolsingh" command? It seems to be your user name...

`--user` pip option instruct pip install modules into users area.

BTW, starting from OpenVINO 2021.4 there is more convenient way to install all required python dependencies and OpenVINO tools with single command

pip install openvino-dev[caffe,caffe2,onnx,tensorflow2,pytorch,mxnet]

this will install all frameworks to convert all OMZ models

after it finish, you may call OMZ downloader just as command line tool - omz_downloader with the same options as in python downloader.py script

**Comment by vladimir-dudnik** [comment]
closing this as answered
