### ISSUE TITLE
get an error when trying to run demos/python_demos/action_recognition

### ISSUE THREAD

**Issue by Madaocv** [openvinotoolkit/open_model_zoo#290]
Hello I get an error when trying to run python script on Mac Mojave 10.14.6.
Can you a little bit of help to run a script ?

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
terminating with uncaught exception of type NSException

**Comment by IRDonch** [comment]
It looks like the problem is caused by the demo doing its rendering from a non-main thread. If this is a problem on macOS, we'll have to refactor the demo to no longer do that. @Wovchena Please look into this.

**Comment by vladimir-dudnik** [comment]
close as outdated
