### ISSUE TITLE
parameters for loading vehicle-license-plate-detection-barrier-0106  in opencv

### ISSUE THREAD

**Issue by ffiruzi** [openvinotoolkit/open_model_zoo#2935]
Hi, 

I wonder what are the right parameters for creating a blob in order to use the **vehicle-license-plate-detection-barrier-0106** in opencv? I test the following parameters for **meanval** and **scale** and **swapRB** and I don't know if they're true. Please explain me about the  values of  blobFromImage function  and scale and meanval and swapRB parameters  for this model.

 Thank you. 

```
cv::cvtColor(img, img, COLOR_RGB2BGR); 
Mat blob = blobFromImage(img, 1.0, Size(300, 300), Scalar(127.5, 127.5, 127.5) , true,  false, CV_32F);

```

**Comment by eaidova** [comment]
@ffiruzi you can find information about acceptable for model input format in its description:
https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/vehicle-license-plate-detection-barrier-0106/README.md

As you can see model expects BGR images in [0, 255] range and size 300x300, no any mean and scale should be applied in preprocessing.
Regarding opencv specific parameters, @alvoron @alalek could you please help?

**Comment by ffiruzi** [comment]
thank you  @eaidova. I'd read the README file of the model, but I couldn't find any info about the mean and scale. I hope @alalek gives some information to create blob for this model.

**Comment by alalek** [comment]
Assume that `img` is in BGR format (default output from OpenCV's `imread()`, `VideoCapture`) and

> no any mean and scale should be applied in preprocessing

```
// not needed at all or use swapRB parameter below: cv::cvtColor(img, img, COLOR_RGB2BGR);
Mat blob = blobFromImage(img,
    /*scalefactor=*/1.0,
    /*size=*/Size(300, 300),
    /*mean=*/Scalar::all(0),
    /*swapRB=*/false,
    /*crop=*/false,
    /*ddepth=*/CV_32F);
```

Please note that [`security_barrier_camera_demo`](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/security_barrier_camera_demo/cpp) passes U8 input to InferenceEngine.

**Comment by ffiruzi** [comment]
Thank you @alalek.
