### ISSUE TITLE
Live Streaming with image_capture.py (action-human-recognition/python)

### ISSUE THREAD

**Issue by paularamo** [openvinotoolkit/open_model_zoo#3029]
I am creating a notebook (Jupyter) inspired by your demo "[action_recognition]("https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/action_recognition_demo/python)". I would like to create live streaming using different cameras (e.g webcam) and running the action recognition behind. I tried to use a "player" (utils.VideoPlayer) and also a cv2.VideoCapture as an input, and image_capture.py is expecting to have a path with the video to analyze. So, I cannot use image_capture.py to get frames from streaming.

Could you please give me more lights about how I could use image_capture.py or let me know what kind of resource I may use, to continue working with your pipeline into Jupyter Notebook?

Thanks and BR.

**Comment by Wovchena** [comment]
You can provide `0` as input which will be interpreted as webcam id. See https://github.com/openvinotoolkit/open_model_zoo/blob/e813a1f0ee071c48b8bb3f56ec85331be9b35c07/demos/action_recognition_demo/python/action_recognition_demo.py#L42

**Comment by paularamo** [comment]
Thanks @Wovchena That was the first thing I tried, but unfortunately, it is not working and I got this message.
![image](https://user-images.githubusercontent.com/10940214/147672290-5662003f-f007-419c-9dc7-472b2282f2cd.png)
I am not using directly your main python script. I am using your dependencies in my notebook. 
What do you think?

**Comment by Wovchena** [comment]
Replace `cap = open_images_capture(0, loop)` with `cap = open_images_capture('0', loop)`

**Comment by paularamo** [comment]
Thanks @Wovchena. Your code is impressive. Thanks for doing that.
