### ISSUE TITLE
About ModelRetinaFacePT::getFilteredProposals function

### ISSUE THREAD

**Issue by hayashi57** [openvinotoolkit/open_model_zoo#3040]
The [link](https://github.com/openvinotoolkit/open_model_zoo/blob/324b4ccbb235e347e5894c22364a30f660bfe89d/demos/common/cpp/models/src/detection_model_retinaface_pt.cpp#:~:text=float%20cY%20%3D%20priors%5Bi%5D.cY%20%2B%20pRawBox%2D%3EcY%20*%20variance%5B0%5D%20*%20prior.width%3B) below may be better with the following code.
`float cY = priors[i].cY + pRawBox->cY * variance[0] * prior.height;`

**Comment by vladimir-dudnik** [comment]
@hayashi57 thanks for the catching this, seems to be typo.
@fzhar please take a look at suggested change

**Comment by fzhar** [comment]
Done: https://github.com/openvinotoolkit/open_model_zoo/pull/3059

**Comment by vladimir-dudnik** [comment]
@hayashi57 fix merged, I'll close the issue
