### ISSUE TITLE
Question: which version of openvino is required right now?

### ISSUE THREAD

**Issue by vnnw** [openvinotoolkit/open_model_zoo#3118]
I tried to run 'multi_camera_multi_target_tracking_demo' but got a ModuleNotFoundError: No module named 'openvino.runtime'.
After doing some searching, I found that I should use the codes from releases like [2021.4.2](https://github.com/openvinotoolkit/open_model_zoo/releases/tag/2021.4.2) instead of cloning this repo directly.
So I wonder which version of openvino is required to run the codes in this repo?

**Comment by vnnw** [comment]
> 
Seems the master branch is for currently development, you should download the released codes here: https://github.com/openvinotoolkit/open_model_zoo/releases/tag/2021.4.2

**Comment by vladimir-dudnik** [comment]
@ziudeso @vnnw for OMZ python demos in `master` branch you should install OMZ model API module (it is actually part of OMZ), call `pip install <OMZ>/demos/common/python`

Note, OMZ demos in `master` branch migrated to OpenVINO 2022.1 API (lot of changes, stay tuned) and require 2022.1 runtime. Pre-release for OpenVINO 2022.1 publicly [available](https://github.com/openvinotoolkit/openvino/releases), so you can try and see what changes expect from coming release. Note, pre-release may not include all features in gold quality.
