### ISSUE TITLE
face re-identification limits

### ISSUE THREAD

**Issue by yahanda** [openvinotoolkit/open_model_zoo#3166]
Hi there!

I have a quick question about maximum number of person that can be registered in face gallery for face-reidentification-retail-0095.
Are there any limits? Any known usage restrictions?

**Comment by vladimir-dudnik** [comment]
Looking at [face-reidentification-retail-0095](https://docs.openvino.ai/2021.4/omz_models_model_face_reidentification_retail_0095.html) model description, we can see that it takes image with one face (128x128) at a time and produce vector of 256 floating point values, representing descriptor of this face. This descriptor then may be compared by cosine distance against such vectors, computed on other images, potentially representing other faces (or different views of the same face) to determine if they are similar enough. So, it is not a model but rather application responsibility to store as much descriptors as needed. The limiting factors, application developers need to take into account, are performance of comparison all descriptors. For offline application, obviously there are almost no limits (probably except amount of memory available at system). For real-time applications. limiting factor is time required for comparison all descriptors. But again, implementation of cosine distance and comparison of descriptors by cosine difference done at application level, it is not a part of model inference, not a part of OpenVINO runtime.

**Comment by yahanda** [comment]
Understood. Thank you for the clarification.
