### ISSUE TITLE
[Suggestion] Change efficientNet-b0 ckpt File to Match Torchvision

### ISSUE THREAD

**Issue by wdkwyf** [openvinotoolkit/open_model_zoo#3203]
The OMZ [efficientnet-b0-pytorch](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/efficientnet-b0-pytorch) use different ckpt file with the [torchvision.models.efficientnet.](https://pytorch.org/vision/main/_modules/torchvision/models/efficientnet.html).
That is: efficientnet_b0-d6904d92.pth(OMZ version) vs efficientnet_b0_ra-3dd342df.pth(torchvision use, popular)
So, I suggest we can change the weight of efficientnet-b0-pytorch to [efficientnet_b0_ra-3dd342df.pth](https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-weights/efficientnet_b0_ra-3dd342df.pth)

**Comment by vladimir-dudnik** [comment]
@wdkwyf thanks for suggestion, @eaidova @jkamelin could you please review suggested change?

**Comment by eaidova** [comment]
@wdkwyf thanks for your suggestion. We will be happy to align weights with official torchvision model version
We prepared PR with these changes https://github.com/openvinotoolkit/open_model_zoo/pull/3336

**Comment by wdkwyf** [comment]
Thanks all!
