### ISSUE TITLE
While building OMZ demos, getting ov::streams not declared error

### ISSUE THREAD

**Issue by js333031** [openvinotoolkit/open_model_zoo#3291]
While building OMZ demos, getting ov::streams not declared error
`Scanning dependencies of target utils
[  5%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/args_helper.cpp.o
[  6%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/config_factory.cpp.o
[  6%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/image_utils.cpp.o
[  6%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/images_capture.cpp.o
[  7%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/kuhn_munkres.cpp.o
[  8%] Building CXX object common/cpp/utils/CMakeFiles/utils.dir/src/performance_metrics.cpp.o
In file included from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:22:0:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp: In function ‘void logCompiledModelInfo(const ov::CompiledModel&, const string&, const string&, const string&)’:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp:155:67: error: ‘ov::streams’ has not been declared
                 int32_t nstreams = compiledModel.get_property(ov::streams::num);
                                                                   ^~~~~~~
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp: In static member function ‘static ModelConfig ConfigFactory::getUserConfig(const string&, uint32_t, const string&, uint32_t)’:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:48:17: error: ‘ov::streams’ has not been declared
             ov::streams::Num nstreams = deviceNstreams.count(device) > 0 ? ov::streams::Num(deviceNstreams[device]) : ov::streams::AUTO;
                 ^~~~~~~
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:49:56: error: ‘nstreams’ was not declared in this scope
             config.compiledModelConfig.emplace(device, nstreams);
                                                        ^~~~~~~~
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:49:56: note: suggested alternative: ‘wctrans’
             config.compiledModelConfig.emplace(device, nstreams);
                                                        ^~~~~~~~
                                                        wctrans
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp: In static member function ‘static ModelConfig ConfigFactory::getMinLatencyConfig(const string&, uint32_t)’:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:65:52: error: ‘ov::streams’ has not been declared
             config.compiledModelConfig.emplace(ov::streams::num.name(), 1);
                                                    ^~~~~~~
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/config_factory.cpp:68:52: error: ‘ov::streams’ has not been declared
             config.compiledModelConfig.emplace(ov::streams::num.name(), 1);
                                                    ^~~~~~~
[  9%] Linking CXX static library ../../../intel64/Release/lib/libmonitors.a
[  9%] Built target monitors
In file included from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/ocv_common.hpp:15:0,
                 from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/performance_metrics.hpp:17,
                 from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/performance_metrics.cpp:6:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp: In function ‘void logCompiledModelInfo(const ov::CompiledModel&, const string&, const string&, const string&)’:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp:155:67: error: ‘ov::streams’ has not been declared
                 int32_t nstreams = compiledModel.get_property(ov::streams::num);
                                                                   ^~~~~~~
In file included from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/ocv_common.hpp:15:0,
                 from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/performance_metrics.hpp:17,
                 from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/images_capture.h:10,
                 from /home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/src/images_capture.cpp:5:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp: In function ‘void logCompiledModelInfo(const ov::CompiledModel&, const string&, const string&, const string&)’:
/home/xxx/workspace/open_model_zoo/demos/common/cpp/utils/include/utils/common.hpp:155:67: error: ‘ov::streams’ has not been declared
                 int32_t nstreams = compiledModel.get_property(ov::streams::num);
                                                                   ^~~~~~~
gmake[2]: *** [common/cpp/utils/CMakeFiles/utils.dir/build.make:93: common/cpp/utils/CMakeFiles/utils.dir/src/config_factory.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [common/cpp/utils/CMakeFiles/utils.dir/build.make:145: common/cpp/utils/CMakeFiles/utils.dir/src/performance_metrics.cpp.o] Error 1
gmake[2]: *** [common/cpp/utils/CMakeFiles/utils.dir/build.make:119: common/cpp/utils/CMakeFiles/utils.dir/src/images_capture.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:825: common/cpp/utils/CMakeFiles/utils.dir/all] Error 2
gmake: *** [Makefile:147: all] Error 2
Error on or near line 106; exiting with status 1
user@localhost:~/workspace/open_model_zoo/demos>`

**Comment by vladimir-dudnik** [comment]
@js333031 this change was recently introduced by OpenVINO, see OpenVINO PR https://github.com/openvinotoolkit/openvino/pull/10411 and corresponding change done on OMZ side, see PR https://github.com/openvinotoolkit/open_model_zoo/pull/3254. You will need OpenVINO 2022.1.605 build to be able compile OMZ from master branch

**Comment by js333031** [comment]
Which tag can I use to checkout OpenVINO 2022.1.605?

Alternatively, which OMZ tag can I use to compile OMZ with OV  2022.1.0.dev20220215?

**Comment by vladimir-dudnik** [comment]
@js333031 when you check out OpenVINO by tag 2022.1.0.dev20220215 you may find corresponding Open Model Zoo, included as submodule at thirdparty/open_model_zoo folder

**Comment by vladimir-dudnik** [comment]
resolved in OpenVINO 2022.1 release
