### ISSUE TITLE
ModuleNotFoundError: No module named '_pyngraph'

### ISSUE THREAD

**Issue by Praveen-mvp** [openvinotoolkit/open_model_zoo#3297]
Received an error while running the 'Object Detection Demo'

![er](https://user-images.githubusercontent.com/78363617/155708681-3d9d0df7-2e62-455f-90f7-2979a5b58951.jpg)

**Comment by vladimir-dudnik** [comment]
@Praveen-mvp seems mismatch between OpenVINO runtime and Open Model Zoo version. 2021.1 is relatively old release, the latest is 2021.4.2. Could you try with the latest release? If not, then you have to use Open Model Zoo from 2021.1 release
