### ISSUE TITLE
documentation mismatch

### ISSUE THREAD

**Issue by walteriviera** [openvinotoolkit/open_model_zoo#3332]
Trying to get the 3d_segmentation_demo working, but as soon as I start reading the documentation, it request to install requirements.txt and that file is not even there.

Documentation refers to omz_directory, with no explanation on how to set it, although the concept is clear.
Nevertheless, the demo doesn't work because the install instructions points to link which are not exaustive in explaining how to get all the components sorted.

**Comment by vladimir-dudnik** [comment]
@Wovchena @anzhella-pankratova @akorobeinikov @ivikhrev

**Comment by eaidova** [comment]
The issue already fixed as part of https://github.com/openvinotoolkit/open_model_zoo/pull/3334
Currently there is no additional requirements.txt for specific demos, all requirements in one place. Actual python demos requirements installation process described in https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#dependencies-for-python-demos
@walteriviera thank you for your note! Can we close this issue?
