### ISSUE TITLE
Building OpenCV4.5.5 form source with enabling Inference Engine not working?

### ISSUE THREAD

**Issue by Bahramudin** [openvinotoolkit/open_model_zoo#3347]
I have successfully built OpenCV from the source without any errors, but when I am using Inference Engine to read net, it shows the following error:

> OpenCV(4.5.5-dev) D:\opencv\modules\dnn\src\dnn.cpp:3964: error: (-2:Unspecified error) Build OpenCV with Inference Engine to enable loading models from Model Optimizer. in function 'cv::dnn::dnn4_v20211220::Net::readFromModelOptimizer'

But when I print `cv::getBuildInformation();` it prints the following output:

> **Inference Engine:            YES (2021040200 / 2021.4.2)**
>         * libs:                  C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/lib/intel64/Release/inference_engine.lib / C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/lib/intel64/Debug/inference_engined.lib C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll / C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll
>         * includes:              C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/inference_engine/include
>     nGraph:                      YES (0.0.0+e2a469a)
>         * libs:                  C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraph.lib / C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraphd.lib C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraph.dll / C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraphd.dll C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraph.dll C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/lib/ngraphd.dll
>         * includes:              C:/Program Files (x86)/Intel/openvino_2021.4.752/deployment_tools/ngraph/include

So the output shows it has the Inference Engine functionality to read net, but why it is not working?

**Comment by vladimir-dudnik** [comment]
@Bahramudin could you please provide more details on how you use Inference Engine to read net, make sure you initialized your environment in right way, so that when you run your OpenCV program it will load your build of OpenCV instead of precompiled version from OpenVINO distribution.
@mshabunin @alalek could you please comment on this?

**Comment by Bahramudin** [comment]
@vladimir-dudnik This is how I use it, the same code was working well in previous versions:

        cout << ">>>>>>>>>>>>>> start" << endl;
        string basePath = "D:/models/OpenVINO_2021_4_752/person-detection/";
        std::string modelName = "person-detection-0203"; cv::Size size(480, 864); 
        string modelPath = "/FP32/";

        string xml = basePath + modelName + modelPath + modelName + ".xml";
        string bin = basePath + modelName + modelPath + modelName + ".bin";


        cout << ">>>>>>>>>>>>>> xml = " << xml << endl;
        // D:/models/OpenVINO_2021_4_752/person-detection/person-detection-0203/FP32/person-detection-0203.xml
        cout << ">>>>>>>>>>>>>> bin = " << bin << endl;
        // D:/models/OpenVINO_2021_4_752/person-detection/person-detection-0203/FP32/person-detection-0203.bin

        cv::dnn::Net net = cv::dnn::Net::readFromModelOptimizer(xml, bin); // this line throws exception
        //cv::dnn::Net net = cv::dnn::readNet(bin, xml); // this line as well
        cout << ">>>>>>>>>>>>>> read net done successfully" << endl; // this line never print

**Comment by mshabunin** [comment]
This error should not be shown if your OpenCV build have OpenVINO support enabled. There are two possibilities, either you are using second copy of OpenCV from elsewhere in the actual application, either you have broken internal cmake state after changing the options. Try to make a clean build and double check that OpenCV being loaded is the one built with OpenVINO support (call `getBuildInformation` in the same app which fails with an error).

**Comment by Bahramudin** [comment]
@mshabunin I have checked every possible issue, in my PC I only have one OpenCV build library, in every OpenCV update, I delete everything including OpenVINO old version and download all the latest codes and packages and do a clean build from scratch, so there will not be any old version libraries to make conflict with the new one. 

In all time I respect the same policy, but before everything was working in one shot (only build one time and run with no problem) but in the current version, I built OpenCV so many times, but I cannot overcome this error, so I came here.

While calling `getBuildInformation()` it clearly shows that it has the IE functionality (IE is enabled): 

```
  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   D:/opencv/build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                D:/opencv/build/3rdparty/ippicv/ippicv_win/iw
    Lapack:                      NO
    Inference Engine:            YES (2021040200 / 2021.4.2)
```

But while reading net it says IE is not enabled, so there is a conflict present in the new version, I don't know this error belongs to OpenCV itself or it belongs to OpenVINO Toolkit?

_During building, there was not any error or warning._

**Comment by mshabunin** [comment]
I've not been able to reproduce your issue with OpenCV@4.5.5 or 4.x branch and OpenVINO 2021.4.2 ([model](https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.4/models_bin/3/person-detection-0203/FP32/), [release](https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4.2/)).

So I built OpenCV (only _dnn_ module):
```.cmd
$ cd build
$ ..\openvino_752\bin\setupvars.bat
	Python 3.8.12
	[setupvars.bat] OpenVINO environment initialized
$ cmake -G"Visual Studio 16 2019" -A x64 -DWITH_INF_ENGINE=ON  -DBUILD_LIST=dnn ..\opencv
	...
	--     Inference Engine:            YES (2021040200 / 2021.4.2)
	--         * libs:                  C:/work/openvino_752/...
	--         * includes:              C:/work/openvino_752/...
	--     nGraph:                      YES (0.0.0+e2a469a)
	--         * libs:                  C:/work/openvino_752/...
	--         * includes:              C:/work/openvino_752/...
	...
$ cmake --build . --config Release
```
Then build an application:
```.cmd
$ cd ..\build-sample
$ set OpenCV_DIR=..\build
$ cmake -G"Visual Studio 16 2019" -A x64 ..\example
$ cmake --build . --config Release
```
Then ran it:
```.cmd
$ set PATH=..\build\bin\Release;%PATH%
$ Release\opencv_example.exe
	>>>>>>>>>>>>>> start
	[E:] [BSL] found 0 ioexpander device
	>>>>>>>>>>>>>> read net done successfully
```
Application is simple:
```.cpp
cout << ">>>>>>>>>>>>>> start" << endl;
cv::dnn::Net net = cv::dnn::Net::readFromModelOptimizer("person-detection-0203.xml", "person-detection-0203.bin");
cout << ">>>>>>>>>>>>>> read net done successfully" << endl;
```

**Comment by Bahramudin** [comment]
@mshabunin I am wondering why here in my PC is not working, anyway, I will keep trying to get the reason that is why it is not working and then I will share it here.
Thanks!!

**Comment by Bahramudin** [comment]
Something I have discovered is, when building OpenCV from source (I think there are now new changes made by the OpenCV team) need to enable both `OPENCV_DNN_OPENVINO` and `WITH_OPENVINO` which before there was only one flag needed to be enabled (WITH_ENFERENCE_ENGIN).
But now I am facing a [new](https://github.com/openvinotoolkit/open_model_zoo/issues/3363#issue-1169006054) problem.

**Comment by alalek** [comment]
Avoid using of CMake GUI - changing build configuration **on the fly** is tricky and it is not validated.

Consider using of CMake command-line only:
- all required flags are specified on the first run (we have reproducible input as much as possible)
- clear CMake cache if dependencies are changed or upgraded

**Comment by saurabhmj11** [comment]
Based on the error message and the output of cv::getBuildInformation(), it seems that OpenCV was built with Inference Engine support, but the specific module you're using (cv::dnn) is not linked to the Inference Engine library.

You can check whether the Inference Engine plugin for cv::dnn is available in your system by running the following command:

bash
Copy code
ls -l /path/to/opencv/lib/
and look for a file named opencv_dnn_plugin.* or libopencv_dnn_plugin.* (where * is the file extension depending on your operating system). If the file is not present, it means that the Inference Engine plugin for cv::dnn was not built or installed.

If the file is present, you may need to link it manually by adding the following line to your code:

ruby
Copy code
cv::dnn::Net net = cv::dnn::readNetFromModelOptimizer(model_xml, model_bin);
net.setPreferableBackend(cv::dnn::DNN_BACKEND_INFERENCE_ENGINE);
net.setPreferableTarget(cv::dnn::DNN_TARGET_CPU);
This code sets the backend and target to use the Inference Engine plugin for cv::dnn.

If the above steps do not work, you may need to rebuild OpenCV with the WITH_INF_ENGINE flag explicitly enabled.
