### ISSUE TITLE
Unable to use Inference Engine detect objects

### ISSUE THREAD

**Issue by Bahramudin** [openvinotoolkit/open_model_zoo#3363]
OpenCV: 4.5.5
OpenVINO: 2021.4.2

The problem happens when running the following code (the same code was working well in the previous versions):

    ```
    cout << ">>>>>>>>>>>>>> start" << endl;
    string basePath = "D:/models/OpenVINO_2021_4_752/person-detection/";
    std::string modelName = "person-detection-0203"; 
    cv::Size size(480, 864); 
    string modelPath = "/FP32/";

    string xml = basePath + modelName + modelPath + modelName + ".xml";
    string bin = basePath + modelName + modelPath + modelName + ".bin";

    cout << ">>>>>>>>>>>>>> xml = " << xml << endl;
    // D:/models/OpenVINO_2021_4_752/person-detection/person-detection-0203/FP32/person-detection-0203.xml
    cout << ">>>>>>>>>>>>>> bin = " << bin << endl;
    // D:/models/OpenVINO_2021_4_752/person-detection/person-detection-0203/FP32/person-detection-0203.bin

    cv::dnn::Net net = cv::dnn::Net::readFromModelOptimizer(xml, bin);

    cv::Mat blob = cv::dnn::blobFromImage(frame, 1.0F, size);
    std::cout << "blobFromImage done!" << std::endl;
    net.setInput(blob);
    std::cout << "setInput done!" << std::endl;
    cv::Mat detection = net.forward();
    std::cout << "forward done!" << std::endl;
```
And this is the error:

> blobFromImage done!
> setInput done!
> [ WARN:0@2.028] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '1095_1096.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.028] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '1312_1313.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.030] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '1529_1530.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.032] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '1746_1747.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.033] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '1963_1964.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.034] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output '2234_2235.0' blob due to wrong dims: 2 => 1
> [ WARN:0@2.036] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (974) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due to wrong precision: FP32 => I32  ndims=1
> [ WARN:0@2.037] global D:\opencv\opencv\modules\dnn\src\ie_ngraph.cpp (979) cv::dnn::ngraphDataOutputNode Reallocate output 'labels' blob due to wrong dims: 2 => 1
> forward done!
> Press <RETURN> to close this window...

**Comment by alalek** [comment]
There is OpenCV DNN API limitation.
OpenCV DNN is designed to work with FP32 outputs only (even with fp16 internal inference).
Some experimental workarounds were added, so you see these warnings (**NOT ERRORS**) which may cause some performance impact.

To use OpenVINO models with non-FP32 outputs it is recommended to use OpenVINO API directly instead of OpenCV DNN API.

---

There is no issue with OMZ.

**Comment by Bahramudin** [comment]
@alalek I am just using FP32
`D:/models/OpenVINO_2021_4_752/person-detection/person-detection-0203/FP32/person-detection-0203.xml`

Which I downloaded it from:
 ```
 - name: FP32/person-detection-0203.xml
    size: 1270918
    sha256: 52af5e82a7b1fce4fea6cd3544172b84bc799afc2d6f865050c0bc8d4375a984
    source: https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.4/models_bin/3/person-detection-0203/FP32/person-detection-0203.xml
  - name: FP32/person-detection-0203.bin
    size: 7804628
    sha256: 1ccc07ef6702756b368de97083ba29d367826b315d1872730ab37048d50dbafd
    source: https://storage.openvinotoolkit.org/repositories/open_model_zoo/2021.4/models_bin/3/person-detection-0203/FP32/person-detection-0203.bin
```

And I don't know what do you mean by **FP32 outputs**, is there any settings to do before starting detecting?

And also I tested **person-detection-0202** which does not give any error, but there is no output produced when forwarding?

**Comment by vladimir-dudnik** [comment]
model [person-detection-0203](https://docs.openvino.ai/2021.4/omz_models_model_person_detection_0203.html) has two outputs:
1, name "boxes", shape [100, 5], type FP32
2, name "labels", shape [100], type I32

and model person-detection-0202 has single output:
name "detection_out", shape [1, 1, 200, 7], type FP32

as @alalek said, OpenCV DNN has limitation that it support model outputs of FP32 type only.
