### ISSUE TITLE
How to play  multiple cameras in face recognition

### ISSUE THREAD

**Issue by Balu2311** [openvinotoolkit/open_model_zoo#3439]
single cameras working using threading but multiple cameras error got request busy and out of range of index, automatic dis connect cameras  only single camera working

**Comment by vladimir-dudnik** [comment]
@Balu2311 are you talking about Python face_recognition_demo ? According to the [description](https://docs.openvino.ai/latest/omz_demos_face_recognition_demo_python.html), this demo takes single input:
  -i INPUT, --input INPUT
                        Required. An input to process. The input must be a
                        single image, a folder of images, video file or camera id.
