### ISSUE TITLE
combine two demo

### ISSUE THREAD

**Issue by moradAMR** [openvinotoolkit/open_model_zoo#3441]
hi , i want to combine two demo social_distance_demo and Smart
_classroom_demo in one demo but i have some problmes , if you can help me ?

this is it the demo that i did .

[test_demo.zip](https://github.com/openvinotoolkit/open_model_zoo/files/8402453/test_demo.zip)

**Comment by vladimir-dudnik** [comment]
@moradAMR smart_classroom_demo provides functionality to detected/recognize people in classroom (either students or teacher, depending on used model) and recognize actions they do during some time. And social_distance_demo detects people and compute approximate distance between them and warn if distance is less some threshold.
What functionality you want to combine in new demo?

**Comment by moradAMR** [comment]
I want to integrate all the functions OF smart_classroom_demo and function of compute approximate distance between people and warn if distance is less some threshold for social_distance_demo

**Comment by andrei-kochin** [comment]
@moradAMR  is it still actual for you?
