### ISSUE TITLE
face re-identification with a mask

### ISSUE THREAD

**Issue by yahanda** [openvinotoolkit/open_model_zoo#3458]
Is [face-reidentification-retail-0095](https://docs.openvino.ai/2021.4/omz_models_model_face_reidentification_retail_0095.html) also valid for identification of people wearing face coverings?
We are looking for a way to identify the face wearing masks with openvino.
Are there any recommendatinos for face identification with a mask, best practice, or things to watch out for?

Thanks,

**Comment by vladimir-dudnik** [comment]
@yahanda face-reidentification-retail-0095 model was trained on dataset with faces without masks (long time ago, before COVID pandemic). Although, it still may work for people with masks, but you need to understand features and limitation of this model. Strictly speaking, the model just compute vector of features from 128x128 face crop. Application then evaluate the cosine distance between several such vectors to find ones which are most close. Faces crops with minimal cosine distance most probably are similar and even might rely to the same person but this is not guaranteed.
