### ISSUE TITLE
How to solve this errors [ REQUEST_BUSY ] and cannot unpack non-iterable NoneType object  face recognition demo 

### ISSUE THREAD

**Issue by Balu2311** [openvinotoolkit/open_model_zoo#3461]
[ REQUEST_BUSY ] 
    def enqueue(self, input):
        self.clear()

        if self.max_requests <= self.active_requests:
            log.warning('Processing request rejected - too many requests')
            return False
     
       self.exec_net.start_async(self.active_requests, input)
      
      self.active_requests += 1
     return True

**Comment by vladimir-dudnik** [comment]
cc @akorobeinikov @anzhella-pankratova

**Comment by Balu2311** [comment]
did not understand, please how to solve the issue

**Comment by Balu2311** [comment]
def enqueue(self, input):
        self.clear()

        if self.max_requests <= self.active_requests:
            log.warning('Processing request rejected - too many requests')
            return False
        try:
            self.exec_net.start_async(self.active_requests, input)
        except:
            self.exec_net.start_async(self.active_requests, input)
        self.active_requests += 1
        return True

[ REQUEST_BUSY ]
