### ISSUE TITLE
yolov4+2022.1openvino，The test result is wrong

### ISSUE THREAD

**Issue by jiaerwang0328** [openvinotoolkit/open_model_zoo#3462]
I get yolo-v4-tf.xml using omz_downloader --name yolo-v4-tf and omz_converter --name yolo-v4-tf commands, but when running the demo ： .\object_detection_demo.exe -d CPU -i car-detection.mp4 -m yolo-v4-tf.xml -at yolo -layout NHWC -t 0.5 -iou_t 0.5 -labels label.txt  , the network detection result is wrong，Can you give me some advice, thanks in   advance  ？
![image-20220414101735391](https://user-images.githubusercontent.com/38750407/163301023-99d6511f-7bdc-434b-bad3-7e4b483fc2f7.png)

**Comment by wuranran** [comment]
@kminemur Can you give me some advice？

**Comment by mempf** [comment]
Hi @jiaerwang0328 I also ran into this issue when using the new model optimizer included in the 2022.1 release. I have created a PR that attempts to fix this issue.
