### ISSUE TITLE
combine social_distance_demo and Smart _classroom_demo

### ISSUE THREAD

**Issue by moradAMR** [openvinotoolkit/open_model_zoo#3464]
hi , i want to combine two demo social_distance_demo and Smart
_classroom_demo in one demo but i have some problmes , if you can help me ?
(I want to integrate all the functions OF smart_classroom_demo and function of compute approximate distance between people and warn if distance is less some threshold for social_distance_demo)

this is it the demo that i did .

**Comment by andrei-kochin** [comment]
Duplicate of #3441
