### ISSUE TITLE
multi cameras to face detection python language based 

### ISSUE THREAD

**Issue by Balu2311** [openvinotoolkit/open_model_zoo#3465]
multiple RTSP cameras to face detection at a time python source 
any one heal me

**Comment by saurabhmj11** [comment]
Sure, I can help you with that. Here's an example code for face detection with multiple cameras using Python and OpenCV library:

python
Copy code
import cv2

# Load the pre-trained face detection model
face_cascade = cv2.CascadeClassifier('path/to/haarcascade_frontalface_default.xml')

# Create a list of video streams from multiple cameras
streams = [
    cv2.VideoCapture('rtsp://camera1'),
    cv2.VideoCapture('rtsp://camera2'),
    cv2.VideoCapture('rtsp://camera3')
]

# Loop through each video stream
while True:
    # Read a frame from each stream
    frames = [stream.read()[1] for stream in streams]

    # Loop through each frame
    for i, frame in enumerate(frames):
        # Convert the frame to grayscale for face detection
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # Detect faces in the frame
        faces = face_cascade.detectMultiScale(gray, 1.3, 5)

        # Draw a rectangle around each face
        for (x, y, w, h) in faces:
            cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 255), 2)

        # Show the frame
        cv2.imshow(f'Camera {i+1}', frame)

    # Wait for a key press to exit
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the video streams and close all windows
for stream in streams:
    stream.release()
cv2.destroyAllWindows()
In this example code, we first load the pre-trained face detection model (Haar Cascade classifier). We then create a list of video streams from multiple cameras using their RTSP URLs. We then loop through each video stream and read a frame from each stream. We convert each frame to grayscale for face detection and detect faces using the pre-trained model. We then draw a rectangle around each face in the frame and show the frame on the screen. We repeat this process for all video streams until the user presses the 'q' key to exit. Finally, we release the video streams and close all windows.

Please note that you'll need to replace the RTSP URLs with the actual URLs of your cameras. Also, you might need to adjust the face detection parameters (scaleFactor and minNeighbors) for best results.
