### ISSUE TITLE
list assignment index out of range  Error  showing this lines             from  self.exec_net.requests[i].wait()          self.outputs[i] = self.exec_net.requests[i].output_blobs #  error this line and above line

### ISSUE THREAD

**Issue by Balu2311** [openvinotoolkit/open_model_zoo#3466]
def wait(self):

        if self.active_requests <= 0:
            return

         self.outputs = [None, ] * self.active_requests
         for i in range(self.active_requests):
             self.exec_net.requests[i].wait()
             self.outputs[i] = self.exec_net.requests[i].output_blobs #  error this line and above line

         self.active_requests = 0

**Comment by Wovchena** [comment]
I don't think such piece of code ever existed in this repo. If you are still interested in it, you need to clarify your question
