### ISSUE TITLE
how to avoided  false detection from face detection model can help me

### ISSUE THREAD

**Issue by Balu2311** [openvinotoolkit/open_model_zoo#3468]
![FaceDetection31_03_2022_TIME_16_28_08](https://user-images.githubusercontent.com/53854911/165496846-10d4cb55-7bba-4122-be88-6b0bf8864238.jpg)
   
I tried to change the threshold(0.8) value and input frame size (500,700), but the same faced false detection, open-vino face detection all models checked but the same issue facing

**Comment by Wovchena** [comment]
@sovrasov, @a-a-egorovich, can you point to training code, if it exists?

**Comment by sovrasov** [comment]
face-detection-0204 still exists in old OTE: https://github.com/openvinotoolkit/training_extensions/blob/4e8ec5d8d7527b0afa5d506ff1bd35299717262d/pytorch_toolkit/object_detection/face-detection/readme.md

face-detection-retail-0004 and face-detection-adas-0001 were trained in custom caffe, which was completely lost.
