### ISSUE TITLE
Memory Leak observed in text_to_speech model demo sample

### ISSUE THREAD

**Issue by AishaSamaanKhan** [openvinotoolkit/open_model_zoo#3475]
## Summary 

We were trying to leverage the openvino text to speech demo sample as inferencing server to which input is fed continuously, we observed that with each input text the memory consumption increases and eventually causing segment fault which results in machine crash. After debugging we found that the scope of inference network object still remain and thereby become a garbage object. 

## Question 
Is there a optimized way to clear the inference network before passing the next input so that it can fit our use-case?

## Simple way to reproduce it 
Giving the continuous input in for-loop

**Comment by Wovchena** [comment]
I can't reproduce it. With for loop:
`for tmp in {1..99}; do 'C:\Users\vzlobin\AppData\Local\Programs\Python\Python310\py.exe' 'C:\Users\vzlobin\r\z\demos\text_to_speech_demo\python\text_to_speech_demo.py' -d CPU -i 'The quick brown fox jumps over the lazy dog.' 'The five boxing wizards jump quickly.' -m_duration 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-duration-prediction\FP16\text-to-speech-en-0001-duration-prediction.xml' -m_forward 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-regression\FP16\text-to-speech-en-0001-regression.xml' -m_melgan 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-generation\FP16\text-to-speech-en-0001-generation.xml'; done`
But this may be that restarting a process each time hides the leak, so I compared
`'C:\Users\vzlobin\AppData\Local\Programs\Python\Python310\py.exe' 'C:\Users\vzlobin\r\z\demos\text_to_speech_demo\python\text_to_speech_demo.py' -d CPU -i 'The quick brown fox jumps over the lazy dog.' 'The five boxing wizards jump quickly.' -m_duration 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-duration-prediction\FP16\text-to-speech-en-0001-duration-prediction.xml' -m_forward 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-regression\FP16\text-to-speech-en-0001-regression.xml' -m_melgan 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-generation\FP16\text-to-speech-en-0001-generation.xml'`
and
`'C:\Users\vzlobin\AppData\Local\Programs\Python\Python310\py.exe' 'C:\Users\vzlobin\r\z\demos\text_to_speech_demo\python\text_to_speech_demo.py' -d CPU -i 'The quick brown fox jumps over the lazy dog.' 'The five boxing wizards jump quickly.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' 'The quick brown fox jumps over the lazy dog.' -m_duration 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-duration-prediction\FP16\text-to-speech-en-0001-duration-prediction.xml' -m_forward 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-regression\FP16\text-to-speech-en-0001-regression.xml' -m_melgan 'C:\Users\vzlobin\.cache\omz\intel\text-to-speech-en-0001\text-to-speech-en-0001-generation\FP16\text-to-speech-en-0001-generation.xml'`
and didn't notice any difference. If you are still interested, you need to provide a reproducer.
