### ISSUE TITLE
face_recognition modal is so bad ? what's happend ? 

### ISSUE THREAD

**Issue by jeesk** [openvinotoolkit/open_model_zoo#3478]
Can only one of the 20 pictures be recognized?  

python ./face_recognition_demo.py  -i /home/song/project/faceai/faceai/img/face_recognition/   -m_fd /home/song/env3/test/open_model_zoo/demos/face_recognition_demo/python/intel/face-detection-retail-0004/FP32/face-detection-retail-0004.xml   -m_lm ~/env3/test/open_model_zoo/demos/face_recognition_demo/python/intel/landmarks-regression-retail-0009/FP32/landmarks-regression-retail-0009.xml   -m_reid /home/song/env3/test/open_model_zoo/demos/face_recognition_demo/python/intel/face-reidentification-retail-0095/FP32/face-reidentification-retail-0095.xml   --verbose   -fg "fg"    -o output_%03d.jpg --run_detector

**Comment by andrei-kochin** [comment]
@jeesk

Could you please let me know was it better before? in which release if so?
