### ISSUE TITLE
Multi Camera Multi Target Demo fails with segmentation models

### ISSUE THREAD

**Issue by ericpronovost** [openvinotoolkit/open_model_zoo#3480]
Running the python demo with the person-detection-retail-0013 works fine. However, running with any of the segmentation models (instance-segmentation-security-xxx) fails:

open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py", line 140, in __init__
    super().__init__(core, model_path, device, 'Instance Segmentation', self.max_reqs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by Bibidkun** [comment]
> Running the python demo with the person-detection-retail-0013 works fine. However, running with any of the segmentation models (instance-segmentation-security-xxx) fails:
> 
> open_model_zoo/demos/multi_camera_multi_target_tracking_demo/python/utils/network_wrappers.py", line 140, in **init** super().**init**(core, model_path, device, 'Instance Segmentation', self.max_reqs) TypeError: object.**init**() takes exactly one argument (the instance to initialize)

I have the same problem. Please be corresponding

**Comment by fspinola** [comment]
I have the same problem, did you find a solution?

**Comment by lswgh** [comment]
same problem !
