### ISSUE TITLE
How to run yolov5s by object_detection_demo/cpp

### ISSUE THREAD

**Issue by biyuehuang** [openvinotoolkit/open_model_zoo#3487]
I can convert yolov5s ONNX model to IR by Openvino2022.1 on Windows10. but how to run it by object_detection_demo.
https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/object_detection_demo/cpp

**Comment by Wovchena** [comment]
`object_detection_demo` doesn't support yolov5. Same answer as https://github.com/openvinotoolkit/open_model_zoo/issues/3501#issuecomment-1192307685
