### ISSUE TITLE
yolov7 support

### ISSUE THREAD

**Issue by xylieong** [openvinotoolkit/open_model_zoo#3501]
Is there any sample codes supporting yolov7 model?

**Comment by eaidova** [comment]
@xylieong unfortunatly, the license of yolo v7 project does not permit to add it in our model zoo, so I'm not sure that sample will be provided.... I believe there is no big difference from original framework support regarding pre- and postprocessing steps. You need just add part connected with model loading using openvino (it is standard API).

**Comment by ayanasser** [comment]
@xylieong  Hello, did you figure out the difference between yolov4 and yolov7 at post or pre-processing ?

**Comment by xylieong** [comment]
@ayanasser I am not too sure about it. Are you using the python or cpp API? Are you using yolov7?

**Comment by ayanasser** [comment]
@xylieong 
I am using C++ demo of object detection, 
I've converted the yolov7 pytorch -> ONNX then to IR, 
There's a sample working code for inference the yolov7 with both python and C++
https://github.com/OpenVINO-dev-contest/YOLOv7_OpenVINO_cpp-python
you could use it.

My problem is I want to integrate that inside the object detection demo that exists at open model zoo, but if anyone want to use it from APIs just use the above mention link

**Comment by xylieong** [comment]
Hi @ayanasser Sorry that I can't help. Haven't figured it out yet. Let me know if you have any findings!

**Comment by ayanasser** [comment]
Note: I've used the mentioned repo (yolov7-openvino) with the latest openvino version (2022.1) and it works. 
but my main goal was to edit on the post-porcess function at the older version of openvino demos (2021.4.2)
.
