### ISSUE TITLE
A path error occurred during accuracy checking in Open Model Zoo

### ISSUE THREAD

**Issue by Zhangxianwen2021** [openvinotoolkit/open_model_zoo#3509]
I'm glad you can see my problems and give me some advice. I plan to make a contribution on OMZ. I have downloaded my model in Openvino docker and converted it into IR file. I have successfully completed the annotation convert of the dataset as shown in the figure below, and generated two files, voc_segmentation.json and voc_segmentation.pickle.
![图片](https://user-images.githubusercontent.com/93261001/181165394-d6e90099-b883-4c77-8763-96049396e416.png)

The next step is the accuracy_checker. The specific execution code is shown in Figure. At this point, an accuracy_checker error occurs. The path of converted annotation is “/opt/ Intel /openvino_2020.4.287/deployment_tools/open_model_zoo/tools/accuracy_checker/voc_convter/”. 
![图片](https://user-images.githubusercontent.com/93261001/181165435-6a756d22-632f-418c-89cb-ae8a5197132a.png)

I really look forward to your valuable advice to solve this problem.

**Comment by eaidova** [comment]
@Zhangxianwen2021 please provide configuration file which you use for your model.
Probably you forgot define name of converted annotation file in config or do not provide path to dataset definitions, where this info stored.

BTW, is it your requirement to use such old openvino?

**Comment by eaidova** [comment]
@Zhangxianwen2021 as I can judge on PR with adding erfnet to OMZ, you solved your problem, can we close this issue?
Thanks
