### ISSUE TITLE
No module named 'openvino.runtime'

### ISSUE THREAD

**Issue by KiiiiiB** [openvinotoolkit/open_model_zoo#3512]
I get the error ModuleNotFoundError: No module named 'openvino.runtime' from ie_tools.py 
How to solve this problem.

**Comment by eaidova** [comment]
@KiiiiiB could you please explain what is ie_tools.py? Looks like, it is not a part of OMZ.
Generally, `openvino.runtime` module was intorduced in 2022.1 openvino release, so please make sure that you use this openvino version, which compatible with your script version. Also if your installation is correct and you also have previous openvino version in your environment, please make sure that you do not use setup_vars script for activation environment in the same environment, where you try execute script

**Comment by KiiiiiB** [comment]
> 

I want to run the multi_camera_multi_target_tracking_demo.py but I got the error ModuleNotFoundError: No module named 'openvino.runtime'. I am not sure how to install the openvino and which I should to install requirements and setup.

**Comment by eaidova** [comment]
@KiiiiiB then let's understand together :)

Do you have installed openvino?
If yes, you can check version using this command:
`python -c "import openvino.inference_engine as ie; print(ie.get_version())"`

If you do not have it or version is less then 2022.1.0 (e.g. 2021.4.1) you need install it, you can use pip for it:
`pip install openvino==2022.1`
You can find more info about installation and tips [here](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_pip.html)
Also for running demos it may requires additional prerequisites, you can find info about it on this [page](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/README.md#dependencies-for-python-demos)

**Comment by KiiiiiB** [comment]
> 
Thank you so much.

**Comment by eaidova** [comment]
@KiiiiiB do you solve your problem? Can we close this issue?
