### ISSUE TITLE
How can I get the corresponding models for all intel .bin models files, like pytorch file format, the original files

### ISSUE THREAD

**Issue by grace2015** [openvinotoolkit/open_model_zoo#3524]
How can I get the corresponding models for all intel .bin models files, like pytorch file format, the original files

**Comment by eaidova** [comment]
@grace2015 sorry, these models are intellectual property of intel and due to some reasons training code can not be published in majority cases.
But some models can be found in https://github.com/openvinotoolkit/training_extensions

**Comment by grace2015** [comment]
Thanks for so quick reply, then can Intel share the Gesture Recognition related training/test dataset, we want to try use [training_extensions] or other platform to train, because we have to add our own gesture dataset together, thanks a lot!

**Comment by eaidova** [comment]
You can find relevant information for gesture recognition models and datasets for them here https://github.com/openvinotoolkit/training_extensions/blob/misc/models/action_recognition/model_templates/gesture-recognition/README.md

That is all, what can be done from my side, hope it helps

**Comment by grace2015** [comment]
ok, thank you so much.
