### ISSUE TITLE
Cannot reproduce the accuracy of person-detection-retail-0013 with accuracy_check on CPU

### ISSUE THREAD

**Issue by JoursBleu** [openvinotoolkit/open_model_zoo#3532]
We tried reproduce the accuracy of person-detection-retail-0013 model (https://docs.openvino.ai/latest/omz_models_model_person_detection_retail_0013.html) with accuracy_check.
But the accuracy is far away from which it should be (supposed 88.62, got 47.62).

 
Following is how to reproduce the error:
$ pip3 install openvino openvino_dev
$ git clone https://github.com/openvinotoolkit/open_model_zoo.git
$ cd open_model_zoo/models
$ omz_downloader --name person-detection-retail-0013
$ omz_converter --name person-detection-retail-0013
$ accuracy_check -c ./intel/person-detection-retail-0013/accuracy-check.yml -m ./intel/person-detection-retail-0013/FP32/person-detection-retail-0013.xml -s /PATH/TO/coco2017 -a /PATH/TO /coco2017 -d ../data/dataset_definitions.yml -td CPU

**Comment by eaidova** [comment]
accuracy of model reported on internal private dataset, which we can not share, not coco, sorry. We provided coco just for reference as sample how to run this model with accuracy_checker (or maybe quantize via pot), so comparing these numbers are impossible
