### ISSUE TITLE
In background_substration_demo model.lst does not matched

### ISSUE THREAD

**Issue by heedongis** [openvinotoolkit/open_model_zoo#3537]
When type omz_downloader --list models.lst,` No matching models: "modnet-photographic-portrait-matting"` error occured

**Comment by heedongis** [comment]
So I removed these model in models list

- modnet-photographic-portrait-matting
- modnet-webcam-portrait-matting

Then, It worked well

**Comment by Wovchena** [comment]
Hi
The models are here: [modnet-photographic-portrait-matting](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/modnet-photographic-portrait-matting), [modnet-webcam-portrait-matting](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/modnet-webcam-portrait-matting). It looks you use `models.lst` from `master` branch while `omz_downloader` is of older version when the models wasn't added yet.

**Comment by heedongis** [comment]
Thanks! @Wovchena
