### ISSUE TITLE
Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by sinchubhat** [openvinotoolkit/open_model_zoo#3559]
In Multi-Channel Object Detection Yolov3 C++ Demo, Both Intel and Public Models FP16 or FP16-INT8 (.xml file) gives Segmentation Fault (core dumped) error. It works perfectly fine if FP32 is used.

![Segmentation Fault Error](https://user-images.githubusercontent.com/32384381/192525792-d37572a0-4334-43a8-b312-a177d506af1c.jpg)

It works fine with Benchmark_app.

**Comment by sinchubhat** [comment]
FP16-INT8, FP32, FP16 .bin and .xml files are generated when we convert using omz_converter --list models.lst as mentioned in the documentation https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/multi_channel_object_detection_demo_yolov3/cpp/README.md
OMZ version - when we do git clone it pulls the latest version git clone --recurse-submodules https://github.com/openvinotoolkit/open_model_zoo.git
OS - Ubuntu 20.04

**Comment by sinchubhat** [comment]
The same error occurs for Multi-Channel Human Pose Estimation C++ Demo when FP16 or FP32 .xml file is used. Works fine for FP16-INT8

![seg_fault_mnhpe](https://user-images.githubusercontent.com/32384381/192956726-f8aeea32-1aa0-491e-9c9d-872a6c8c7e63.png)

Note- I have run the demo on 2 devices having different Openvino version. Got the same error in both.

**Comment by Wovchena** [comment]
I still can't reproduce it.

Can you check if there's enough RAM on your machines?

To follow your screenshot I installed 2022.1 Offline installer from https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html and then executed
```sh
. ~/intel/openvino_2022.1.0.643/setupvars.sh
git clone https://github.com/openvinotoolkit/open_model_zoo --recursive
open_model_zoo/demos/build_demos.sh
open_model_zoo/tools/model_tools/downloader.py --name human-pose-estimation-0001 -o ~/d --cache_dir ~/d
/home/vzlobin/omz_demos_build/intel64/Release/multi_channel_human_pose_estimation_demo -no_show -i face-demographics-walking.mp4 -m /home/vzlobin/d/intel/human-pose-estimation-0001/FP16/human-pose-estimation-0001.xml -bs 4
```
Can you see any difference with what you do?
Please share the models you use to run the demo.

**Comment by sinchubhat** [comment]
The issue is resolved.
I used Model Downloader and other Open Model Zoo tools
omz_downloader --list models.lst
omz_converter --list models.lst
https://pypi.org/project/openvino-dev/2022.1.0/
https://docs.openvino.ai/latest/omz_tools_downloader.html

The error was because of different versions of openvino-dev and OMZ Tools
So i updated openvino-dev to same version as that of openvino (2022.1.0) by
python3 -m pip install --upgrade pip
pip3 install openvino-dev[onnx,pytorch,caffe,kaldi,mxnet,tensorflow2]==2022.1.0


As you were using open_model_zoo/tools/model_tools/downloader.py --name human-pose-estimation-0001 -o ~/d --cache_dir ~/d to download, you didn't have to worry about the version of Model Downloader tools.
