### ISSUE TITLE
can't compiled with vs2019 with error!

### ISSUE THREAD

**Issue by danve-fan** [openvinotoolkit/open_model_zoo#3562]
can't compiled with vs2019 with error as follows:

the function  wrapMat2Tensor  can't be found!

why?
thanks!

**Comment by Wovchena** [comment]
Make sure you have clean environment and repos state. The function is here https://github.com/openvinotoolkit/open_model_zoo/blob/e3f46cc476402075b88be5ca983752268cc3150e/demos/common/cpp/utils/include/utils/ocv_common.hpp#L79

**Comment by danve-fan** [comment]
yes, it's ok, thanks!

**Comment by eaidova** [comment]
@danve-fan do you solv e the issue? Can we close it?
