### ISSUE TITLE
Import "openvino.model_zoo.model_api.models" could not be resolved (Pylancer (eportMissingImports) )

### ISSUE THREAD

**Issue by jiapei100** [openvinotoolkit/open_model_zoo#3566]
Where is the definition of **openvino.model_zoo** ??? Do I need to **install** `open_model_zoo` with **openvino**?? If so, how ???

For instance, the following lines in file [bert_question_answering_demo.py](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/bert_question_answering_demo/python/bert_question_answering_demo.py#L31-L34)

```python
from openvino.model_zoo.model_api.models import BertEmbedding, BertQuestionAnswering
from openvino.model_zoo.model_api.models.tokens_bert import text_to_tokens, load_vocab_file, ContextWindow
from openvino.model_zoo.model_api.pipelines import get_user_config, AsyncPipeline
from openvino.model_zoo.model_api.adapters import create_core, OpenvinoAdapter
```

**Comment by brmarkus** [comment]
Can you provide more context, please?
Have you found these "from openvino.model_zoo....." in an example-code?

**Comment by jiapei100** [comment]
My bad.... I found them, all here [https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/common/python](https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/common/python)
