### ISSUE TITLE
Intel person detection models

### ISSUE THREAD

**Issue by bbartling** [openvinotoolkit/open_model_zoo#3567]
This question is [originally asked on Stackoverflow](https://stackoverflow.com/questions/74115991/troubleshoot-openvino-model-output-for-cv2-rectangle) but I think there is something still not correct.

I am experimenting with the people models:

- person-detection-asl-0001
- person-detection-0202

And I am using a lot of the code from the openvino IPython notebooks [number 115 ](https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/115-async-api) that goes through a person detection example.

What's tripping me up is the post process function (shown below)  where there is what appears to be some sort of scaling on the model output for the `xmin, ymin, xmax, ymax` coordinates to draw a bounding box. Specifically, each coordinate is multiplied by the image shape like  `coordinate * image.shape` but I cant see any documentation for this in any of the person detection examples.

```
            xmin = int(max((xmin * image.shape[1]), 10))
            ymin = int(max((ymin * image.shape[0]), 10))
            xmax = int(min((xmax * image.shape[1]), image.shape[1] - 10))
            ymax = int(min((ymax * image.shape[0]), image.shape[0] - 10))
```

Entire function:
```
def postprocess(result, image, fps):
    """
    Define the postprocess function for output data
    
    :param: result: the inference results
            image: the orignal input frame
            fps: average throughput calculated for each frame
    :returns:
            image: the image with bounding box and fps message
    """
    detections = result.reshape(-1, 7)
    for i, detection in enumerate(detections):
        _, image_id, confidence, xmin, ymin, xmax, ymax = detection
        if confidence > 0.5:
            xmin = int(max((xmin * image.shape[1]), 10))
            ymin = int(max((ymin * image.shape[0]), 10))
            xmax = int(min((xmax * image.shape[1]), image.shape[1] - 10))
            ymax = int(min((ymax * image.shape[0]), image.shape[0] - 10))
            cv2.rectangle(image, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)
            cv2.putText(image, str(round(fps, 2)) + " fps", (5, 20), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 3) 
    return image
```

I am running[ this code](https://gist.github.com/bbartling/fbe0cd218d42a40ea69dd82964ee022d#file-app_0202-py) and it works for the `person-detection-0202` model from the recycled code from the IPython notebook and output looks good here's the model outputs:

![image](https://user-images.githubusercontent.com/29737117/196714692-fb6060cd-4f6a-46d1-807b-31df937c885c.png)

But when I try to use [this same code with a slight modification ](https://gist.github.com/bbartling/fbe0cd218d42a40ea69dd82964ee022d#file-app_asl-0001-py)  in the post process function to handle a different shape output as 0202 with the `person-detection-asl-0001` the scaling is off or something. If I use the same:
```
            xmin = int(max((xmin * image.shape[1]), 10))
            ymin = int(max((ymin * image.shape[0]), 10))
            xmax = int(min((xmax * image.shape[1]), image.shape[1] - 10))
            ymax = int(min((ymax * image.shape[0]), image.shape[0] - 10))
```

The `xmin, ymin, xmax, ymax` appear to be way off, especially the `xmin, ymin` are off the image shape. But if I remove the scaling from my code and just run this:
```
            xmin = int(max(xmin, 10))
            ymin = int(max(ymin, 10))
            xmax = int(min(xmax, image.shape[1] - 10))
            ymax = int(min(ymax, image.shape[0] - 10))
```

I get a bounding box but its off, like the x,y coordinates are missing something...I've tested this on serveral images and get the same results of bounding boxes showing up in the wrong place:
![image](https://user-images.githubusercontent.com/29737117/196716986-818c8e2c-9baa-47ef-ae9d-72566ad980d4.png)

**Comment by eaidova** [comment]
@bbartling person-detection-asl model requires output rescaling as:
```pyhton

input_h = model.input(0).shape[2]
input_w = model.input(0).shape[3]
initial_h, initial_w = frame.shape[:2]
scale_h, scale_w = initial_h / float(input_h), initial_w / float(input_w)
xmin = int(max((xmin * scale_w), 10))
            ymin = int(max((ymin * scale_h), 10))
            xmax = int(min((xmax * scale_w), image.shape[1] - 10))
            ymax = int(min((ymax *  scale_h), image.shape[0] - 10))
```
You can find more detailed example about this model usage in gesture recognition demo code:
https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/gesture_recognition_demo/python/gesture_recognition_demo/person_detector.py

**Comment by bbartling** [comment]
@eaidova Is there any chance you could give me one more tip? Sorry still learning and I apologize this is a lot of code to look at but I rewrote my code based on the link you provided in more of an object orientated format.

I'm stuck on the output of this function which returns the array.
```
    def process_output(self):
        """Converts network output to the internal format"""

        result = self.blob

        if result.shape[-1] == 5:  # format: [xmin, ymin, xmax, ymax, conf]
            return np.array([[self.scale_w, self.scale_h, self.scale_w, self.scale_h, 1.0]]) * result
```

And after this I would still need to loop through this output to draw the bounding boxes in cv2 like if `conf` is greater than `.5` or whatever threshold you want to use, right? I think the same or similar code snippet you in your last response.

Thanks for any tips or advice. My complete code so far in a [Gist.](https://gist.github.com/bbartling/fbe0cd218d42a40ea69dd82964ee022d#file-app_asl-0001_mod-py)

**Comment by eaidova** [comment]
@bbartling not a problem :) 
yes, this code just performs multiplying to scale without changing the detection format, for visualization using cv2, you still need iterate from all boxes and filter by score. In my snippet, I just simplify and adopt postprocessing in your provided example style.
`input_h` and `input_w` is image size after resizing (or at the same time model input size)
 `initial_h` and `initial_w` is the original image size (before resize)
you need just replace multiplying coefficient from `image.shape[0]` to `initial_h / float(input_h)` and `image.shape[1]` to `initial_w / float(input_w)` for getting correctly scaled boxes coordinates, other code parts looks good. You can try it just to make sure that model works as expected before big code refactoring :)

In OMZ demo case, we use object oriented approach because this demo uses video as input (it means that we need to process many frames but with the same input resolution parameters) and we want reuse previously calculated scales.
If you want to look how detection drawing used in this demo you can see it [here](https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/gesture_recognition_demo/python/gesture_recognition_demo.py#L198-L205). But I need to warn you that the main goal of demo not object detection, it is demo for running models in pipeline with model for gesture recognition, person detector used for tracking [person and cropping area of interest before inference of geasture recognition model. That is why here we check detection id, which maybe not required in your case

**Comment by bbartling** [comment]
Hi @eaidova thank you for all the tips so far : ) much appreciation on my end.

On this function that I grabbed from the link you sent me previously in the obj orientated example:https://github.com/openvinotoolkit/open_model_zoo/blob/master/demos/gesture_recognition_demo/python/gesture_recognition_demo/person_detector.py#:~:text=def%20_process_output(self,the%20internal%20format%22%22%22

More version:
```
    def process_output(self):
        """Converts network output to the internal format
        - intel models I have tested come in 2 forms
        - 5 outputs or 7 shape output (IF/ELSE)
        """
        
        if self.blob.shape[-1] == 5:
        
            # format: [xmin, ymin, xmax, ymax, conf]
            arr = np.array([[self.scale_w,
                             self.scale_h,
                             self.scale_w,
                             self.scale_h, 1.0]]) * self.blob

            for i, arr in enumerate(arr):
                xmin, ymin, xmax, ymax, confidence = arr

                xmin = int(xmin)
                ymin = int(ymin)
                xmax = int(xmax)
                ymax = int(ymax)

            self.plot_boxes(confidence, xmin, ymin, xmax, ymax)
        
        else:

            # format: [image_id, label, conf, xmin, ymin, xmax, ymax]
            out = np.array([[1.0,
                             self.scale_w,
                             self.scale_h,
                             self.scale_w,
                             self.scale_h]]) * self.blob[0, 0, :, 2:]

            arr = np.concatenate((out[:, 1:], out[:, 0].reshape([-1, 1])), axis=1)

            for i, arr in enumerate(arr):
                confidence, xmin, ymin, xmax, ymax = arr

                print(confidence, xmin, ymin, xmax, ymax)

                xmin = int(xmin)
                ymin = int(ymin)
                xmax = int(xmax)
                ymax = int(ymax)

            self.plot_boxes(confidence, xmin, ymin, xmax, ymax)
```

On the `else` side of the function above, I think I am doing something wrong to handle model output shapes that dont equal 5, like the [person-detection-0202](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-detection-0202). The `if` side of the function works just fine for the [person-detection-asl-0001](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/person-detection-asl-0001)

I just get lost on some of the numpy code on the `else` with the `np.concatenate` and reshape...any tips greatly appreciated. My code works I am doing something wrong to plot box coordinates around the person-detection-0202 type model. Thanks for anytime you may have....
