### ISSUE TITLE
reference paper for machine translation nar

### ISSUE THREAD

**Issue by zhuango** [openvinotoolkit/open_model_zoo#3568]
I'm working on the machine translation nar models released at : https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/machine-translation-nar-de-en-0002.
I want to learn the model structure of this model, but I failed to find any reference info about this model in this repo, like paper or code. Could please share more detail information about this model? Thanks a lot.

**Comment by andreyanufr** [comment]
Hi @zhuango . I am not the author of this model, but as I know you can find some technical details and description on the training pipeline: https://github.com/openvinotoolkit/training_extensions/tree/misc/misc/pytorch_toolkit/machine_translation

**Comment by zhuango** [comment]
Thanks @andreyanufr. That's exactly what I need.
