### ISSUE TITLE
Using deprecated versions of python packages (scipy, pandas, scikit-learn)

### ISSUE THREAD

**Issue by mikhailk62** [openvinotoolkit/open_model_zoo#3597]
Our team faced with problem using deprecated versions of python components into OMZ. The oldest one is 2 years old (scipy - 1.5.4). Use of obsolete versions of components is hard-coded in the requirements files:
```
numpy>=1.16.6,<=1.23.1
scipy~=1.5.4
pandas~=1.1.5
scikit-learn~=0.24.1
```
Using old versions of components does not allow using all the functionality of the libraries, and also forces to use a specific environment with old versions of components. In this case, there may be conflicting requirements from different projects.

We are requesting updates to the requirements for these components to be able to use the latest versions or near the latest. We aim to use the following versions: 

```
numpy - 1.22.3
scipy - 1.7.3
pandas - 1.5.1
scikit-learn - 1.0.2
```

**Comment by Wovchena** [comment]
numpy - 1.22.3 fits into numpy>=1.16.6,<=1.23.1

scipy was updated: https://github.com/openvinotoolkit/open_model_zoo/pull/3585

For pandas we have pandas>=1.1.5,<=1.3.5 now: https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/accuracy_checker/requirements-extra.in#L57 @eaidova, is there a reason to have upper bound?

scikit-learn is used only in image_retrieval_demo. I'm removing package constraint: https://github.com/openvinotoolkit/open_model_zoo/pull/3602

**Comment by eaidova** [comment]
updated
