### ISSUE TITLE
What was training dataset for facial-landmarks-35?

### ISSUE THREAD

**Issue by vadik6666** [openvinotoolkit/open_model_zoo#3618]
Hello! 
Can you please share information about `training dataset` for [facial-landmarks-35-adas-0002](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/facial-landmarks-35-adas-0002#example-and-landmarks-definition) model?
There are a [few words about validation](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/facial-landmarks-35-adas-0002#validation-dataset) but not `training dataset`.

**Comment by andreyanufr** [comment]
Hello! We used internal training dataset for this model. But we had annotation similar to this one: https://neerajkumar.org/databases/lfpw/ .

**Comment by vadik6666** [comment]
Thank you @andreyanufr for your answer. Can you please share with me the approximate size of your internal training dataset? Was it also nearly 1000 annotated images as in[https://neerajkumar.org/databases/lfpw/]( https://neerajkumar.org/databases/lfpw/)?

**Comment by andreyanufr** [comment]
I think it was bigger dataset with different head poses per person, but with less variety of people.

**Comment by vadik6666** [comment]
@andreyanufr thank you, I really appreciate your answer
