### ISSUE TITLE
The latest release of transformers==4.25.1 breaks the conversion of some models

### ISSUE THREAD

**Issue by mikhailk62** [openvinotoolkit/open_model_zoo#3620]
The conversion of some models for the openvino 2022.2.0 release started to failure. (in our case, the gpt-2 model).
After research, we found that a new version of the transformers library was released over the weekend https://pypi.org/project/transformers/#history
In previous runs, we had version 4.24.0, now it has become 4.25.1. After rolling back the version, the model began to convert.
We ask you to process and investigate this issue
[stdout.txt](https://github.com/openvinotoolkit/open_model_zoo/files/10154403/stdout.txt)

**Comment by eaidova** [comment]
@mikhailk62 thank you for your report,  the problem in incorrect import order in our case (4.25.1 has incompatible model format in comparision with previous releases that is why you got segfault for loading)
I prepared fix for resolving this issue:
https://github.com/openvinotoolkit/open_model_zoo/pull/3621
