### ISSUE TITLE
Can the object_detection.py intel code support yolov5?

### ISSUE THREAD

**Issue by glennford49** [openvinotoolkit/open_model_zoo#3630]
I have tried to run it with exported  yolov5n.xml, but failed to run, architecture availble is only yolox.

**Comment by Wovchena** [comment]
No, object_detection_demo.py doesn't support yolov5

**Comment by glennford49** [comment]
Is it possible to run exported yolov5 to openvino in openvino environment?

**Comment by Wovchena** [comment]
I guess so. It's just demos which don't have pre and postprocessing implemented for yolov5. You should be able to run say [benchmark_tool](https://github.com/openvinotoolkit/openvino/tree/master/tools/benchmark_tool) with yolov5

**Comment by glennford49** [comment]
I have successfully run exported yolov5 to openvino model using both on intel cpu and ncs2, but running it on raspberry throws an error, so i think running exported model on benchmark_tool is just fine.
