### ISSUE TITLE
Use batch size bigger than 1 for head-pose-model

### ISSUE THREAD

**Issue by vadik6666** [openvinotoolkit/open_model_zoo#3637]
Hi, is it possible to use [head-pose-estimation-adas-001](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/head-pose-estimation-adas-0001) model from model-zoo with a batch size 2 or bigger?
In the model page the input described as a `1, 3, 60, 60`
Doing simply model([input]), where input is e.g. `2, 3, 60, 60` gives an error `RuntimeError: The input blob size is not equal to the network input size: got 21600 expecting 10800`
Maybe there is way? Somehow convert to openvino with batch dimension not fixed, but to do this I need original model, am correct?

**Comment by eaidova** [comment]
@vadik6666 you can reshape openvino model for specific batch size, you can find tutorial hows to do it here: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/002-openvino-api/002-openvino-api.ipynb
