### ISSUE TITLE
How to run text_detection_demo C++?

### ISSUE THREAD

**Issue by Pipickin** [openvinotoolkit/open_model_zoo#3640]
Hello, everybody! 
I tried to run text_detection_demo from this link https://docs.openvino.ai/latest/omz_demos_text_detection_demo_cpp.html but when I have run this code I'v got `bash: ./text_detection_demo: No such file or directory`

I installed OpenVINO RunTime for C++ as follow here https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_from_archive_linux.html#doxid-openvino-docs-install-guides-installing-openvino-from-archive-linux and OpenVINO Development Tools from here https://docs.openvino.ai/latest/openvino_docs_install_guides_install_dev_tools.html#install-dev-tools. I also ran inference from this link  https://docs.openvino.ai/latest/openvino_docs_get_started_get_started_demos.html#:~:text=Step%204%3A%20Run%20Inference%20on%20a%20Sample and this code worked for me, but I have no idea how to run text detection demo. I just cloned model_zoo and downloaded the correspondence models, but in `open_model_zoo/demos/text_detection_demo/cpp`  there are only files: 
`CMakeLists.txt  intel     models.lst  README.md  text_detection_demo.hpp
include         main.cpp  public      src        text_detection_demo.jpg`

Could you tell what to do to run this demo? Thank you in advance!

**Comment by Wovchena** [comment]
Hi. You need to build demos: https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#build-the-demo-applications

**Comment by Pipickin** [comment]
> Hi. You need to build demos: https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#build-the-demo-applications

Thank You! It works for me
