### ISSUE TITLE
What is the mean value and std value for the pretrained model in the model zoos

### ISSUE THREAD

**Issue by htangcreaxon** [openvinotoolkit/open_model_zoo#3660]
Hi, I'm here to ask what's mean and std for the [ssdlite_mobilenet_v2](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/ssdlite_mobilenet_v2).  Thanks.
It seems the model trained from the tensorflow but I can't find the exact mean and std.

**Comment by Wovchena** [comment]
Hi. My guess is mean=0, std=1

**Comment by htangcreaxon** [comment]
NVM, I'll verify it if I have time. Thanks... I'll reopen this issue later on once I figure it out... Should be useful if your application requires that parameter...

> Hi. My guess is mean=0, std=1
