### ISSUE TITLE
mask_rcnn_demo: command not found

### ISSUE THREAD

**Issue by VicencPB** [openvinotoolkit/open_model_zoo#3678]
Hi, I am trying to run the mask_rcnn_demo in Ubuntu.

I have dowwnloaded and converted the models without errors:

omz_downloader --list models.lst

omz_converter --list models.lst

But I don't know how to execute the mask_rcnn_demo; the OS can't find the executable file.

I would appreciate very much any help on this issue (where is mask_rcnn_located ?)

Sincerely

Vicenç Parisi

**Comment by Wovchena** [comment]
Hi. You need to build demos https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos#build-the-demo-applications

**Comment by VicencPB** [comment]
Thank you!!
