### ISSUE TITLE
Correct annotation file format (.json) for post-training tool in action recognition model

### ISSUE THREAD

**Issue by edgarmg91** [openvinotoolkit/open_model_zoo#3686]
Thanks a lot for your amazing work!

I trained a custom model for action recognition using the UFC-101 dataset format, which I was also able to convert into .xml format using the model optimizer tool. 

Currently, I want to quantize this model to FP16-INT8. By looking in the documentation: 

https://docs.openvino.ai/2020.4/pot_README.html

https://docs.openvino.ai/2021.2/pot_configs_examples_README.html

I was able to run some samples with no issues. As the action recognition task is not available as sample, I looked deeper in the documentation and found that I require: 

* Define a profer configuration file.
* Prepare the validation dataset in the correct format. 
* Generate a valid annotation file (.json) for the dataset.
* Look for a compatible accuracy_check.yml file.

For the accuracy check file, I think i can use the provided in the action recognition sample:
https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/action-recognition-0001/accuracy-check.yml

This accuracy tool uses the dataset sample "kinetics-400" as source, which parameters are described here:

https://github.com/openvinotoolkit/open_model_zoo/blob/master/data/dataset_definitions.yml

this dataset type uses the *clip_action_recognition* converter, which format is described here: 

https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/README.md

According the information, I need to preprocess the validation according the following tutorial: 

https://github.com/openvinotoolkit/training_extensions/blob/misc/models/action_recognition/model_templates/custom-action-recognition/README.md#3-prepare-data

Also, I need an annotation file (.json) with the information related to the validation dataset. Nevertheless, the standard kinetics-400.json file is not compatible:

https://www.deepmind.com/open-source/kinetics

as when I use them into the converter (for testing only), the following error appears:

```
 ges/openvino/tools/accuracy_checker/annotation_converters/action_recognition.py", line 116, in get_meta
    label_map = dict(enumerate(full_annotation['labels']))
 KeyError: 'labels'
```

which means that the format of the .json file is missing some details. I have searched for days in the documentation but I cannot find a sample of how the annotation file should be generated or written. 

Is there any sample about the format of the .json file for this type of model?. Or I miss some step of the tutorial where it is generated?.

I also find a tool to generate the .json file here: 

https://github.com/openvinotoolkit/open_model_zoo/tree/master/tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters 

```

clip_action_recognition - converts annotation video-based action recognition datasets. Before conversion validation set should be preprocessed using approach described [here](https://github.com/openvinotoolkit/training_extensions/blob/misc/models/action_recognition/model_templates/custom-action-recognition/README.md#3-prepare-data).
      annotation_file - path to annotation file in json format.
      data_dir - path to directory with prepared data (e. g. data/kinetics/frames_data).
      clips_per_video - number of clips per video (Optional, default 3).
      clip_duration - clip duration (Optional, default 16)
      temporal_stride - temporal stride for frames selection (Optional, default 2).
      numpy_input - allows usage numpy files instead images. It can be useful if data required difficult preprocessing steps (e.g. conversion to optical flow) (Optional, default False)
      subset - dataset split: train, validation or test (Optional, default validation).
      dataset_meta_file - path to json file with dataset meta (e.g. label_map, color_encoding).Optional, more details in [Customizing dataset meta](https://github.com/openvinotoolkit/open_model_zoo/blob/master/tools/accuracy_checker/openvino/tools/accuracy_checker/annotation_converters/README.md#customizing-dataset-meta) section.
      num_samples - select first n samples from dataset (Optional, if not provided full subset of samples will be used).
```

Nevertheless, the documentation didn't specify how the  annotation file should be created.

Thanks in advance for your response!

**Comment by eaidova** [comment]
@edgarmg91 as you already have dataset in own format and code for your trained model, I think it can be easier to go with new nncf.quantize API, you can provide your data loader to this API and define transformation function to fit data to openvino model input
https://github.com/openvinotoolkit/nncf/blob/develop/docs/compression_algorithms/post_training/Quantization.md
Unfortunatly, we still has no example for action recognition, but you can see example for classification model (I think it should be similar for action recognition too)

https://github.com/openvinotoolkit/nncf/tree/develop/examples/post_training_quantization/openvino/mobilenet_v2

**Comment by edgarmg91** [comment]
@eaidova thanks a lot for your quick response! 

Amazing new tool!, it will be of great help that it allows to do the complete process in python.

As an update I found the way to introduce the dataset in the correct format but I am still having issues with the converter. I will try with the nncf API and will provide you a feedback of the results.

Thanks again for the support!

**Comment by edgarmg91** [comment]
Hi @eaidova !. 

I was able to quantize my model very quickly using the nncf.quantize API by just modifying the provided sample with my dataloader and model: 

https://github.com/openvinotoolkit/nncf/tree/develop/examples/post_training_quantization/openvino/mobilenet_v2 

Thanks a lot for your support!
