### ISSUE TITLE
How to run single-human-pose-estimation-0001 in dlstreamer

### ISSUE THREAD

**Issue by shekarneo** [openvinotoolkit/open_model_zoo#3691]
How to run single-human-pose-estimation-0001 in dlstreamer
I am using unbuntu-18.04 with openvino 2021.4 docker 

I tried to use model proc for this from the latest openvino repo, but it gives some error.

0:00:07.049200302  1975 0x55f8b42bb450 ERROR             GVA_common post_processor.cpp:202:PostProcessor: Converter "keypoints" is not implemented.
Pipeline is PREROLLED ...0 %)

**Comment by Wovchena** [comment]
That old combination of OS and OpenVINO isn't supported anymore by dlstreamer. If you are still interested, update the environment. If the issue reproduces, submit an issue to a dlstreamer repo.
