### ISSUE TITLE
build_demos_msvc Failed on ADL i5 win11 by VS2019 Openvino2022.3 archives runtime

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/open_model_zoo#3713]
setupvars.bat
cd demos
build_demos_msvc.bat
>Searching for the latest Visual Studio...
Creating Visual Studio 16 2019 x64 files in C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build...
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:140 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

###############|| Build Open Model Zoo Demos using MS Visual Studio ||###############

cmake --build . --config Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
Error

**Comment by Wovchena** [comment]
Hi. Before running `build_demos_msvc.bat` set `OpenCV_DIR` env var to a folder containing `OpenCVConfig.cmake` for example for me it is `set OpenCV_DIR=C:\Users\vzlobin\r\opencv\build`. Usually you can find `OpenCVConfig.cmake` in build folder if you compiled OpenCV yourself or in `cmake` folder if you installed OpenCV.

**Comment by KiwiHana** [comment]
hi Wovchena,
I installed opencv and add OpenCV_DIR=C:\Users\vzlobin\r\opencv\build. But part of build_demos_msvc.bat failed.

C:\Users\NUC12\Downloads\open_model_zoo\demos>build_demos_msvc.bat
Searching for the latest Visual Studio...
Creating Visual Studio 16 2019 x64 files in C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build...
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc16
-- OpenCV STATIC: OFF
-- Found OpenCV: C:/Users/NUC12/opencv/build (found version "4.7.0") found components: core highgui videoio imgproc imgcodecs
-- Found OpenCV 4.7.0 in C:/Users/NUC12/opencv/build/x64/vc16/lib
-- You might need to add C:\Users\NUC12\opencv\build\x64\vc16\bin to your PATH to be able to run your applications.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
CMake Error at CMakeLists.txt:143 (add_subdirectory):
  The source directory

    C:/Users/NUC12/Downloads/open_model_zoo/demos/thirdparty/gflags

  does not contain a CMakeLists.txt file.


-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc16
-- OpenCV STATIC: OFF
-- Found OpenCV: C:/Users/NUC12/opencv/build (found version "4.7.0") found components: gapi
-- Found OpenCV 4.7.0 in C:/Users/NUC12/opencv/build/x64/vc16/lib
-- You might need to add C:\Users\NUC12\opencv\build\x64\vc16\bin to your PATH to be able to run your applications.
-- Configuring incomplete, errors occurred!

###############|| Build Open Model Zoo Demos using MS Visual Studio ||###############

cmake --build . --config Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
Error

SSSSSSSSSSSSSSSSSS: lack file in C:/Users/NUC12/Downloads/open_model_zoo/demos/thirdparty/gflags

####################################################******************************************
>build_demos_msvc.bat
Searching for the latest Visual Studio...
Creating Visual Studio 16 2019 x64 files in C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build...
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc16
-- OpenCV STATIC: OFF
-- Found OpenCV: C:/Users/NUC12/opencv/build (found version "4.7.0") found components: core highgui videoio imgproc imgcodecs
-- Found OpenCV 4.7.0 in C:/Users/NUC12/opencv/build/x64/vc16/lib
-- You might need to add C:\Users\NUC12\opencv\build\x64\vc16\bin to your PATH to be able to run your applications.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Check size of __int32
-- Check size of __int32 - done
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc16
-- OpenCV STATIC: OFF
-- Found OpenCV: C:/Users/NUC12/opencv/build (found version "4.7.0") found components: gapi
-- Found OpenCV 4.7.0 in C:/Users/NUC12/opencv/build/x64/vc16/lib
-- You might need to add C:\Users\NUC12\opencv\build\x64\vc16\bin to your PATH to be able to run your applications.
-- Configuring done (4.7s)
-- Generating done (0.2s)
-- Build files have been written to: C:/Users/NUC12/Documents/Intel/OpenVINO/omz_demos_build

###############|| Build Open Model Zoo Demos using MS Visual Studio ||###############

cmake --build . --config Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/thirdparty/gflags/CMakeLists.txt
  gflags.cc
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/common/cpp/monitors/CMakeLists.txt
  cpu_monitor.cpp
  memory_monitor.cpp
  gflags_reporting.cc
  gflags_completions.cc
  presenter.cpp
  windows_port.cc
  Generating Code...
  query_wrapper.cpp
  Generating Code...
  gflags_nothreads_static.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\gflags_not
  hreads_static.lib
  monitors.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\monitors.lib
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/common/cpp/utils/CMakeLists.txt
  args_helper.cpp
  config_factory.cpp
  image_utils.cpp
  images_capture.cpp
  kuhn_munkres.cpp
  performance_metrics.cpp
  Generating Code...
  utils.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\utils.lib
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/mri_reconstruction_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/gaze_estimation_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/common/cpp_gapi/utils_gapi/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/interactive_face_detection_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/noise_suppression_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/social_distance_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/multi_channel_common/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/text_detection_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/security_barrier_camera_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/smart_classroom_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/crossroad_camera_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/mask_rcnn_demo/cpp/CMakeLists.txt
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  cnn.cpp
  stream_source.cpp
  action_detector.cpp
  mri_reconstruction_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\mri_recons
  truction_demo.exe
  main.cpp
C:\Users\NUC12\Downloads\open_model_zoo\demos\text_detection_demo\cpp\src\cnn.cpp(55,68): warning C4244: '=': conversio
n from '_Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\text_detection_de
mo\cpp\text_detection_demo.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\text_detection_demo\cpp\src\cnn.cpp(56,127): warning C4244: 'argument': c
onversion from '_Ty' to '_Tp', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\text_dete
ction_demo\cpp\text_detection_demo.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
          and
          [
              _Tp=int
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\text_detection_demo\cpp\src\cnn.cpp(56,76): warning C4244: 'argument': co
nversion from '_Ty' to '_Tp', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\text_detec
tion_demo\cpp\text_detection_demo.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
          and
          [
              _Tp=int
          ]
  mask_rcnn_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\mask_rcnn_demo.exe
  main.cpp
  text_detection.cpp
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/gesture_recognition_demo/cpp_gapi/CMakeLists.txt
  main.cpp
  align_transform.cpp
  utils_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\utils_gapi.lib
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/common/cpp/models/CMakeLists.txt
  associative_embedding_decoder.cpp
  geodist.cpp
  classification_model.cpp
  text_recognition.cpp
  Generating Code...
  cnn.cpp
  custom_kernels.cpp
  security_barrier_camera_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\secur
  ity_barrier_camera_demo.exe
  deblurring_model.cpp
  crossroad_camera_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\crossroad_ca
  mera_demo.exe
  Generating Code...
  noise_suppression_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\noise_suppr
  ession_demo.exe
  social_distance_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\social_distan
  ce_demo.exe
  CMakeCXXCompilerId.cpp
  decoder.cpp
  tracker.cpp
  CMakeCXXCompilerId.cpp
  main.cpp
  detector.cpp
  utils.cpp
  graph.cpp
  detection_model.cpp
  visualizer.cpp
  eye_state_estimator.cpp
  logger.cpp
  text_detection_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\text_detection
  _demo.exe
  detectors.cpp
  Generating Code...
  input.cpp
  detection_model_centernet.cpp
C:\Users\NUC12\Downloads\open_model_zoo\demos\interactive_face_detection_demo\cpp\detectors.cpp(52,51): warning C4244:
'=': conversion from 'const _Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_bui
ld\interactive_face_detection_demo\cpp\interactive_face_detection_demo.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\interactive_face_detection_demo\cpp\detectors.cpp(67,43): warning C4244:
'=': conversion from 'const _Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_bui
ld\interactive_face_detection_demo\cpp\interactive_face_detection_demo.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
  face_detector.cpp
  reid_gallery.cpp
  face.cpp
  gesture_recognition_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\gest
  ure_recognition_demo_gapi.exe
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/gaze_estimation_demo/cpp_gapi/CMakeLists.txt
  output.cpp
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/smart_classroom_demo/cpp_gapi/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/background_subtraction_demo/cpp_gapi/CMakeLists.tx
  t
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/interactive_face_detection_demo/cpp_gapi/CMakeList
  s.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/face_detection_mtcnn_demo/cpp_gapi/CMakeLists.txt
  main.cpp
  detection_model_faceboxes.cpp
  face_inference_results.cpp
  tracker.cpp
  main.cpp
  gaze_estimator.cpp
  perf_timer.cpp
  threading.cpp
  Generating Code...
  detection_model_retinaface.cpp
  main.cpp
  custom_kernels.cpp
  Generating Code...
  visualizer.cpp
  head_pose_estimator.cpp
  detection_model_retinaface_pt.cpp
  Generating Code...
  Generating Code...
  ie_wrapper.cpp
  action_detector.cpp
  background_subtraction_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\b
  ackground_subtraction_demo_gapi.exe
  main.cpp
  detection_model_ssd.cpp
  face.cpp
  align_transform.cpp
  main.cpp
  main.cpp
  landmarks_estimator.cpp
  custom_kernels.cpp
  detection_model_yolo.cpp
  detector.cpp
  results_marker.cpp
  drawing_helper.cpp
  custom_kernels.cpp
  custom_kernels.cpp
  logger.cpp
  visualizer.cpp
  face_inference_results.cpp
  detection_model_yolov3_onnx.cpp
  reid_gallery.cpp
  Generating Code...
  utils.cpp
  results_marker.cpp
  tracker.cpp
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolov3_onnx.cpp(126,11): warning C4
244: 'initializing': conversion from 'const _Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVI
NO\omz_demos_build\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolov3_onnx.cpp(151,23): warning C4
244: 'initializing': conversion from 'const _Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVI
NO\omz_demos_build\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
  Generating Code...
  Generating Code...
  face_detection_mtcnn_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\fac
  e_detection_mtcnn_demo_gapi.exe
  detection_model_yolox.cpp
  multi_channel_common.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\multi_channel
  _common.lib
  Generating Code...
  interactive_face_detection_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\in
  teractive_face_detection_demo.exe
  utils.cpp
  smart_classroom_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\smart_classro
  om_demo.exe
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/multi_channel_object_detection_demo_yolov3/cpp/CMa
  keLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/multi_channel_human_pose_estimation_demo/cpp/CMake
  Lists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/multi_channel_face_detection_demo/cpp/CMakeLists.t
  xt
  main.cpp
  Generating Code...
  human_pose.cpp
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolox.cpp(179,53): warning C4244: '
argument': conversion from 'double' to 'const float', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\om
z_demos_build\common\cpp\models\models.vcxproj]
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolox.cpp(188,36): warning C4244: '
=': conversion from '_Ty' to 'unsigned int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_b
uild\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolox.cpp(189,47): warning C4244: '
argument': conversion from '_Ty' to 'int', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_bui
ld\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=uint64_t
          ]
  main.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xutility(149,77): warni
ng C4244: 'argument': conversion from 'double' to 'float', possible loss of data [C:\Users\NUC12\Documents\Intel\OpenVI
NO\omz_demos_build\common\cpp\models\models.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(2014): message :
 see reference to function template instantiation 'void std::_Construct_in_place<_Ty,const int&,const int&,double&,doub
le&>(_Ty &,const int &,const int &,double &,double &) noexcept(false)' being compiled [C:\Users\NUC12\Documents\Intel\O
penVINO\omz_demos_build\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=InternalScaleData
          ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(2726): message :
 see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const int&,const int&,dou
ble&,double&>(const int &,const int &,double &,double &)' being compiled [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_d
emos_build\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=InternalScaleData
          ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(2726): message :
 see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<const int&,const int&,dou
ble&,double&>(const int &,const int &,double &,double &)' being compiled [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_d
emos_build\common\cpp\models\models.vcxproj]
          with
          [
              _Ty=InternalScaleData
          ]
C:\Users\NUC12\Downloads\open_model_zoo\demos\common\cpp\models\src\detection_model_yolox.cpp(122): message : see refer
ence to function template instantiation 'std::shared_ptr<InternalScaleData> std::make_shared<InternalScaleData,const in
t&,const int&,double&,double&>(const int &,const int &,double &,double &)' being compiled [C:\Users\NUC12\Documents\Int
el\OpenVINO\omz_demos_build\common\cpp\models\models.vcxproj]
  main.cpp
  hpe_model_associative_embedding.cpp
  smart_classroom_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\smart_cl
  assroom_demo_gapi.exe
  interactive_face_detection_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Relea
  se\interactive_face_detection_demo_gapi.exe
CMakeCXXCompilerId.cpp.obj : error LNK2005: main already defined in main.obj [C:\Users\NUC12\Documents\Intel\OpenVINO\o
mz_demos_build\gaze_estimation_demo\cpp\gaze_estimation_demo.vcxproj]
CMakeCXXCompilerId.cpp.obj : error LNK2005: main already defined in main.obj [C:\Users\NUC12\Documents\Intel\OpenVINO\o
mz_demos_build\gaze_estimation_demo\cpp\gaze_estimation_demo.vcxproj]
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_compiler" (?info_compiler@@3PEBDEB) already define
d in CMakeCXXCompilerId.cpp.obj [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\gaze_estimation_demo\cpp\gaze_
estimation_demo.vcxproj]
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_platform" (?info_platform@@3PEBDEB) already define
d in CMakeCXXCompilerId.cpp.obj [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\gaze_estimation_demo\cpp\gaze_
estimation_demo.vcxproj]
CMakeCXXCompilerId.cpp.obj : error LNK2005: "char const * const info_arch" (?info_arch@@3PEBDEB) already defined in CMa
keCXXCompilerId.cpp.obj [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\gaze_estimation_demo\cpp\gaze_estimati
on_demo.vcxproj]
  gaze_estimation_demo_gapi.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\gaze_est
  imation_demo_gapi.exe
C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\gaze_estimation_demo.exe : fatal error LNK1169:
 one or more multiply defined symbols found [C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\gaze_estimation_de
mo\cpp\gaze_estimation_demo.vcxproj]
  peak.cpp
  multi_channel_object_detection_demo_yolov3.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64
  \Release\multi_channel_object_detection_demo_yolov3.exe
  hpe_model_openpose.cpp
  postprocess.cpp
  multi_channel_face_detection_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\
  multi_channel_face_detection_demo.exe
  postprocessor.cpp
  image_model.cpp
  render_human_pose.cpp
  Generating Code...
  jpeg_restoration_model.cpp
  multi_channel_human_pose_estimation_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\R
  elease\multi_channel_human_pose_estimation_demo.exe
  model_base.cpp
  openpose_decoder.cpp
  segmentation_model.cpp
  style_transfer_model.cpp
  Generating Code...
  Compiling...
  super_resolution_model.cpp
  Generating Code...
  models.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\models.lib
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/common/cpp/pipelines/CMakeLists.txt
  async_pipeline.cpp
  requests_pool.cpp
  Generating Code...
  pipelines.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\pipelines.lib
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/image_processing_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/classification_benchmark_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/segmentation_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/human_pose_estimation_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/pedestrian_tracker_demo/cpp/CMakeLists.txt
  Building Custom Rule C:/Users/NUC12/Downloads/open_model_zoo/demos/object_detection_demo/cpp/CMakeLists.txt
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  main.cpp
  cnn.cpp
  visualizer.cpp
  segmentation_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\segmentation_dem
  o.exe
  human_pose_estimation_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\human_p
  ose_estimation_demo.exe
  classification_benchmark_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\clas
  sification_benchmark_demo.exe
  object_detection_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\object_detec
  tion_demo.exe
  distance.cpp
  Generating Code...
  tracker.cpp
  image_processing_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\image_proces
  sing_demo.exe
  utils.cpp
  Generating Code...
  pedestrian_tracker_demo.vcxproj -> C:\Users\NUC12\Documents\Intel\OpenVINO\omz_demos_build\intel64\Release\pedestrian
  _tracker_demo.exe
Error

**Comment by KiwiHana** [comment]
solved. Use git clone code instead of download code.zip
