### ISSUE TITLE
Trouble running demos on ARM CPU

### ISSUE THREAD

**Issue by ashwanth-07** [openvinotoolkit/open_model_zoo#3719]
I install ARM CPU plugin for openvino toolkit version 2022.1
When I tried running an object detection demo using the following command:
python3 object_detection_demo.py -i ~/Downloads/person-bicycle-car-detection.mp4 -m ~/Downloads/person-vehicle-bike-detection-crossroad-0078.xml -at ssd -d CPU

I got the following error:
RuntimeError: Arm Plugin: Nodes from RMNet_SSD are not supported by plugin:
	mbox_conf_softmax (Softmax.0)
	detection_out (DetectionOutput.0)

Kindly help resolve the issue.
I would like to run the same model in MYRIAD as well.

**Comment by alvoron** [comment]
Duplication of https://github.com/openvinotoolkit/openvino/issues/16352
