### ISSUE TITLE
Wrong Accuracy Metric in Speech Recognition Public Models table

### ISSUE THREAD

**Issue by sawradip** [openvinotoolkit/open_model_zoo#3724]
In the Model Zoo public [Models page](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/public/index.md), under the **Speech Recognition Models** models, The accuracy metric that is mentioned is **WER(Word Error Rate),** which is opposite to **Accuracy**. But it is mentioned as **Accuracy**. 

This is confusing for the users finding the best model, should I fix it?

**Comment by eaidova** [comment]
@sawradip this header used for consistency readme template with other models, under accuracy we understand any metric which helps to understand model result work in accuracy terms including error rates, so your changes are also can confuse users who has the same level of understanding

**Comment by sawradip** [comment]
If that is intentional, alright. But myself was stnned a little at first as I dodn't know that it could also be error rate.

Could we add some notice like "Lower is better", when the metrics are inverted?
