### ISSUE TITLE
Converted model error

### ISSUE THREAD

**Issue by Dev-Divyendh** [openvinotoolkit/open_model_zoo#3731]
i am using omz_converter for my project. After converting yolo-tiny-v4-tf model using the following command, 
`omz_converter --name=yolo-v4-tiny-tf --mo=D:\fyp_project\openvino_env\Lib\site-packages\openvino\tools\mo\mo.py` 

I tried to use the converted model on Raspberry pi 4b with the help of Intel Movidius Stick 2 (NCS2) using the following command:
`python3 object_detection_demo.py -i ~/Downloads/person-bicycle-car-detection.mp4 -m ~/Downloads/yolo-v4-tiny-tf/FP32/yolo-v4-tiny-tf.xml -at yolo -d MYRIAD.`

I have tried both FP16 and FP32 but got this error in both the cases:
```
tensor = tensor.reshape(N, -1, K, H, W)
ValueError: cannot reshape array of size 43095 into shape (1,newaxis,85,13,255)
```
Kindly help me to resolve this issue.

**Comment by Wovchena** [comment]
This is a demo problem. Until it is fixed you can use C++ object_detection_demo

**Comment by Wovchena** [comment]
You should run object_detection_demo.py with at yolov4
