### ISSUE TITLE
Converting self-made trained ML model using omz_converter

### ISSUE THREAD

**Issue by Dev-Divyendh** [openvinotoolkit/open_model_zoo#3732]
I am using omz_converter in my project. I have used a facial expression detection dataset to train a ML model. Now I have to convert this ipynb file to the required file format so that I will be able to use omz_converter to convert this file and use this in my project on Raspberry pi4 B.

Please help me with the steps that has to be followed in order to achieve this.

**Comment by Wovchena** [comment]
`omz_converter` is just a wrapper over `mo`. I suggest you move from `omz_converter` to `mo`. You should be able to just put a command calling `mo` with appropriate arguments.

**Comment by Dev-Divyendh** [comment]
I have a model that is stored in .pkl (pickle) format. How to use `mo` over this file so that I can run this model using Intel movidius stick on Raspberry pi 4B. 

If possible can you please list down the steps to be followed.

**Comment by Wovchena** [comment]
My work usually doesn't involve this so I can't help much. You need to follow a common instructions how to convert the model from a given framework. There is nothing specific to Intel movidius stick or Raspberry pi 4B at this step. But first you need to convert your pickle to one of the supported frameworks: tensorflow, onnx, etc.
