### ISSUE TITLE
Error while compiling a g-api model 

### ISSUE THREAD

**Issue by Dev-Divyendh** [openvinotoolkit/open_model_zoo#3740]
I am trying to run an interactive face detection model from open model zoo on raspberry pi 4B. While trying to run the model using gapi I get the following error:

`[ ERROR ] G-API has been compiled without OpenVINO IE support`

I have already installed the intel MYRIAD plugin and ARM CPU plugins that are required for the project.
These are the versions of librarires and their respective cmake commands that I have used:

1. Opencv - 4.7 
`cmake ../ -DWITH_INF_ENGINE=ON -DCMAKE_BUILD_TYPE=Release`

2. Openvino - 2022/3/0
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/pi/openvino_dist -DENABLE_INTEL_MYRIAD=ON -DENABLE_INTEL_CPU=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_CLDNN=OFF -DENABLE_AUTO=ON -DENABLE_MULTI=ON -DENABLE_HETERO=ON -DENABLE_GAPI_PREPROCESSING=ON -DENABLE_TEMPLATE=OFF -DENABLE_TESTS=OFF -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_NCC_STYLE=OFF -DENABLE_SSE42=OFF -DTHREADING=SEQ -DENABLE_OPENCV=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=$(which python3.7) -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..`

**Comment by dharun-narayanan** [comment]
Follow up on the above mentioned issue, I was able to solve the error by changing the opencv cmake command to 
`cmake -DCMAKE_BUILD_TYPE=Release -DWITH_INF_ENGINE=ON -DCMAKE_INSTALL_PREFIX=/usr/local .. &&  make -j4`

I tried running the model again but got this error:
`[ ERROR ] Data object reached during unroll wasn't found in Protocol`

I used this command to run my model:
`./interactive_face_detection_demo_gapi -i /dev/video0 -m /home/pi/Downloads/facial_detection1/face-detection-adas-0001.xml --mag /home/pi/Downloads/facial_detection1/age-gender-recognition-retail-0013.xml --mhp /home/pi/Downloads/facial_detection1/head-pose-estimation-adas-0001.xml --mem /home/pi/Downloads/facial_detection1/emotions-recognition-retail-0003.xml --mlm /home/pi/Downloads/facial_detection1/facial-landmarks-35-adas-0002.xml -d MYRIAD --dag MYRIAD --dhp MYRIAD --dem MYRIAD --dlm MYRIAD
`

Kindly help to resolve the issue

**Comment by Wovchena** [comment]
Hi. I've never seen this error message. You can try running the demo on a more regular system on intel CPU to make sure you don't do something strange and the demo works for you in a common setup.
Also, as a guess, the error may come from opencv while it tries to read `/dev/video0`. Try removing everything from the demo code and keep just frame reading and showing and see if the problem disappears.

**Comment by eaidova** [comment]
@dmatveev @TolyaTalamanov could you please help to check correctness of building opencv with g-api support?
Thanks!

**Comment by TolyaTalamanov** [comment]
> @dmatveev @TolyaTalamanov could you please help to check correctness of building opencv with g-api support? Thanks!

Hi, build command seems be correct. Just in case there is an instruction for that: https://github.com/opencv/opencv/wiki/Using-G-API-with-OpenVINO-Toolkit

One nuance here, if you build `OpenVINO` from source, it's required to explicitly provide `-DInferenceEngine_DIR=<path-to-build>` to opencv cmake otherwise it'd be enough to just call `setupvars.sh`

As for the error, it comes from `G-API`, working on reproducing this...
@dharun-narayanan Could you share the `opencv` commit are you using?

**Comment by dharun-narayanan** [comment]
Cmake Installation:
wget https://github.com/Kitware/CMake/releases/download/v3.25.0/cmake-3.25.0.tar.gz
tar xvzf cmake-3.25.0.tar.gz
cd ~/cmake-3.25.0
./bootstrap
make -j4
sudo make install

Cmake 3.25.0 version was installed that was mentioned in the documention for openvino environment for raspberry pi
https://www.intel.in/content/www/in/en/support/articles/000057005/boards-and-kits.html

**Comment by TolyaTalamanov** [comment]
@dharun-narayanan could you share the `opencv` & `open_model_zoo` commit hashes, please?

Demo is working fine on my setup:
`opencv`: d2143bcd44edfde1438aa4baf56e688d481d6158 (master)
`open_model_zoo`: e7ea6626e02dab2f9680d940bc504e75151dda63 (master)

`cmd`: 
```
./interactive_face_detection_demo_gapi -i <video> -m ~/workspace/models/intel/face-detection-adas-0001/FP32/face-detection-adas-0001.xml --mag ~/workspace/models/intel/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml --mhp ~/workspace/models/intel/head-pose-estimation-adas-0001/FP32/head-pose-estimation-adas-0001.xml --mem ~/workspace/models/intel/emotions-recognition-retail-0003/FP32/emotions-recognition-retail-0003.xml --mlm ~/workspace/models/intel/facial-landmarks-35-adas-0002/FP32/facial-landmarks-35-adas-0002.xml -d CPU --dag CPU --dhp CPU --dem CPU --dlm CPU
```

I've downloaded all models by using: 
```
tools/model_tools/downloader.py --name <name> --o <output_dir>
```

**Comment by dharun-narayanan** [comment]
@TolyaTalamanov I have attached the steps that i have followed during the installation of openvino environment on raspberry pi 4
I have mentioned the version in brackets for each package installed.

[Building Open Source OpenVINO.docx](https://github.com/openvinotoolkit/open_model_zoo/files/11513440/Building.Open.Source.OpenVINO.docx)

**Comment by TolyaTalamanov** [comment]
> @TolyaTalamanov I have attached the steps that i have followed during the installation of openvino environment on raspberry pi 4 I have mentioned the version in brackets for each package installed.
> 
> [Building Open Source OpenVINO.docx](https://github.com/openvinotoolkit/open_model_zoo/files/11513440/Building.Open.Source.OpenVINO.docx)

I can see that you're using `4.7.0` branch for `opencv`.
```
git clone --depth 1 --branch 4.7.0 https://github.com/opencv/opencv.git
```
and `2022.1.0` for `open_model_zoo` based on
https://www.intel.in/content/www/in/en/support/articles/000055510/boards-and-kits/neural-compute-sticks.html

If so, could you switch to `master` branch for `open_model_zoo` and try to run?
In my environment I can't even build `2022.1.0` (omz) with `2023.0` (openvino)

**Comment by TolyaTalamanov** [comment]
> > @TolyaTalamanov I have attached the steps that i have followed during the installation of openvino environment on raspberry pi 4 I have mentioned the version in brackets for each package installed.
> > [Building Open Source OpenVINO.docx](https://github.com/openvinotoolkit/open_model_zoo/files/11513440/Building.Open.Source.OpenVINO.docx)
> 
> I can see that you're using `4.7.0` branch for `opencv`.
> 
> ```
> git clone --depth 1 --branch 4.7.0 https://github.com/opencv/opencv.git
> ```
> 
> and `2022.1.0` for `open_model_zoo` based on https://www.intel.in/content/www/in/en/support/articles/000055510/boards-and-kits/neural-compute-sticks.html
> 
> If so, could you switch to `master` branch for `open_model_zoo` and try to run? In my environment I can't even build `2022.1.0` (omz) with `2023.0` (openvino)

Also make sure that `LD_LIBRARY_PATH` points to the `opencv` you built from sources.
```
export LD_LIBRARY_PATH=<path-to-opencv>/build/lib/:$LD_LIBRARY_PATH
```

**Comment by andrei-kochin** [comment]
@Dev-Divyendh have you followed suggested steps? can this issue be closed?
