### ISSUE TITLE
Need help running demos on multiple Myriad sticks

### ISSUE THREAD

**Issue by ashwanth-07** [openvinotoolkit/open_model_zoo#3746]
I am trying to ran python face recognition demo using 3 Intel Movidius sticks,
The demo run well when one movidius is connected, but when I use 3 movidius sticks ,I dont know how to assign each model to a movidius stick, since we use the generic name MYRIAD for the device flags.
Kindly help with the issue

**Comment by Wovchena** [comment]
OpenVINO adds suffixes to "MYRIAD" device names if there is more than one stick. You can print every available device with `python3 -c "from openvino.runtime import Core; print(Core().available_devices)"`. You should be able to see MYRIAD names there.
