### ISSUE TITLE
face_recognition_demo can't run on Arc GPU. RuntimeError: Failed to create plugin /home/a380/miniconda3/envs/ov2022.3/lib/python3.8/site-packages/openvino/libs/libopenvino_intel_gpu_plugin.so for device GPU

### ISSUE THREAD

**Issue by KiwiHana** [openvinotoolkit/open_model_zoo#3767]
face_recognition_demo can't run on A380. This device disable iGPU, GPU means A380.

(ov2022.3) a380@a380:~/open_model_zoo/demos/face_recognition_demo/python$ python face_recognition_demo.py -i face_gallery/backgroud_1080.mp4 --run_detector -m_fd intel/face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.xml -m_lm intel/landmarks-regression-retail-0009/FP16-INT8/landmarks-regression-retail-0009.xml -m_reid intel/face-reidentification-retail-0095/FP16-INT8/face-reidentification-retail-0095.xml -d_fd GPU

[ INFO ] OpenVINO Runtime
[ INFO ]        build: 2022.3.0-9052-9752fafe8eb-releases/2022/3
[ INFO ] Reading Face Detection model intel/face-detection-adas-0001/FP16-INT8/face-detection-adas-0001.xml
[ INFO ] Reading Landmarks Detection model intel/landmarks-regression-retail-0009/FP16-INT8/landmarks-regression-retail-0009.xml
[ INFO ] Reading Face Reidentification model intel/face-reidentification-retail-0095/FP16-INT8/face-reidentification-retail-0095.xml
Traceback (most recent call last):
  File "face_recognition_demo.py", line 268, in <module>
    sys.exit(main() or 0)
  File "face_recognition_demo.py", line 211, in main
    frame_processor = FrameProcessor(args)
  File "face_recognition_demo.py", line 137, in __init__
    self.face_detector.deploy(args.d_fd)
  File "/home/a380/open_model_zoo/demos/face_recognition_demo/python/ie_module.py", line 33, in deploy
    compiled_model = self.core.compile_model(self.model, device)
  File "/home/a380/miniconda3/envs/ov2022.3/lib/python3.8/site-packages/openvino/runtime/ie_api.py", line 399, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Failed to create plugin /home/a380/miniconda3/envs/ov2022.3/lib/python3.8/site-packages/openvino/libs/libopenvino_intel_gpu_plugin.so for device GPU
Please, check your environment
Check '!supported_devices.empty()' failed at src/plugins/intel_gpu/src/runtime/ocl/ocl_device_detector.cpp:212:
[GPU] No supported OCL devices found or unexpected error happened during devices query.
[GPU] Please check OpenVINO documentation for GPU drivers setup guide.

**Comment by Wovchena** [comment]
Have you installed GPU drivers as the error message suggests?
