### ISSUE TITLE
how can i train road-segmentation-adas-0001 with my own datasets?

### ISSUE THREAD

**Issue by SorrowKiss** [openvinotoolkit/open_model_zoo#3773]
I would like to know where can I get the training code for this pre-trained model?
or the orignial name of it?
I hope  I can train of fine-tune it on my own dataset. 
Getting the orignial artical and the orignial is also acceptiable. RGB based ofcource.
Thanks for helping:)

**Comment by Wovchena** [comment]
@sovrasov, @a-a-egorovich, can you point to training code, if it exists?

**Comment by Wovchena** [comment]
They say the code can't be shared
