### ISSUE TITLE
Pytorch source code for retrain person-attributes-recognition-crossroad-0230 Model

### ISSUE THREAD

**Issue by shekarneo** [openvinotoolkit/open_model_zoo#3783]
Where do i find the source code to retrain **person-attributes-recognition-crossroad-0230** model.

**Comment by andrei-kochin** [comment]
@shekarneo  this is Intel pre-trained model and source code of this model is not shared unfortunately

**Comment by Wovchena** [comment]
@sovrasov, @a-a-egorovich, can you point to training code, if it exists?

**Comment by Wovchena** [comment]
The code can't be shared

**Comment by shekarneo** [comment]
How do i retrain the model!
