### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by HejhGitHub** [openvinotoolkit/open_model_zoo#3803]
when   run  the  code      open_model_zoo/demos/segmentation_demo /cpp/
terminate called after throwing an instance of 'ov::Exception'
  what():  [ PARAMETER_MISMATCH ] Failed to set input blob with precision: FP32, if CNNNetwork input blob precision is: U8

**Comment by HejhGitHub** [comment]
ov::Core core;
std::unique_ptr<SegmentationModel> model(new SegmentationModel(model_path_, true, ""));
model->setInputsPreprocessing(true, "123.675 116.28 103.53", "58.395 57.12 57.375");

**Comment by HejhGitHub** [comment]
ov::preprocess::PrePostProcessor ppp(model);
 ppp.input().tensor().set_element_type(ov::element::u8).set_layout({"NHWC"});
 if (useAutoResize) {
    ppp.input().tensor().set_spatial_dynamic_shape();

    ppp.input()
        .preprocess()
        .convert_element_type(ov::element::f32)
        .resize(ov::preprocess::ResizeAlgorithm::RESIZE_LINEAR);
  }

  ppp.input().model().set_layout(inputLayout);
  model = ppp.build();

**Comment by HejhGitHub** [comment]
```
ov::preprocess::PrePostProcessor ppp(model);
ppp.input().tensor().set_element_type(ov::element::u8).set_layout({"NHWC"});
if (useAutoResize) {
    ppp.input().tensor().set_spatial_dynamic_shape();

    ppp.input()
        .preprocess()
        .convert_element_type(ov::element::f32)
        .resize(ov::preprocess::ResizeAlgorithm::RESIZE_LINEAR);
  }

  ppp.input().model().set_layout(inputLayout);
  model = ppp.build();
```

**Comment by Wovchena** [comment]
Hi. I have a feeling that the problem was already resolved, but I can't find a corresponding PR quickly. Try latest master.
