### ISSUE TITLE
Error in running "multi_camera_multi_target_tracking_demo.py"

### ISSUE THREAD

**Issue by zhuo-yoyowz** [openvinotoolkit/open_model_zoo#3809]
I ran into this error when running "demos/multi_camera_multi_target_tracking_demo.py" using command
`python multi_camera_multi_target_tracking_demo.py  -i video/video1.mp4 video/video2.mp4 --m_detector intel/person-detection-retail-0013/FP16/person-detection-retail-0013.xml --m_reid intel/person-reidentification-retail-0277/FP16/person-reidentification-retail-0277.xml --config configs/person.py`

![image](https://github.com/openvinotoolkit/open_model_zoo/assets/35246475/0a8f921d-52ee-443c-a700-5075bef6b7c0)

I used:
openvino                     2023.0.0
openvino-dev                 2023.0.0
numpy                        1.23.4
scikit-learn                 1.2.2
scipy                        1.10.0
Python 3.10.9

Could you help with the issue? Thanks!

**Comment by Wovchena** [comment]
For now you can use a workaround from https://github.com/openvinotoolkit/open_model_zoo/issues/3715

Duplicate
