### ISSUE TITLE
doc error: `device_support.md` table fails to layout -- get raw markdown instead

### ISSUE THREAD

**Issue by diablodale** [openvinotoolkit/open_model_zoo#3819]
At https://docs.openvino.ai/2023.0/omz_models_public_device_support.html you can see the table is not rendered. Instead, raw markdown is seen.
![image](https://github.com/openvinotoolkit/open_model_zoo/assets/679350/3e90a6ac-e305-4ea3-a731-8e9edde325e3)

### Setup

* Windows Chrome v115.0.5790.110

### Repro

1. visit https://docs.openvino.ai/2023.0/omz_models_public_device_support.html

### Result

Raw markdown.

### Expected

html table layout rendered from the markdown

### Notes

I see some em-dashes on the second row of markdown. Those symbols in row 2 must be hyphen-minus symbols with ascii `0x2d`

**Comment by Wovchena** [comment]
@tsavina, please, summon someone to fix it

**Comment by tsavina** [comment]
Addressed in https://github.com/openvinotoolkit/open_model_zoo/pull/3820

**Comment by diablodale** [comment]
thx, looks good to me on live site
