### ISSUE TITLE
Issue running sound classification demo

### ISSUE THREAD

**Issue by NeethuES-intel** [openvinotoolkit/open_model_zoo#3858]
I converted the acl.onnx model to IR format using mo tool. However when I run the demo program I am getting network unreadable error 
I followed the instructions here https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/sound_classification_demo/python
I am getting the same error when trying with aclnet-int8
Please help resolve this issue
```
python3 sound_classification_demo.py -i /home///gun-gunshot-01.wav -m /home////public/aclnet/aclnet.xml --sample_rate 16000
[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] Reading model /home////public/aclnet/aclnet.xml
Traceback (most recent call last):
  File "sound_classification_demo.py", line 193, in <module>
    main()
  File "sound_classification_demo.py", line 141, in main
    model = core.read_model(args.model)
RuntimeError: Check 'false' failed at src/inference/src/core.cpp:100:
[ NETWORK_NOT_READ ] Unable to read the model: /home////public/aclnet/aclnet.xml Please check that model format: xml is supported and the model is correct. Available frontends: ir tflite tf pytorch onnx paddle 
```

**Comment by NeethuES-intel** [comment]
those were my machine credentials, i deleted them, since I don't wan them out in public :-)
paths are all correct

**Comment by Wovchena** [comment]
I see only two possible reasons:
1. There's version mismatch between mo and OpenVINO Runtime. Run `mo --version` and compare that to what the demo prints.
2. File path is incorrect. You can try running `python3 -c "import openvino.runtime as ov; ov.Core().read_model('XML_PATH')"` to make sure there's nothing in demo itself causing the problem.
    BTW, the usual path is `public/aclnet/FP16/aclnet.xml` maybe you miss `FP16`.

**Comment by NeethuES-intel** [comment]
Thank you. It was version mismatch, but now I am getting a different error. Any pointers ?
[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] Reading model /home////public/aclnet/aclnet_des_53.xml
Traceback (most recent call last):
  File "sound_classification_demo.py", line 193, in <module>
    main()
  File "sound_classification_demo.py", line 151, in main
    batch_size, channels, one, length = model.inputs[0].shape
ValueError: get_shape was called on a descriptor::Tensor with dynamic shape

**Comment by NeethuES-intel** [comment]
Both mo & openvino runtime have the same versions. I generated the IR by running the mo command - mo --input_model aclnet_des_53.onnx 

[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2023.0.1-11005-fa1c41994f3-releases/2023/0

mo --version
Version of Model Optimizer is: 2023.0.1-11005-fa1c41994f3-releases/2023/0

**Comment by Wovchena** [comment]
The demo supports static shapes only.

One option is to update the demo to support dynamic shapes. But I'm not going to help here.

Another option is to set shapes to be static at `mo` stage. Regenerate IR by running `mo --input_model aclnet_des_53.onnx --input_shape=[1,1,1,16000]`. Assuming your `aclnet_des_53.onnx` is similar to one we have in https://github.com/openvinotoolkit/open_model_zoo/blob/f08b9b080b240b4abd08830542ef532deeaf1da3/models/public/aclnet/model.yml#L33C2-L33C2

**Comment by NeethuES-intel** [comment]
I now get a channel issue. Any suggestions on where I can get the sample audio from openvino repo? I got this input audio from google.
```[ INFO ] OpenVINO Runtime
[ INFO ] 	build: 2023.0.1-11005-fa1c41994f3-releases/2023/0
[ INFO ] Reading model /home////public/aclnet/aclnet_des_53.xml
[ INFO ] The model /home////public/aclnet/aclnet_des_53.xml is loaded to CPU
Traceback (most recent call last):
  File "sound_classification_demo.py", line 193, in <module>
    main()
  File "sound_classification_demo.py", line 171, in main
    audio = AudioSource(args.input, channels=channels, samplerate=args.sample_rate)
  File "sound_classification_demo.py", line 67, in __init__
    raise RuntimeError("Audio has unsupported number of channels - {} (expected {})"
RuntimeError: Audio has unsupported number of channels - 2 (expected 1)
```

**Comment by Wovchena** [comment]
https://storage.openvinotoolkit.org/models_contrib/speech/2021.2/librispeech_s5/how_are_you_doing_today.wav

**Comment by NeethuES-intel** [comment]
Thank a lot @Wovchena. Demo worked :-)
