### ISSUE TITLE
 omz_downloader command not found

### ISSUE THREAD

**Issue by amaancoder** [openvinotoolkit/open_model_zoo#3897]
I want to run a openvinho demo,  for this I am getting this command   omz_downloader --all
I am getting this error omz_downloader command not found, how to solve this issue. I am using a windows pc and I have already installed omz_tools

**Comment by Wovchena** [comment]
`omz_tools` installation brings `omz_downloader` for sure. Check your installation. Alternatively you can run https://github.com/openvinotoolkit/open_model_zoo/blob/866e054513a65de319f20b243c6d9920c2a3e36c/tools/model_tools/downloader.py directly without installation

**Comment by amaancoder** [comment]
Hi @Wovchena  

Hi I have already downloaded openvino Development_tools , omz_tools is also installed  below is the screenshot
<img width="642" alt="Screenshot 2024-01-25 140700" src="https://github.com/openvinotoolkit/open_model_zoo/assets/61614379/5662788f-04ce-4e24-9b96-81776a10b1b4">
<img width="1280" alt="Screenshot 2024-01-25 141016" src="https://github.com/openvinotoolkit/open_model_zoo/assets/61614379/1c3e920c-e466-43e0-9d98-d96272a84f4d">

Also I am trying to run a demo , 

As  u can see screen shot below while running command  while running the command omz_downloader --list models.lst I am getting this error , can it be related to env variables

**Comment by Wovchena** [comment]
I think so. Maybe the problem is that you use different environments. Try running `pip show omz_tools` and  `pip show openvino-dev` from the same cmd terminal which you use to run omz_downloader. Not from IDE terminal
