### ISSUE TITLE
demos: unify no_show

### ISSUE THREAD

**Issue by Wovchena** [openvinotoolkit/open_model_zoo#391]
Variables `no_show_processed_video` for demos should be renamed to `no_show_message`. Help messages for `-no_show` should also be updated to `Optional. Don't show output`.
I would be nice to do the same update for IE samples.

**Comment by vladimir-dudnik** [comment]
@Wovchena seems we may close this as done?

**Comment by Wovchena** [comment]
There are still some minor differences. For example `Optional. Do not show processed video.` as a help message in https://github.com/openvinotoolkit/open_model_zoo/tree/develop/demos/interactive_face_detection_demo#running
I also had an idea that we could rename it to just `show` or even abbreviate it to `-s` because gflags automatically generates option with `no` prefix.

**Comment by vladimir-dudnik** [comment]
@Wovchena what about now? have we unified `no_show` option?

**Comment by Wovchena** [comment]
Nope

**Comment by vladimir-dudnik** [comment]
fix merged
