### ISSUE TITLE
How to Postprocess data from product-detection-100 openvino model while usinv ovms 

### ISSUE THREAD

**Issue by NeethuES-intel** [openvinotoolkit/open_model_zoo#3963]
I followed the vehicle detection example below to setup pipeline through ovms using openvino [product-detection-100 model](https://docs.openvino.ai/2022.3/omz_models_model_product_detection_0001.html#)
https://github.com/openvinotoolkit/model_server/blob/main/demos/vehicle_analysis_pipeline/python/vehicles_analysis_pipeline.py

I was able to preprocess data & pass it to inference, however I am unable to postprocess the output. 
Can I get some help with postprocessing ? Any example on how to postprocess the output will help.

Following is the output that I am receiving -
[outputs { key: "868" value { dtype: DT_FLOAT tensor_shape { dim { size: 1 } dim { size: 1 } dim { size: 200 } dim { size: 7 } } tensor_content: "\000\000\000\000\000\000\000@=\370\223=\314l\371=\334\334\322=^\177\215>~{\n?\000\000\000\000\000\000@@\346\247u?X\2429?\320Q\312=\366\333_?h\006\370>\000\000\000\000\000\0000A\332\277\177?\0366\267>\036\253\314=\346\216\035?\016\365\025?\000\000\000\000\000\0000A\323\215c=\346\3169?t\263\334=l/?\373S\372>\000\000\000\000\000\000PAE\306u?\274\264\372=N\241\304=\031\014\216>\352A\n?\000\000\200\277\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\0`

**Comment by Wovchena** [comment]
Expect a reply in https://github.com/openvinotoolkit/model_server/issues/2529
