### ISSUE TITLE
How do I save the output results of the gaze_estimation_demo?

### ISSUE THREAD

**Issue by wzr0108** [openvinotoolkit/open_model_zoo#3973]
I run the following command, and I can get the output video. The command line also outputs information like the Gaze vector, but I want to save the Gaze vector locally. Additionally, I would like to know how to convert the three-dimensional Gaze vector into two-dimensional Gaze angles
```
/root/omz_demos_build/intel64/Release/gaze_estimation_demo \
  -d CPU \
  -i ./0007_03_1.249_59.412.MP4 \
  -o output.avi \
  -m openvino_dir/open_model_zoo/tools/model_tools/intel/gaze-estimation-adas-0002/FP32/gaze-estimation-adas-0002.xml \
  -m_fd /openvino_dir/open_model_zoo/tools/model_tools/intel/face-detection-retail-0004/FP32/face-detection-retail-0004.xml \
  -m_hp openvino_dir/open_model_zoo/tools/model_tools/intel/head-pose-estimation-adas-0001/FP32/head-pose-estimation-adas-0001.xml \
  -m_lm openvino_dir/open_model_zoo/tools/model_tools/intel/facial-landmarks-35-adas-0002/FP32/facial-landmarks-35-adas-0002.xml \
  -m_es openvino_dir/open_model_zoo/tools/model_tools/public/open-closed-eye-0001/open-closed-eye.onnx \
  -no_show \
  -r
```
![output avi_20240908_033438 821](https://github.com/user-attachments/assets/ef18b73d-0cc3-42a1-b6c9-4fdee56552f7)
```
[ DEBUG ] Head pose angles (yaw, pitch, roll): [-2.287, -9.02149, -0.952856]
[ DEBUG ] Gaze vector (x, y, z): [0.144119, -0.0539841, -0.988087]
[ DEBUG ] --End of inference results--

[ INFO ] Metrics report:
[ INFO ]        Latency: 8.1 ms
[ INFO ]        FPS: 117.3
```

**Comment by Wovchena** [comment]
I don't think there are dedicated features for that.
You can forward std out to a file.
As for the converting the three-dimensional Gaze vector into two-dimensional Gaze angles, you can research how to project a vector onto a plane. So Wikipedia or the demo source code code: https://github.com/openvinotoolkit/open_model_zoo/blob/f798fd62d66c273c757ab9c6038a47a364b726d0/demos/gaze_estimation_demo/cpp/src/results_marker.cpp#L114 and https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/intel/gaze-estimation-adas-0002#example-and-gaze-vector-definition may help.
