### ISSUE TITLE
python_demos: segmentation demo can not work in proper way for more than 21 classes segmentation

### ISSUE THREAD

**Issue by eaidova** [openvinotoolkit/open_model_zoo#411]
Python segmentation demo has hardcoded classes color mapping for 21 class:
https://github.com/opencv/open_model_zoo/blob/develop/demos/python_demos/segmentation_demo/segmentation_demo.py#L27
and also uses casting to 20 for all classes more than 20: https://github.com/opencv/open_model_zoo/blob/develop/demos/python_demos/segmentation_demo/segmentation_demo.py#L140
It leads to incorrect results for running models trained with more than 21 class datasets.

Although Open Model Zoo does not contain such models, it can become a potential problem for running the demo on users' models. I think we should at least mention it in the readme to this demo.

**Comment by Wovchena** [comment]
Cpp `segmentation_demo` adds random colors if it lacks predefined ones. May be the python demo should do the same.

**Comment by eaidova** [comment]
Yes, it is a nice solution, I also think about it.
My experience says that random in python sometimes works not as expected (even used the same seed, it gives different results on different machines), so need to be careful with it.

Also I can suggest to use file with color mapping for overwrite defult. Some benchmarks use colored segmentation masks as input for checking accuracy and them expects following their color coding.

**Comment by Wovchena** [comment]
I didn't think about const seed, but it could be nice. And cpp demo should also do that.
> Also, I can suggest using a file with color mapping for overwriting the default.

Does it match this: https://github.com/opencv/open_model_zoo/blob/ab1e04fdd3db9cf8811a596d71f13b1f513dc76f/demos/common/samples/common.hpp#L412

**Comment by eaidova** [comment]
> Does it match this
I do not think about bounding boxes... It has a text label description and score in the same image with drawn box, so the color-coding not so important as for segmentation, where output is just image with labeled pixels and more difficult to understand the correspondence of class and color. But yes, i think, it can look in such way.
In Accuracy Checker, we use json for storing color coding like
```json
"segmentation_colors": [[255, 0, 0], [0, 255, 0], [0, 0, 255]]
```
I am not sure that using this approach is suitable for demos too...
