### ISSUE TITLE
Consider forcing lowercase names for models

### ISSUE THREAD

**Issue by alalek** [openvinotoolkit/open_model_zoo#894]
to keep "coding" style consistent.

Issue with ['Sphereface'](https://github.com/opencv/open_model_zoo/tree/2020.1/models/public/Sphereface).

Full list example: https://github.com/opencv/open_model_zoo/tree/2020.1/models/public

relates #207

**Comment by jgespino** [comment]
@IRDonch Could you please take a look at this?

**Comment by IRDonch** [comment]
I'd like to, but I don't want to rename `Sphereface` now, as I think it would be a gratuitous compatibility break. If we ever remove it, I'll tighten the name validation rules in the downloader to only allow lowercase letters. For now, I'm just going to reject uppercase model names in code review.

**Comment by vladimir-dudnik** [comment]
agreed to keep existing names `as is` and do not introduce new names with upper case. close this,
